### ISSUE TITLE
6.22.02 build error on macOS 10.15

### ISSUE THREAD

**Issue by cjones051073** [root-project/root#6366] opened 2020-09-16 10:34 UTC
6.22.02 build error on mac OS 10.15

Building 6.22.02 from source on macOS fails. Note I maintain the ROOT6 port in MacPorts, and my ultimate aim here is to update that build to 6.22.02 (currently 6.22.00). We use a number additional options and dependencies, hence the cmake configure command is a bit long (apologies).

6.22.00 builds just fine using the exact same configuration, so the issue is new to 6.22.02.

I have attached the output from the configure and build steps (as outlined below).

[configure.log](https://github.com/root-project/root/files/5231518/configure.log)

[build.log](https://github.com/root-project/root/files/5231520/build.log)

Unfortunately the build log error messages aren't hugely helpful (at least to me) in pointing to the issue, so I am hoping someone can offer suggestions as to where to look

First indication of a problem is
```
[ 74%] Linking CXX shared library ../lib/libCore.so
<snip>
make[1]: *** read jobs pipe: Resource temporarily unavailable.  Stop.
make[1]: *** Waiting for unfinished jobs....[ 74%] Linking CXX shared library ../lib/libCore.so
```

## Expected behavior
Builds OK.

## To Reproduce
```
git clone git@github.com:root-project/root.git
cd root
git checkout v6-22-02
cd ..
mkdir install build
cd build
cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -Dgnuinstall=ON -Drpath=ON -DCMAKE_INSTALL_PREFIX="/opt/local/libexec/root6" -DCMAKE_INSTALL_SYSCONFDIR="/opt/local/libexec/root6/etc/root" -DCMAKE_INSTALL_NAME_DIR="/opt/local/libexec/root6/lib/root" -Dfortran=ON -Dbuiltin_davix=OFF -Dbuiltin_freetype=ON -Dbuiltin_glew=ON -Dbuiltin_pcre=OFF -Dbuiltin_zlib=ON -Dbuiltin_lzma=OFF -Dbuiltin_tbb=OFF -Dbuiltin_afterimage=ON -Ddavix=ON -Dfftw3=OFF -Dkrb5=OFF -Dmysql=OFF -Dsqlite=OFF -Dodbc=OFF -Dopengl=ON -Dpythia6=OFF -Dpythia8=OFF -Droofit=ON -Dssl=ON -Dxml=ON -Dpyroot=ON -Dfitsio=OFF -Dgsl_shared=ON -Dbuiltin_gsl=OFF -Dpgsql=OFF -Ddcache=OFF -Dchirp=OFF -Dhdfs=OFF -Druby=OFF -Dminuit2=ON -Dtmva=ON -Dqt=OFF -Dqtgsi=OFF -Dgviz=ON -Dsoversion=ON -Dcxx11=ON -Dcxx14=OFF -Dcxx17=ON -Dlibcxx=ON -Dxrootd=ON -Dbuiltin_ftgl=ON -Dmathmore=ON -Dgenvector=ON -Dmemstat=ON -Dunuran=ON -Dgdml=ON -Dhttp=ON -Dvc=OFF -Dastiff=ON -Dgeocad=OFF -Dr=OFF -Droot7=ON -Dbuiltin_veccore=OFF -DPNG_LIBRARY=/opt/local/lib/libpng.dylib -DPNG_PNG_INCLUDE_DIR=/opt/local/include -Druntime_cxxmodules=OFF -DPYTHON_INCLUDE_DIR="/opt/local/Library/Frameworks/Python.framework/Versions/3.8/Headers" -DPYTHON_EXECUTABLE="/opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8" -DPYTHON_LIBRARY="/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib" -DXROOTD_INCLUDE_DIR="/opt/local/include/xrootd" -DGRAPHVIZ_INCLUDE_DIR="/opt/local/include" -DGSL_CONFIG_EXECUTABLE="/opt/local/bin/gsl-config" -DLIBXML2_INCLUDE_DIR="/opt/local/include/libxml2" -DLIBXML2_LIBRARIES="/opt/local/lib/libxml2.dylib" -DLIBXML2_LIBRARY="/opt/local/lib/libxml2.dylib" -DLIBXML2_XMLLINT_EXECUTABLE="/opt/local/bin/xmllint" -Dcocoa=ON -Dx11=OFF -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.15" -DCMAKE_OSX_SYSROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk" -DCMAKE_INSTALL_PREFIX=/Users/chris/Projects/ROOT/install ../root 2>&1 | tee ../configure.log
cmake --build . -- -j8 2>&1 | tee ../build.log
```

**Comment by cjones051073** [comment] 2020-09-16 15:49
Update. The issues appears to be some sort of race-like condition in the build configuration, as disabling parallel builds

```
cmake --build . 2>&1 | tee ../build.log
```

works just fine.

**Comment by Axel-Naumann** [comment] 2020-09-17 08:09
IIRC that's just the build running out of file (or other) handles. You should be able to do parallel builds, but not as parallel, or raise the limits. Could you try?

**Comment by cjones051073** [comment] 2020-09-17 08:10
How would I do that ? As far as I am aware I have no limits set.

Also, why would this only affect 6.22.02 ? The very same machine has no problems with any other ROOT versions ?

**Comment by Axel-Naumann** [comment] 2020-09-17 08:17
Right, so here's the Internet's cue: http://gnu-make.2324884.n4.nabble.com/EAGAIN-in-read-jobs-pipe-tp1224p1228.html

`ulimit -a` shows you "Maximum number of open file descriptors"; for me it shows the macOS default of 256 which is notoriously low. Try setting that tom 1024 and see whether it helps?

**Comment by cjones051073** [comment] 2020-09-17 08:27
```
Oberon ~/Projects/MacPorts/ports > ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                2560
```

So no, the limit is not 256.

Please also note even if this is related to the problem, changing ulimit is not a practical solution in terms of fixing our automated builds in MacPorts, as I cannot request every user and the build systems make any changes to these settings. Also note we have NEVER run into an issue with any other port, or ROOT version, prior to 6.22.02, so I still maintain even if this is what is happening the core issue is something in the ROOT build system, new in 6.22.02, that is causing this.

**Comment by Axel-Naumann** [comment] 2020-09-17 12:02
Thanks. I'm evaluating what might be the cause, and the number of file handles is the only possible cause that I am aware of. If it's not that then I don't know. I remember this issue in the old days with Cygwin's `make`. Do you see the same issue with ninja? I suppose you use Macport's `make`?

**Comment by cjones051073** [comment] 2020-09-17 12:03
We use the macOS system make `/usr/bin/make`, not one supply by macports.

**Comment by Axel-Naumann** [comment] 2020-09-17 12:23
Thanks. Does Ninja show the same issue?

**Comment by cjones051073** [comment] 2020-09-17 12:24
how do I build with ninja ?

**Comment by cjones051073** [comment] 2020-09-17 12:25
also note I also do not see the issue with a default configuration. I only see it when I enabled additional features. I presume you also test these in your builds ?

**Comment by Axel-Naumann** [comment] 2020-09-17 12:27
`cmake -G Ninja`. And you need `ninja`; you can grab it from https://github.com/ninja-build/ninja/releases but I bet  MacPorts already has is?

**Comment by Axel-Naumann** [comment] 2020-09-17 12:29
Indeed we have a couple of options enabled - but as MacOS proper doesn't offer a lot we also don't build with a lot. But this part `-G "CodeBlocks - Unix Makefiles"` is probably crucial. How does `-G "Unix Makefiles"` work?

**Comment by cjones051073** [comment] 2020-09-17 12:31
Honestly, I don't know much about that. I just cloned the cmake configuration from the exact command used internally by the MacPorts build, so its added by that. I will have to investigate the reasons for this.

**Comment by cjones051073** [comment] 2020-09-17 13:10
OK, have switch the MacPorts build to use ninja. We run a test to see if this shows the issue or not.

**Comment by cjones051073** [comment] 2020-09-17 13:52
ninja based builds work just fine in parallel, so this does seem a good way to sidestep the gnu make build issues, particularly as I now understand ninja is anyway the primary build system used by ROOT devs.

**Comment by Axel-Naumann** [comment] 2020-10-06 07:17
OK closing - let me know if there's something we can do on our side.

**Closed by Axel-Naumann** 2020-10-06 07:17 UTC
Labels: bug
