### ISSUE TITLE
ROOT blocks matplotlib

### ISSUE THREAD

**Issue by wiso** [root-project/root#6592] opened 2020-10-08 17:48 UTC
In a python interactive shell

    import ROOT
    from matplotlib import pyplot as plt
    fig, ax = plt.subplots()

this freeze my program. If I don't import ROOT it works.

fedora 32
matplotlib 3.2.2
ROOT 6.22/02

**Comment by etejedor** [comment] 2020-10-09 07:21
I believe this might be a duplicate of:

https://sft.its.cern.ch/jira/browse/ROOT-7909

Do you observe this interference on MacOS? If I understand correctly, it is the third line of code that freezes?

**Comment by wiso** [comment] 2020-10-09 08:11
yes, it is the last line that freezes. By the way this is not very reproducible. I am on fedora 32

**Comment by stwunsch** [comment] 2020-10-09 10:39
@wiso Could you try the following? 

```python
import ROOT
ROOT.PyConfig.StartGUIThread = False # Do not enable the interactive graphics in ROOT
# ROOT.SetBatch(True) # This should have the same effect!
from matplotlib import pyplot as plt
fig, ax = plt.subplots()
```

There seems to be an inference of the hooks installed by ROOT and matplotlib to show the graphics.

**Comment by wiso** [comment] 2020-10-15 15:17
@etejedor yes, it is the last line
@stwunsch unfortunatly I can't reproduce my problem anymore... your code works

**Comment by etejedor** [comment] 2020-10-16 09:34
If @stwunsch suggestion works, it looks like the issue is a (known) interference between matplotlib and ROOT, since they both use inputhooks to implement their event loops for graphics. ROOT only uses the inputhook mechanism when in interactive mode. Do you observe a different behaviour of your initial code when you run it as a script or from the Python prompt?

In any case, if you want to use only matplotlib for graphics, using `ROOT.PyConfig.StartGUIThread = False` stops ROOT from configuring its graphics, which prevents the interference with matplotlib.

**Comment by etejedor** [comment] 2020-10-21 14:46
@wiso, if you agree, I would leave https://sft.its.cern.ch/jira/browse/ROOT-7909 open (since the interference between ROOT graphics and matplotlib exists and is reproducible on MacOS), and for your case you can use @stwunsch suggestion if you just need matplotlib graphics?

**Comment by wiso** [comment] 2020-10-21 14:50
ok, thanks

**Closed** 2020-10-21 15:19 UTC
Labels: bug, in:PyROOT
