### ISSUE TITLE
Problems compiling root 6.24.00 with gcc 11 on Fedora 34

### ISSUE THREAD

**Issue by ellert** [root-project/root#8071] opened 2021-05-03 08:53 UTC
### Describe the bug

When running make test on a root build on Fedora 34 (using gcc 11) several tests fail that do not fail on Fedora 33 (using gcc 10).

### Expected behavior
No test failures.

### To Reproduce
1. Build root 6.24.00 on Fedora 34.
2. Run make test

### Setup
1. ROOT version: 6.24.00
2. Operating system: Fedora Linux 34

### Additional context
The kind of errors vary. But many of them seems to be related to disagreement on the size of data structures. Here are some examples: [test.log.gz](https://github.com/root-project/root/files/6413774/test.log.gz)

Some examples: 
```
Error in <TInterpreter::InspectMembers>: TClass and cling disagree on the size of the class ROOT::Experimental::RAttrLine, respectively 368 400
Error in <TInterpreter::InspectMembers>: TClass and cling disagree on the size of the class ROOT::Experimental::RAttrColor, respectively 64 72
Error in <TInterpreter::InspectMembers>: TClass and cling disagree on the size of the class ROOT::Experimental::RAttrBase, respectively 64 72
```
and
```
python3.9: /builddir/build/BUILD/root-6.24.00/roofit/roofitcore/src/RooArgSet.cxx:108: static void* RooArgSet::operator new(size_t): Assertion `sizeof(RooArgSet) == bytes' failed.
```
Does anyone have any idea what is going on?

**Comment by scott-snyder** [comment] 2021-05-09 01:20
I think the problem is that the gcc 11 implementation of std::tuple uses
no_unique_address if it's available, but it spells it 
```
__no_unique_address__
```
,
which cling doesn't recognize.

I just ran into this building ATLAS code with gcc 11 / root 6.24.

This patch seems to help things for me.

```
diff --git a/interpreter/llvm/src/tools/clang/include/clang/Basic/Attr.td b/interpreter/llvm/src/tools/clang/include/clang/Basic/Attr.td
index d39b16e62b..bf7f6a922c 100644
--- a/interpreter/llvm/src/tools/clang/include/clang/Basic/Attr.td
+++ b/interpreter/llvm/src/tools/clang/include/clang/Basic/Attr.td
@@ -1423,7 +1423,8 @@ def NeonVectorType : TypeAttr {
 }
 
 def NoUniqueAddress : InheritableAttr, TargetSpecificAttr<TargetItaniumCXXABI> {
-  let Spellings = [CXX11<"", "no_unique_address", 201803>];
+  let Spellings = [CXX11<"", "no_unique_address", 201803>,
+                   CXX11<"", "__no_unique_address__", 201803>];
   let Subjects = SubjectList<[NonBitField], ErrorDiag>;
   let Documentation = [NoUniqueAddressDocs];
 }
```

**Comment by Axel-Naumann** [comment] 2021-05-26 09:36
We were missing an llvm backport: https://github.com/root-project/root/pull/8243

**Comment by Axel-Naumann** [comment] 2021-06-04 09:57
Should be fixed, please let me know if the issue remains and we re-open.

**Closed by Axel-Naumann** 2021-06-04 09:57 UTC
Labels: affects:6.24, bug, in:Cling, priority:default
