### ISSUE TITLE
Wrong TColor constructor is picked when called from python in 6.22/08

### ISSUE THREAD

**Issue by tmadlener** [root-project/root#7790] opened 2021-04-06 14:53 UTC
- [x] Checked for duplicates

At least I could not find any obvious ones that described the same problem. But it might be a more general problem in the python bindings which I have missed.

### Describe the bug

Defining new `TColor`s in python seems to pick the wrong constructor.

### Expected behavior

In previous versions of ROOT (up to 6.20/04) the right constructor was picked here. 

### To Reproduce

```python
import ROOT as r

color_index = r.TColor.GetFreeColorIndex()
print(type(color_index), color_index) # just to be sure that color_index is indeed an int

# This seems to be chosing the TColor(float, float, float, float) constructor
# instead of the TColor(int, float, float, float, const char*, float)
color = r.TColor(color_index, 0.1, 0.2, 0.3)

# This should be 0.1, 0.2, 0.3, but will actually be the color index, 0.1, 0.2
print(color.GetRed(), color.GetBlue(), color.GetGreen())

# Explicitly passing an empty string to the constructor helps in picking the correct constructor
color = r.TColor(color_index + 1, 0.1, 0.2, 0.3, "")
print(color.GetRed(), color.GetBlue(), color.GetGreen()) # now is 0.1, 0.2, 0.3
```

### Setup

ROOT v6.22/08 (built with system gcc 9.3.0 and python 3.8.5) on Ubuntu 20.04

**Comment by vepadulano** [comment] 2021-04-28 12:47
I've tried with the following code

```python
import cppyy

cppyy.cppdef(
    '''
    class Simple{
    public:
        Simple(int a, float b, float c, float d, const char *e = "", float f=1.f) {
            std::cout << "Simple(int a, float b, float c, float d, const char *e = \\"\\", float f=1.f) with arguments:" << std::endl;
            std::cout << "a: " << a << std::endl;
            std::cout << "b: " << b << std::endl;
            std::cout << "c: " << c << std::endl;
            std::cout << "d: " << d << std::endl;
            std::cout << "e: " << e << std::endl;
            std::cout << "f: " << f << std::endl;
        }
        Simple(float a, float b, float c,float d=1.f) {
            std::cout << "Simple(float a, float b, float c,float d=1.f) with arguments:" << std::endl;
            std::cout << "a: " << a << std::endl;
            std::cout << "b: " << b << std::endl;
            std::cout << "c: " << c << std::endl;
            std::cout << "d: " << d << std::endl;
        }
    };

    class Minimal{
    public:
        Minimal(int a, float b, float c=1.0f) {
            std::cout << "Minimal(int a, float b, float c=1.0f) with arguments:" << std::endl;
            std::cout << "a: " << a << std::endl;
            std::cout << "b: " << b << std::endl;
            std::cout << "c: " << c << std::endl;
        }
        Minimal(float a, float b) {
            std::cout << "Minimal(float a, float b) with arguments:" << std::endl;
            std::cout << "a: " << a << std::endl;
            std::cout << "b: " << b << std::endl;
        }
    };
    '''
)

a = int(1)
b = float(2.2)
c = float(3.3)
d = float(4.4)

simple = cppyy.gbl.Simple(a, b, c, d)
minimal = cppyy.gbl.Minimal(a, b)
```

The constructors in `Simple` mimic the constructors of `TColor`. The `Minimal` class should show the same issue with less constructor arguments. Passing an `int` as first argument is not enough to distinguish between these two constructors
```
Minimal(int a, float b, float c=1.0f)
Minimal(float a, float b)
```
This is the result of the script above
```
(cppyy-venv) vpadulan@fedorathinkpad-T550 [~/Projects/rootcode/ROOT-GITHUB-7790]: pip freeze
cppyy==1.9.5
cppyy-backend==1.14.3
cppyy-cling==6.21.6
CPyCppyy==1.12.4
(cppyy-venv) vpadulan@fedorathinkpad-T550 [~/Projects/rootcode/ROOT-GITHUB-7790]: python cppyy_simple_reproducer.py 
Simple(float a, float b, float c,float d=1.f) with arguments:
a: 1
b: 2.2
c: 3.3
d: 4.4
Minimal(float a, float b) with arguments:
a: 1
b: 2.2
```

**Comment by vepadulano** [comment] 2021-04-30 09:49
I found out that what happens in this issue is the intended behaviour when calculating the priority of the different overloads in [CPPMethod::GetPriority](https://github.com/root-project/root/blob/3ba13b74a151460ea1b69763c305f165fba0aeb9/bindings/pyroot/cppyy/CPyCppyy/src/CPPMethod.cxx#L432-L434). The comment specifically says

> prefer methods w/o optional arguments b/c ones with optional arguments are easier to select by providing the optional arguments explicitly

In fact, just by commenting that line I get the correct overload with this other reproducer
```python
import ROOT

ROOT.gInterpreter.Declare(
'''
    class Minimal{
    public:
        Minimal(int a, float b=1.0f) {
            std::cout << "Minimal(int a, float b=1.0f) with arguments:" << std::endl;
            std::cout << "a: " << a << std::endl;
            std::cout << "b: " << b << std::endl;
        }
        Minimal(float a) {
            std::cout << "Minimal(float a)  with arguments:" << std::endl;
            std::cout << "a: " << a << std::endl;
        }
    };
'''
)
minimal = ROOT.Minimal(1)
```
```
vpadulan@fedorathinkpad-T550 [~/Projects/rootcode/ROOT-GITHUB-7790]: python ROOT_minimal_reproducer.py 
Minimal(int a, float b=1.0f) with arguments:
a: 1
b: 1
```

Since this appears to be the intended behaviour, the second option @tmadlener proposes in the original reproducer (i.e. adding an empty string to the TColor constructor) seems to be the right way to go with the default new PyROOT since 6.22

**Comment by vepadulano** [comment] 2021-05-07 07:58
Closing this, let us know if you need any other help :smile: !

**Closed by vepadulano** 2021-05-07 07:58 UTC
Labels: bug, in:PyROOT
