### ISSUE TITLE
[RF] Ranged fits evaluate numeric integrals too often in ROOT master

### ISSUE THREAD

**Issue by smuzaffar** [root-project/root#11637] opened 2022-10-26 13:35 UTC
Hi,
  while testing root master ( commit a0d62ca8ad ) in to CMSSW we noticed that `RooAddPdf::fitTo()` now very slow. The [test](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_6_ROOT626_X_2022-10-25-2300/unitTestLogs/DQMOffline/Alignment#/) takes 6 mins for root 6.24 and 6.26 but for root master it takes over an hour  ( and still does not finish). Running under GDB shows [this stacktrace](https://muzaffar.web.cern.ch/master-RooAddPdf-fitTo.txt) . Any idea what has changed in root master which is causing this slowness?

https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Alignment/src/DiMuonMassBiasClient.cc#L189 is call which is very slow now as compare to root 6.24/6.26

Thanks

**Comment by smuzaffar** [comment] 2022-10-26 14:10
I think https://github.com/root-project/root/compare/99093d95f7...78228fee3b were the changes which caused this issue. There were no issues with root commit 99093d95f7 but once we integrated 78228fee3b then cmssw unit test started to show slowness

**Comment by guitargeek** [comment] 2022-10-26 22:53
Hi, thank you very much for reporting this!

It's indeed a bug that I will fix, but for the CMSSW side we can avoid the problem easily so you can proceed quickly with the update of the ROOT master branch. I have created a PR for that:

https://github.com/cms-sw/cmssw/pull/39867

Indeed, it appears I introduced a bug with recent developments where the overhead when using the `RooFit::Range()` argument blew up. But I suggest you remove this argument to begin with, because the range was the same that is used to define the `InvMass` variable to begin with. So in any case it's better for you to not use `Range()`, and then you also don't hit the code path that has the bug (and you will have less overhead once the bug is gone).

**Comment by guitargeek** [comment] 2022-10-31 13:40
The issue in CMSSW is fixed now by just not doing a ranged fit, but in ROOT master this performance regression still needs to be fixed. Here is a simple reproducer for the problem, with the code extracted from the CMSSW source linked in the initial post:
```c++
  using namespace RooFit;

  RooRealVar x("x", "", 0, 10);

  RooRealVar mean("mu", "", 5.0, 0, 10);
  RooRealVar width("width", "", 1.0, 0.1, 10);
  RooRealVar sigma("sigma", "", 2.0, 0.1, 10);
  RooVoigtian voigt("voigt", "", x, mean, width, sigma);

  RooRealVar lambda("lambda", "", -0.01, -100., 1.);
  RooExponential expo("expo", "", x, lambda);

  RooRealVar b("n_bkg", "", 100., 0, 1000);
  RooRealVar s("n_sig", "", 1000., 0, 10000);

  RooAddPdf model("model", "", {voigt, expo}, {s, b});

  std::unique_ptr<RooDataSet> data{model.generate(x)};

  model.fitTo(*data, Range(0.0, 10.0), PrintLevel(-1));
```

Most likely, this issue was caused by https://github.com/root-project/root/pull/11455. I set the priority to `high` now, because this is a regression that also affects experiment workflows and it needs to be fixed before the 6.28 release for sure! Therefore, this issue is also added to the 6.28 milestone.

**Comment by guitargeek** [comment] 2022-10-31 15:50
I narrowed the issue down to a more simple reproducer:
```
void script()
{
  RooRealVar x{"x", "", -10, 10};
  x.setRange("fit", 0, 10);

  RooGenericPdf gauss{"gauss", "std::exp(-0.5 * (x*x))", x};
  RooRealVar s{"n_sig", "", 1000., 0, 10000};
  RooAddPdf model{"model", "", {gauss}, {s}};

  std::unique_ptr<RooDataSet> data{model.generate(x)};

  // Comment this out and it is fast again
  model.setNormRange("fit");

  std::unique_ptr<RooAbsReal> nll{model.createNLL(*data)};

  for(std::size_t i = 0; i < 1000; ++i) {
    s.setVal(s.getVal() + (i % 2 ? +1 : -1));
    nll->getVal();
  }
}
```

**Comment by guitargeek** [comment] 2022-11-04 17:48
I realized that the problem didn't come from the multi-range fit refactoring, but from the refactoring of the RooRealIntegral constructor:
https://github.com/root-project/root/pull/11597

I have opened a PR to fix it:
https://github.com/root-project/root/pull/11662

**Closed** 2022-11-07 11:31 UTC
Labels: bug, affects:master, priority:high, in:RooFit/RooStats
