### ISSUE TITLE
`undefined reference to 'TChain::kBigNumber'` when ROOT is built without C++17

### ISSUE THREAD

**Issue by veprbl** [root-project/root#9422] opened 2021-12-12 17:37 UTC
- [x] Checked for duplicates

### Describe the bug

ROOT seems to claim (some?) C++14 compatibility. However the current use of `static constexpr` member values are missing external linking support

### To Reproduce

```c++
    std::vector<int> v;
    v.push_back(TChain::kBigNumber); // fail
    v.push_back(1 + TChain::kBigNumber); // fine
```

Also can play with a toy example in https://godbolt.org/z/frn4e8KPd

### Setup

Seen in production with ROOT 6.16 + GCC 4.8.5, but can be also demonstrated with modern GCC running with -std=c++14

### Additional context

See references:

 - https://stackoverflow.com/questions/8016780/undefined-reference-to-static-constexpr-char
 - https://stackoverflow.com/questions/19630570/what-does-it-mean-to-odr-use-something

**Comment by guitargeek** [comment] 2021-12-12 20:52
Hi @veprbl! I can't reproduce this issue myself, even if I configure ROOT with `CMAKE_CXX_STANDARD =14`. So I guess this issue has been fixed in the long time since 6.16 got released? ROOT also only claims C++14 compatibility with the upcoming v6.26 release.

I would close this issue because it works with the new ROOT, and for older versions there is the workaround you are suggesting yourself. But before doing that, I invite @Axel-Naumann to comment as well, who has a better overview on C++ standards and ROOT.

**Comment by veprbl** [comment] 2021-12-12 23:46
@guitargeek Thanks for looking into this. I don't see any fixes for this issue, it would require to "duplicate" the definition in the class'es "main" translation unit, and there are quite a few definitions to go through.

Here is an MRE with c++11, but should be identical for c++14:
```
# root-config --version
6.24/06
# root.exe --version
ROOT Version: 6.24/06
Built for linuxx8664gcc on Sep 02 2021, 14:20:23
From tags/v6-24-06@v6-24-06
# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# cat test.cxx                                                     
#include <vector>
#include <TChain.h>

int func() {
   std::vector<long long> v;
   v.push_back(TChain::kBigNumber); // fail
   v.push_back(TChain::kBigNumber - 1); // fine
   return v.size();
}
# g++ -O0 -std=c++11 `root-config --cflags --libs` test.cxx -o test
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/ccxkwRYF.o: In function `func()':
test.cxx:(.text+0x1a): undefined reference to `TChain::kBigNumber'
collect2: error: ld returned 1 exit status
```

I don't mind if this gets closed with wontfix.

**Comment by Axel-Naumann** [comment] 2021-12-13 08:04
Can you remind us of the output of ROOT v6.16's `root-config --libs`? Are you building against ROOT v6.16 in the above example? ROOT's master does not support GCC 4.8 anymore.

**Comment by veprbl** [comment] 2021-12-13 10:57
> Can you remind us of the output of ROOT v6.16's `root-config --libs`?

Sure

6.16:
```
-L/opt/software/linux-scientific7-x86_64/gcc-4.8.5/root-6.16.00-zmcilzuttugwi3pxlrrp5r3ztoh544sn/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -pthread -Wl,-rpath,/opt/software/linux-scientific7-x86_64/gcc-4.8.5/root-6.16.00-zmcilzuttugwi3pxlrrp5r3ztoh544sn/lib -lm -ldl -rdynamic
```
6.24/06:
```
root-config --libs
-L/path/to/root/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -pthread -lm -ldl -rdynamic
```

> Are you building against ROOT v6.16 in the above example?

In my previous message it was against 6.24/06 built with the same gcc:
```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/path/to/root .. -Dx11=OFF -Dsqlite=OFF -Dtmva=OFF -Dxrootd=OFF -Dpyroot=OFF -Dmlp=OFF -Dssl=OFF -Dhttp=OFF -Dclad=OFF -Ddataframe=OFF -Dpythia6=ON -Dbuiltin_tbb=OFF -Dbuiltin_xrootd=OFF -Dbuiltin_freetype=OFF
```

> ROOT's master does not support GCC 4.8 anymore.

At godbolt link above you can reproduce the same error with GCC 11.2 and clang 13.0.0.

**Comment by Axel-Naumann** [comment] 2021-12-13 16:36
That's indeed a bug; `static constexpr` variables must have a definition somewhere. Thanks for reporting!

**Comment by guitargeek** [comment] 2023-09-28 19:36
Hello again two years later!
I'll close this as "won't fix" now, because ROOTs support for C++14 has stopped:
* https://github.com/root-project/root/pull/13243

For older ROOT versions, there is at least a workaround:
```c++
    int kBigNumberTChain = TChain::kBigNumber;
    v.push_back(kBigNumberTChain);
```

**Closed by guitargeek** 2023-09-28 19:36 UTC
Labels: bug
