### ISSUE TITLE
PyROOT unittest about requirements

### ISSUE THREAD

**Issue by pcanal** [root-project/root#15212] opened 2024-04-11 18:56 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

As seen in https://lcgapp-services.cern.ch/root-jenkins/job/roottest-pullrequests-build/14222/testReport/projectroot.bindings.pyroot.pythonizations/test/pyunittests_pyroot_dependency_versions/

this test fails because of missing access to `scikit-learn` and `xgboost`.

Are those hard requirement of ROOT? 

If they are, why does the configuration succeed?

If they are not, why does the test fail?

### Reproducer

```
test_versions (dependency_versions.DependencyVersions)
Test the versions of the installed packages versus the ... Attempting requirement 'numpy>=1.4.1'
Attempting requirement 'scikit-learn'
Attempting requirement 'xgboost'
Attempting requirement 'numba>=0.47.0; python_version < "3.11"'
Attempting requirement 'numba>=0.57.0; python_version >= "3.11" and python_version < "3.12"'
Attempting requirement 'cffi>=1.9.1'
Attempting requirement 'notebook>=4.4.1'
Attempting requirement 'metakernel>=0.20.0'
Ignore dependency pyspark>=2.4
Ignore dependency dask>=2022.08.1; python_version >= "3.8"
Ignore dependency distributed>=2022.08.1; python_version >= "3.8"

Full path to requirements.txt: /home/sftnight/build/workspace/roottest-pullrequests-build/root/requirements.txt
Details about not matched dependencies:
 - The 'scikit-learn' distribution was not found and is required by the application
 - The 'xgboost' distribution was not found and is required by the application
ERROR
```

### ROOT version

master

### Installation method

Jenkins/CI

### Operating system

Ubuntu 22.04

**Comment by vepadulano** [comment] 2024-04-11 21:45
The unittest works as intended, as do the requirements at `requirements.txt`. ROOT does not enforce any build-time Python dependencies (except for `numpy`) and the packages listed in `requirements.txt`. The unittest is merely checking that our test suite will find the packages it needs for the *optional*, *runtime* dependencies that we want to test ourselves.

What happened is the following:
1. There was the necessity to start testing a certain subset of TMVA, which was never tested before (see https://github.com/root-project/root/issues/15197)
2. The packages were added to `requirements.txt` so that the docker images built for Linux runners of the new CI infrastructure could pick them up (the images are built nightly and they install in the virtual environment of the docker container all the packages in `requirements.txt` available in `master` at the time of building the image).
3. Jenkins has been disabled since more than a week now so these packages were not manually installed on the Linux nodes of the old Jenkins instance.


So I will close this issue as everything was working as intended. Jenkins builds should not longer appear for PRs as far as I am aware. If there is the necessity, a member of the team can manually install those packages on the Jenkins nodes.

**Comment by vepadulano** [comment] 2024-04-12 06:48
> Does it mean that they are optional requirement?

Correct, always has been like this.

> Humm ... but then they become non-optional requirement for developer.

If the developer wants to also run Python-based unittests, yes. I don't see any issue with that.

>  It also means that we can not test the case where they are not installed

In principle we can add a "special" CI image and run that as a separate github action.

> and since we are not testing this configuration one could assume that the configuration is broken (until proven otherwise)

What we are "not testing" is the situation `-Dpyroot=OFF` and no Python package being installed on the same machine... i.e. no need to even bother with Python.

>  i.e. those package are actually required 

No, they are not

**Comment by pcanal** [comment] 2024-04-12 17:01
> If the developer wants to also run Python-based unittests, yes. I don't see any issue with that.

Humm .. I thought a bare `ctest` would run it, so it is the opposite, one would know to add a `-E ` to ignore them.

> No, they are not

Well they "appear" to be because of the test.  The jenkins node was configured however it was (and the user could have the exact same configuration) and a run of `ctest` fails and "clearly" states that those are requirements :)

From my limited view point it seems that we have:
* python support is enabled 
* some optional component is not installed (and I am assuming that the related features are disabled and the actual tests related to those features are not run)
* a test still complains that those optional component are not installed

To make an analogy: this sound like we would have the situations:
* `X11` support is enabled.
* The `OpenGL` libraries (`MesaGL`) is not installed and support for `OpenGL` is disabled, no test tries to run `OpenGL` code)
* Still ctest fails noting that `MesaGL` is in the list of 'requirements'

How does my anologies fail/differ from the `xgboost` case?

**Comment by guitargeek** [comment] 2024-05-11 10:46
> From my limited view point it seems that we have:
> 
>     * python support is enabled
> 
>     * some optional component is not installed (and I am assuming that the related features are disabled and the actual tests related to those features are not run)
> 
>     * a test still complains that those optional component are not installed

You're correct, there is no reason for a test to complain about these optional components missing.
The test is gone now:
https://github.com/root-project/root/pull/15286

**Comment by guitargeek** [comment] 2024-05-11 10:47
Marked as fixed in "not applicable", because this only referred to the testing infrastructure which the users don't care about. Therefore, this should also not appear in the release notes.

**Closed by guitargeek** 2024-05-11 10:46 UTC
Labels: bug, affects:master, in:PyROOT
