### ISSUE TITLE
ROOT fails to build many builtins with CMake 3.30 (>=3.28) (when building in parallel (-j N))

### ISSUE THREAD

**Issue by andresailer** [root-project/root#16733] opened 2024-10-23 11:31 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

With newer versions of cmake like 3.30.5 at least some of ExternalProject_Add'ed builtins fail to compile with an  error like
```
gmake[6]: *** read jobs pipe: Bad file descriptor.  Stop.
gmake[6]: *** Waiting for unfinished jobs....
gmake[5]: *** [CMakeFiles/Makefile2:97: CMakeFiles/pcre.dir/all] Error 2
gmake[4]: *** [CMakeFiles/Makefile2:104: CMakeFiles/pcre.dir/rule] Error 2
gmake[3]: *** [Makefile:179: pcre] Error 2
```
(here builtin PCRE failed)

I don't know with which version of cmake this starts failing, but we (SPI/LCG) moved from 3.26.2 to 3.30.
Unless one limits oneself to a small number of `--jobs`?

### Reproducer

On lxplus or equivalent machines with CVMFS for example

```
export PATH=/cvmfs/sft.cern.ch/lcg/contrib/CMake/3.30.5/Linux-x86_64/bin/:$PATH
git clone https://github.com/root-project/root.git
cd root
mkdir build
cd build
cmake -D builtin_pcre=ON ..
make -j8
```

### ROOT version

any? (definitely HEAD)

### Installation method

build from source

### Operating system

Linux

**Comment by bellenot** [comment] 2024-10-23 13:27
Is it really a ROOT bug? Or a CMake one? 🤔

**Comment by bellenot** [comment] 2024-10-23 14:28
OK, so apparently it's only `builtin_pcre` which is causing problems (i.e. `pcre-8.43.tar.bz2`)

**Comment by bellenot** [comment] 2024-10-23 14:49
FYI there is the same error with `pcre 8.45` (which is the latest available). Investigating...

**Comment by bellenot** [comment] 2024-10-23 14:56
OK, I found a work-around. PR is coming soon. And note that the issue is not present on Windows

**Comment by andresailer** [comment] 2024-10-23 15:02
It probably depends on which builtins you enable?
I also see this for builtin_XROOTD
```
gmake[4]: *** read jobs pipe: Bad file descriptor.  Stop.
gmake[4]: *** Waiting for unfinished jobs....
gmake[3]: *** [Makefile:146: all] Error 2
```

**Comment by bellenot** [comment] 2024-10-23 15:06
Oh crap! I can't build XRootD... OK, thanks! I'll do the same with XRootD. Anything else?

**Comment by bellenot** [comment] 2024-10-23 15:08
Note that would be interesting to see if it's possible to build XRootD in parallel outside ROOT

**Comment by andresailer** [comment] 2024-10-23 15:09
I haven't found anything else so far. Do you have a cmake command to enable all builtins?

And yes we build xrootd outside of ROOT for the LCG stacks with cmake 3.30 without problems.
Heck I can build pcre outside of ROOT without problems as well.

**Comment by bellenot** [comment] 2024-10-23 15:11
> I haven't found anything else so far. Do you have a cmake command to enable all builtins?
I don't think so


> And yes we build xrootd outside of ROOT for the LCG stacks with cmake 3.30 without problems. Heck, I can build pcre outside of ROOT without problems as well.
OK, so I'll have to spend more time on this...

**Comment by andresailer** [comment] 2024-10-23 15:18
ccmake to the rescue...
TBB
```
gmake[5]: *** read jobs pipe: Bad file descriptor.  Stop.
gmake[5]: *** Waiting for unfinished jobs....
gmake[4]: *** [CMakeFiles/Makefile2:134: src/tbb/CMakeFiles/tbb.dir/all] Error 2
gmake[3]: *** [Makefile:156: all] Error 2
```
FFTW3
```
make[5]: *** read jobs pipe: Bad file descriptor.  Stop.
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [Makefile:708: all-recursive] Error 1
make[3]: *** [Makefile:552: all] Error 2
```

freetype (in the configure step??? :confused: )
```
make[3]: *** read jobs pipe: Bad file descriptor.  Stop.
make[3]: *** Waiting for unfinished jobs....
```

**Comment by bellenot** [comment] 2024-10-23 15:22
OK, thanks André! It looks like CMake is badly broken...

**Comment by bellenot** [comment] 2024-10-23 15:29
Looking there: https://www.kitware.com/cmake-3-28-0-rc5-is-ready-for-testing/
It seems adding `BUILD_JOB_SERVER_AWARE true` in `ExternalProject_Add` fixes the issue (at least for PCRE). Trying it right now (but xrootd fails for some reason...)

**Comment by bellenot** [comment] 2024-10-24 07:30
Adding `BUILD_JOB_SERVER_AWARE 1` partially fixes the issue, but adding it only for CMake version > 3.28 in something like 50 different places would be a pain in the neck...
see also https://gitlab.kitware.com/cmake/cmake/-/issues/26398

**Comment by bellenot** [comment] 2024-10-24 08:50
So interesting enough, adding `BUILD_JOB_SERVER_AWARE 1` fixes the issue for the ones failing at build time and adding `BUILD_JOB_SERVER_AWARE 0` fixes the issue for freetype (failing at configure step)

**Comment by bellenot** [comment] 2024-10-24 12:07
See also the discussion here: https://gitlab.kitware.com/cmake/cmake/-/issues/26398

**Comment by andresailer** [comment] 2024-10-24 12:37
Ubuntu24 comes with cmake version 3.28.3. (cf. #16654, #16682)

**Comment by bellenot** [comment] 2024-10-24 12:38
Thanks André!

**Comment by bellenot** [comment] 2024-10-24 13:36
So disabling the `LOG_CONFIGURE`, `LOG_BUILD`, `LOG_INSTALL` when using `CONFIGURE_COMMAND`, `BUILD_COMMNAD`, `INSTALL_COMMAND` (and so on) seems to fix the issue, but then we have no log...

**Comment by andresailer** [comment] 2024-12-06 12:13
CMake 3.30.6 was released and I have no more problems to build ROOT builtins

**Comment by bellenot** [comment] 2024-12-06 12:19
> CMake 3.30.6 was released and I have no more problems to build ROOT builtins

Cool! Thank you very much for the feedback André! Then I close this issue.

**Closed by bellenot** 2024-12-06 12:19 UTC
Labels: bug
