### ISSUE TITLE
Snapshot can't store event affected by missing "TBranch"  across different.

### ISSUE THREAD

**Issue by ShirinGolpayeganiCern** [root-project/root#9366] opened 2021-12-02 11:17 UTC
Dear all,

**Description :**
I have come across an issue in my analysis. I have been using **RDF** and **multithread** for my analysis.
I was **previously storing** the output of my analysis as **1D and 2D histograms root files**. 
I changed the method and started storing the results using snapshot.
**After storing the TTree/TChain** by using **snapshot** now, I have a separate script which creates the required plots.
Since I have converted to using the output of snapshot I have noticed, I have **lost significant number of events in the plots ** of some of the datasets.
I also noticed that the **same affected datasets**  **print out** the following errors:

Error in <TTreeReaderValueBase::CreateProxy()>: The tree does not have a branch called HLT_Trimuon2_Upsilon5_Muon. You could check with TTree::Print() for available branches.

The "missing TBranch" error is also repeated across the bugged datasets with different branches.

It is important to note that I **don't even use any of those "missing TBranches" in my analysis** nor am trying to plot them.
When I use the **report**, the **output shows that all events have been reached and all the filters are applied correctly**, 

**What seems to have correct behaviour**:
1. Reading events TTree/TChain.
2. Running across the script since the previous version which is stored as plots directly look fine even though those files has missing TBranches too, have used multithread and RDF.
3. Report function, the output of the script stored as plots and the snapshot are same (as far as I recall).

**Suspected bug:**
Could it be If there is a missing TBranch across some files, The snapshot can't handle the TTree/TChain and those events are not stored (i.e. rejected from the storage)?

Could anyone please help me with this issue and clarify of the behaviour of snapshot in case of inconsistent branches?

**Expected behaviour:**
1.Snapshot will be able to at least store other branches and not be affected by missing tbranches.
2.Snapshot to print that there is a branch which could not be fully stored or stored at all with mentioning which branch it is and the reason of failure (i.e. missing branch in x,y,z, files).
3.Is it possible to develop a method for snapshot to store only the required branches and not all. It can help with saving plenty of space on the servers.

Thank you in advance for looking into this issue and sorry about the wordy description.

Github links:
**RDF opening the TTree datasets**: https://github.com/brunel-physics/Shirin-Codes/blob/b6539523aeda1dee0445e81d0377b19589b468ed/src/TTreeMaker.cxx#L1464
**RDF opening the TChain datasets**:https://github.com/brunel-physics/Shirin-Codes/blob/b6539523aeda1dee0445e81d0377b19589b468ed/src/TTreeMaker.cxx#L1486
**Snapshot**:https://github.com/brunel-physics/Shirin-Codes/blob/b6539523aeda1dee0445e81d0377b19589b468ed/src/TTreeMaker.cxx#L1753 ,
https://github.com/brunel-physics/Shirin-Codes/blob/b6539523aeda1dee0445e81d0377b19589b468ed/src/TTreeMaker.cxx#L2249

**Comment by eguiraud** [comment] 2021-12-02 11:52
As a first quick reply: if there are errors like those you mention printed on screen during the processing, indeed you can expect the output to not be all ok.

In particular RDataFrame does not deal well with disappearing/reappearing branches. The TTree schema is expected to be constant across the whole dataset being processed. I am not 100% what the effect will be in this case, it also depends on how TTreeReader, TChain and TTree (which RDataFrame uses internally for I/O) react in these cases.

With that said RDataFrame should do its best to diagnose this and throw an exception rather than continuing the processing until the end. Please provide a recipe to reproduce the problem (e.g. dataset + minimal code) so we can debug further.

**Comment by eguiraud** [comment] 2022-01-05 11:53
Hi @ShirinGolpayeganiCern , can you please provide a minimal reproducer for the issue?

**Comment by ShirinGolpayeganiCern** [comment] 2022-01-05 11:59
> Hi @ShirinGolpayeganiCern , can you please provide a minimal reproducer for the issue?

Hi again and happy holidays,

I unfortunately have never used root to create ttrees, i only use the provided data for analysis.
One easy way to reproduce this error, is to use tchain to read from various events and ttrees of root files, and the importance is that some contain some branches while others dont.
And then take snapshot from the whole thing.
I now know for sure it is a bug, because as soon as i saved some columns only , the error disappeared and the results were back to normal

**Comment by eguiraud** [comment] 2022-01-05 12:11
Hi,
as I mentioned above RDataFrame does not support disappearing/reappearing branches, so I don't doubt that the behavior in this case is broken/incorrect/surprising.

I would like to improve the diagnostics for your case (your point number 2.), but for that I would need a reproducer. Otherwise this falls under the umbrella of #8704 .

Regarding points 1. and 3., that should already be the case: if you don't read or write the branches that disappear/reappear, there should be no problem -- and it's possible to do so by passing the list of columns to write explicitly to Snapshot.

**Comment by ShirinGolpayeganiCern** [comment] 2022-01-05 12:17
Hey again,

I think it is a big problem, because I and some colleagues are using the snapshot method to save the root files so later one we will plot from them, however, if many events are not recorded accordingly, our root files are also be wring, this issue costed me a few months and many people don't even recognize they are missing events since they have not used alternative methods to save and plot.
Many people wont be using the column list to save all the columns because we save many columns,
And it is appreciated if there is an error stating the consequences at least.
I have told you the name of the datasets I have used earlier and the problematic ones, however, as I said, I have never used root to create data. I honestly thought that creating some .txt or .csv file to be saved as nto root files

**Comment by ShirinGolpayeganiCern** [comment] 2022-01-05 12:18
To be saved as root files and later read again as rdf and saved as snapshot shouldnt be so time taking for a root programmer.
I really want to help but I don't know how, since you don't have access to the data I have used.

**Comment by eguiraud** [comment] 2022-01-06 09:49
Hi @ShirinGolpayeganiCern ,
RDataFrame should print errors and also exit with an error status for the case you describe, is that not the case for you?

I tried to reproduce the problem but I get a noisy error:

```cpp
#include <ROOT/RDataFrame.hxx>

int main() {
  {
    ROOT::RDataFrame(10)
        .Define("x", [] { return 1; })
        .Define("y", [] { return 1; })
        .Snapshot("t", "f1.root");

    ROOT::RDataFrame(10).Define("x", [] { return 1; }).Snapshot("t", "f2.root");

    ROOT::RDataFrame(10)
        .Define("x", [] { return 1; })
        .Define("y", [] { return 1; })
        .Snapshot("t", "f3.root");
  }

  ROOT::EnableImplicitMT();
  ROOT::RDataFrame df("t", {"f1.root", "f2.root", "f3.root"});
  df.Snapshot("t", "fmerged.root");
}
```

yields:

```
~/S/w/gh9366 rootcompile repro.cpp && ./repro
g++ -g -Wall -Wextra -Wpedantic -o "repro" "repro.cpp" $(root-config --cflags --libs)
Error in <TTreeReaderValueBase::CreateProxy()>: The tree does not have a branch called y. You could check with TTree::Print() for available branches.
terminate called after throwing an instance of 'std::runtime_error'
  what():  An error was encountered while processing the data. TTreeReader status code is: 6
fish: Job 1, './repro' terminated by signal SIGABRT (Abort)
```

As RDataFrame does not support processing disappearing/appearing branches (in Snapshots or any other method) everything seems to be working as expected here.

I'd like to figure out why your colleagues don't see these error messages and the exception being thrown, but I would need help on your side to reproduce the issue.

Cheers,
Enrico

**Comment by ShirinGolpayeganiCern** [comment] 2022-01-06 09:53
Hi,

I got the error message that TBranch is missing, but it never threw an exception handling, in fact in my case, i even had a cout at the end of the scripts which stated the script has ran fine and I always got that. Meaning, the run was never terminated due to the error....
I really want to help, but i dont know how, i sent the github link of my script, also the data I have used, but you dont have access to them, so pls tell me how can I help you exactly?

Regards,

Shirin

**Comment by eguiraud** [comment] 2022-01-06 10:02
Ok, no exception but the problem is still diagnosed and reported, that's something.

If that was with a ROOT version prior to v6.24, can you please try with v6.24? Handling of errors during the event loop was improved in recent versions.

If you don't get an exception with v6.24 can you share the datasets (or the part of the datasets required to reproduce the problem) with me (also privately is fine)?

In any case besides this quirk of the exception not being thrown (which I hope is just due to an older ROOT version), things seem to work as intended. As I mentioned, we do want to support disappearing/reappearing branches in the future by letting users specify a default value that the column should take when the branch is not present. This is feature request https://github.com/root-project/root/issues/8704 .

**Comment by eguiraud** [comment] 2022-01-06 10:29
Ah no, my bad sorry, the exception-throwing-on-error is not even in 6.24, it's only in the development branch (and soon will be in v6.26). So what you see is expected (but starting from the next ROOT version you'll also get an exception and a non-zero exit code).

**Comment by ShirinGolpayeganiCern** [comment] 2022-01-06 10:34
So I guess this issue is solved in next version then 🙈

**Comment by eguiraud** [comment] 2022-01-06 10:41
In the next version (v6.26, being released in a few weeks) an exception is thrown on top of the error message that is currently printed.

Then in a future version users will be able to tell RDF what default values to use for disappearing/reappearing branches, which gives users a way to deal with this case more nicely.

For now, I am afraid the best workaround is to not read or write such branches from RDF (if you only read/write well-behaved branches everything works), either by fixing the trees themselves or by only Snapshotting a subset of the columns.

I'm closing this in favor of #8704 .

**Closed** 2022-01-06 10:41 UTC
Labels: bug, in:RDataFrame

**Comment by ShirinGolpayeganiCern** [comment] 2022-01-06 10:46
Hi again,

I have only used a subset for now, I will tell other colleagues too,
Thanks for the nice error handling, hopefully no one is gonna have similar experience regarding this matter in future.
Thanks for the hard work again,

Best regards

Shirin
