### ISSUE TITLE
Draw TCanvas on Macos 14.5

### ISSUE THREAD

**Issue by Josiah1** [root-project/root#15517] opened 2024-05-15 10:01 UTC
### Check duplicate issues.

- [x] Checked for duplicates

### Description

After I upgraded my M1 pro MacBook (2021) to MacOS 14.5 last night, I found there are many error printings every time I open the ROOT prompt or execute a program with ROOT libraries linked. Then I tried to update the ROOT to the master version last night and rebuild it. Now I found every time I create a TCanvas in the ROOT program, it prints the errors:

```
  ------------------------------------------------------------------
  | Welcome to ROOT 6.33/01                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on May 15 2024, 03:36:37                   |
  | From heads/master@v6-31-01-1952-gfb9ba02037                      |
  | With Apple clang version 15.0.0 (clang-1500.3.9.4)               |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] TCanvas *tc1 = new TCanvas()
Error in <TGHScrollBar::TGHScrollBar>: arrow_*.xpm not found
Error in <TGVScrollBar::TGVScrollBar>: arrow_*.xpm not found

 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[/Users/josiahlee/WORK/Tools/root_install_master/lib/libGui.so] TGCanvas::Layout() (no debug info)
[/Users/josiahlee/WORK/Tools/root_install_master/lib/libGui.so] TGCanvas::Layout() (no debug info) 
```

### Reproducer

1. Open root prompt on MacOS 14.5
2. type "TCanvas *tc=new TCanvas();"

### ROOT version

heads/master@v6-31-01-1952-gfb9ba02037

### Installation method

build from source

### Operating system

MacOS

**Comment by couet** [comment] 2024-05-15 15:32
The xpm file should be in `$ROOTSYS/icons` . can you check ??

**Comment by Josiah1** [comment] 2024-05-15 15:35
> The xpm file should be in `$ROOTSYS/icons` . can you check ??

Hello, here is the result:

<img width="985" alt="image" src="https://github.com/root-project/root/assets/17957968/b621505c-2a9d-46b1-93b3-f6027e535bce">

**Comment by couet** [comment] 2024-05-15 15:42
Weird, it seems ok.
I do not see this problem on my mac:
```
% root --web=off
   ------------------------------------------------------------------
  | Welcome to ROOT 6.33/01                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosx64 on May 02 2024, 08:25:19                      |
  | From heads/save-C-fix@v6-31-01-1828-g0d282dd4a6                  |
  | With Apple clang version 15.0.0 (clang-1500.3.9.4)               |
  | Try .help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] TBrowser b
(TBrowser &) Name: Browser Title: ROOT Object Browser
root [1] 
```
and the icon folder is the same as yours:
```
% cd $ROOTSYS/icons
couet@oliviers-mbp icons % ls arrow_*.xpm
arrow_down.xpm		arrow_right.xpm		arrow_up.xpm
arrow_left.xpm		arrow_right2.xpm
```
As TBrowser is a GUI class, may be @bellenot might have some idea about these missing icons

**Comment by ferdymercury** [comment] 2024-05-15 15:48
Maybe related: https://github.com/root-project/root/issues/14247

Maybe removing the systemwide libAfterimage packages helps?

**Comment by bellenot** [comment] 2024-05-16 07:35
I cannot try on MacOS, and I have no idea what could be the issue, but as @ferdymercury said, can you try to remove the system libAfterimage, if any?

**Comment by dpiparo** [comment] 2024-05-20 09:48
Hi,

I also cannot reproduce. I am closing the issue. Please feel free to re-open in case the problem surfaces again and is reproducible.

**Closed by dpiparo** 2024-05-20 09:48 UTC
Labels: bug
