### ISSUE TITLE
cannot buid the dependent project

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#8942] opened 2021-09-01 08:13 UTC
- [ ] Checked for duplicates

I have my own project that uses ROOT (and Python)
my CMakeList file contains following ilnes 
```
find_package(ROOT 6 CONFIG REQUIRED )
...
find_package(Python3 ${PY3VERSION_ROOT} COMPONENTS Interpreter Development NumPy)

```
And it build, works, and everything is fine 

To follow up development in ROOT, I regularly rebuild my project using ROOT version from LCG nighlies dev3 build.  And starting from Tuesday, August 31 I have a build error - numpy i snot found

```
-- Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found suitable version "3.9.6", minimum required is "3.9.6")
```

As a result all binaries/libraries in my project are invalid and result in segfaults. 

It is not clear if this is ROOT,CMAKE or LCG-nighlies problem

 

### Describe the bug

for ROOT-based project 
cmake does not find NumPy   for dev3 LCG nighlies built Staring form August 31, 2021 

### Expected behavior

cmake should find NumPy 

### To Reproduce

1. lxplus.cern.ch 
2. source /cvmfs/sft.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-opt/setup.sh
3. any CMAKe project with these two ilnes included 
```
find_package(ROOT 6 CONFIG REQUIRED )
...
find_package(Python3 3.6.9  COMPONENTS Interpreter Development NumPy)
```

**Comment by etejedor** [comment] 2021-09-07 10:46
I don't see any change around that date in ROOT's CMake files which could be the cause of this problem. I will have a look and let you know.

**Comment by etejedor** [comment] 2021-09-07 12:53
@VanyaBelyaev I can't reproduce with latest dev3, does it still fail for you?

I use this `CMakeLists.txt` on lxplus, after sourcing latest dev3:

```
cmake_minimum_required(VERSION 3.16)

project(TestProject)

find_package(ROOT 6 CONFIG REQUIRED )
find_package(Python3 3.6.9  COMPONENTS Interpreter Development NumPy)
```

and the output I get for Python3 is:

```
-- Found Python3: /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-opt/bin/python3.9 (found suitable version "3.9.6", minimum required is "3.6.9") found components: Interpreter Development NumPy Development.Module Development.Embed 
```

There was maybe some temporary problem with the NumPy installation in dev3?

**Comment by dpiparo** [comment] 2024-02-03 12:19
I am closing the issue since @etejedor himself could not reproduce. Please do not hesitate to re-open if more information becomes available.

**Closed by dpiparo** 2024-02-03 12:19 UTC
Labels: bug
