### ISSUE TITLE
[ci] Add a workflow that builds cling standalone and runs its tests

### ISSUE THREAD

**Issue by vgvassilev** [root-project/root#14972] opened 2024-03-14 15:54 UTC
### Explain what you would like to see improved and how.

ROOT cannot run cling's testsuite because it compiles llvm with `-fvisibility=hidden` which the cling tests cannot work with. However, in many cases when we commit code to cling (and more importantly during llvm upgrades) these tests provide minimal reproducers for common issues.

Note that the CI should run only if there are changes to `root-src/interpreter/`.

### ROOT version

N/A

### Installation method

N/A

### Operating system

N/A

**Comment by dpiparo** [comment] 2024-03-14 17:43
@vgvassilev great idea. I think triggering the tests only if something in that dir changes is perfectly possible. Do you have some starting point which can be taken as  example to build a GH workflow to run on the ROOT infra?

**Comment by vgvassilev** [comment] 2024-03-14 19:05
Should be something as simple as:

```
git clone our/llvm/fork
git clone cling
git checkout cling-latest
cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD="host;nvptx" -DLLVM_EXTERNAL_PROJECTS="cling" -DLLVM_EXTERNAL_CLING_SOURCE_DIR=/path/to/where/we/cloned/cling ../llvm
make check-cling
```

**Comment by ferdymercury** [comment] 2024-03-21 11:45
This is maybe a duplicate of https://github.com/root-project/root/issues/6957

**Comment by dpiparo** [comment] 2024-03-24 06:54
it is. Thanks @ferdymercury

**Closed by dpiparo** 2024-03-24 06:54 UTC
Labels: improvement
