### ISSUE TITLE
The '404' error pages contains a link to ... another 404 page :) 

### ISSUE THREAD

**Issue by pcanal** [root-project/root#17316] opened 2024-12-19 16:02 UTC
If you enter a bad link (intentionally or not :) ) like [https://root.cern/badlink/](https://root.cern/badlink/), you get a nice page explaining the page was not found and then offers to go to the "[get started](https://root.cern/get_started) section" but this is a bad link itself `https://root.cern/get_started`

**Comment by couet** [comment] 2024-12-19 16:16
This is due to this change: https://github.com/root-project/web/commit/e36dbff3b277d4fd346bf53a2c3fd27b02da73b3 in which @martamaja10 replace the `get_started` page by `learn`. The 404 page was changed accordingly but some unknown reason the old version with `get_started` is still used on the online build. When building the web-site locally the right page (with "learn") is shown.  An extra commit was done afterwards https://github.com/root-project/web/commit/7f8f484c8dcfa1e36d3e77d31d658d0a8a36b47b to force the build of the new 404.md version but it did not help.

**Comment by ferdymercury** [comment] 2024-12-19 16:25
Duplicate of https://github.com/root-project/web/issues/1027

**Closed by ferdymercury** 2024-12-19 16:25 UTC
Labels: bug
