### ISSUE TITLE
Can't compile RModelParser_Keras

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#13102] opened 2023-06-26 19:25 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When compiling ROOT from source, I got an error:

```
/opt/root/src/tmva/pymva/src/RModelParser_Keras.cxx: In function ‘std::unique_ptr<TMVA::Experimental::SOFIE::ROperator> TMVA::Experimental::SOFIE::PyKeras::INTERNAL::MakeKerasSwish(PyObject*)’:
/opt/root/src/tmva/pymva/src/RModelParser_Keras.cxx:562:23: error: ‘ROperator_Swish’ does not name a type; did you mean ‘ROperator_Slice’?
  562 |          op.reset(new ROperator_Swish<float>(fLayerInputName, fLayerOutputName));
      |                       ^~~~~~~~~~~~~~~
      |                       ROperator_Slice
/opt/root/src/tmva/pymva/src/RModelParser_Keras.cxx:562:39: error: expected primary-expression before ‘float’
  562 |          op.reset(new ROperator_Swish<float>(fLayerInputName, fLayerOutputName));
      |                                       ^~~~~
make[2]: *** [tmva/pymva/CMakeFiles/PyMVA.dir/build.make:146: tmva/pymva/CMakeFiles/PyMVA.dir/src/RModelParser_Keras.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:42937: tmva/pymva/CMakeFiles/PyMVA.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:44293: roofit/xroofit/CMakeFiles/RooFitXRooFit.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

Had to add a line

+++ b/tmva/pymva/src/RModelParser_Keras.cxx
@@ -18,6 +18,7 @@
  **********************************************************************************/
 
 #include "TMVA/RModelParser_Keras.h"
+#include "TMVA/ROperator_Swish.hxx"

I'm not sure the include had to be added in that file, but it worked.

### Reproducer

Clone ROOT repository, go to the build directory,

    cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_INSTALL_PREFIX=../install ../src
    cmake --build . -- install -j4

### ROOT version

Most recent ROOT version from the master branch at that time.

    commit https://github.com/root-project/root/commit/870618f1bfa43376c73bc07fa4becc0a54caa9ed (HEAD -> master, origin/master, origin/HEAD)

### Installation method

built from source

### Operating system

Arch Linux

**Comment by guitargeek** [comment] 2023-06-26 22:38
Duplicate of https://github.com/root-project/root/issues/13101.

**Closed by guitargeek** 2023-06-26 22:38 UTC
Labels: bug
