### ISSUE TITLE
TRandom: signature mismatch between getter and setter

### ISSUE THREAD

**Issue by alexrollings** [root-project/root#6624] opened 2020-10-13 08:26 UTC
In order to test the stability of a model in RooFit, I need to generate independent pseudo-datasets and fit the model back to them. I use the TRandom class to make sure that the system starts in a different state each time in the following way:

RooRandom::randomGenerator()->SetSeed(0);

I need to be able to reproduce these fits, so I save the seed associated with each pseudo-dataset:

UInt_t my_seed =  RooRandom::randomGenerator()->GetSeed();

However, if I then set the seed to the number that GetSeed() returns and and re-run the fit:

RooRandom::randomGenerator()->SetSeed(my_seed);

The same state is not reproduced.

I have checked the documentation, and SetSeed accepts the type ULong_T as an argument, where as GetSeed returns the type UInt_t. There is therefore no way for me to extract the actual seed the RooRandom object is using to generate the pseudo-datasets as the number is truncated.

**Comment by hageboeck** [comment] 2020-10-13 10:04
A valid point. The problem is not in RooFit, since RooFit directly uses the TRandom interface.

@lmoneta, do you think this can be fixed?

**Comment by lmoneta** [comment] 2020-10-13 10:16
Hi, 
This is a known problem since when you use TRandom3, you need to retrieve the full state of ~600 values. 
The solution is to save the Random generator instance (TRandom3) and use that one in a file to reproduce your fits

Lorenzo

**Comment by lmoneta** [comment] 2020-10-27 09:40
Duplicate of https://sft.its.cern.ch/jira/browse/ROOT-10059 and also https://sft.its.cern.ch/jira/browse/ROOT-10081
and the solution is not to use GetSeed but the class copy constructor. 
Things to do is document better `TRandom::GetSeed`

**Closed** 2020-11-23 14:27 UTC
Labels: affects:master, bug, in:Math Libraries
