### ISSUE TITLE
[ROOT 6.29] module 'std.bits/uses_allocator_args.h' requires feature 'cplusplus20'

### ISSUE THREAD

**Issue by iarspider** [root-project/root#12240] opened 2023-02-07 10:05 UTC
- [x] Checked for duplicates

### Describe the bug
When building CMS offline software stack with the ROOT commit 6f02c75fea, we get the following errors:
```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/lcg/root/6.29.01-8b1fb99c2f98c5fc80c3d3abd70c9452/etc/cling/std.modulemap:497:10: error: module 'std.bits/uses_allocator_args.h' requires feature 'cplusplus20'
  module "bits/uses_allocator_args.h" {
         ^
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/external/gcc/11.2.1-f9b9dfdd886f71cd63f5538223d8f161/include/c++/11.2.1/memory_resource:42:10: note: submodule of top-level module 'std' implicitly imported here
#include    // uninitialized_construct_using_alloc
         ^
```

```
python3: /(...)/lcg/root/6.29.01-8b1fb99c2f98c5fc80c3d3abd70c9452/root-6.29.01/interpreter/llvm/src/tools/clang/lib/AST/DeclCXX.cpp:1499: clang::NamedDecl* getLambdaCallOperatorHelper(const clang::CXXRecordDecl&): Assertion `!Calls.empty() && "Missing lambda call operator!"' failed.
 *** Break *** abort
```

We have previously tested ROOT commit 0bd51969ce, and did not get these errors.

### Expected behavior
No build errors

### Setup
ROOT 6.29.01 / 6f02c75fea on AlmaLinux 8, built from source (gcc 11.2)

**Comment by davidlange6** [comment] 2023-02-07 10:28
https://github.com/root-project/root/pull/11874 
(I had seen this same error last week in cmssw while just picking up the stl.modulemap changes - I had assumed the rest of the PR would avoid this error, but seems not)

**Comment by iarspider** [comment] 2023-02-07 10:31
@vgvassilev

**Comment by iarspider** [comment] 2023-02-14 13:55
After updating ROOT to 026a1a701b, the first error is gone. But dictionary generation still fails due to "Missing lambda call operator".

**Comment by iarspider** [comment] 2023-02-14 17:17
@Axel-Naumann gentle ping

**Comment by vgvassilev** [comment] 2023-02-15 13:19
@iarspider, can you check if that helps: https://github.com/root-project/root/pull/12276

**Comment by iarspider** [comment] 2023-02-15 21:30
@vgvassilev No, we still get the same errors. New build log: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2c2cf9/30647/build.log).

> For local testing, you can use /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmsdist/8312/30647/install.sh to create a dev area with all the needed externals and cmssw changes.

**Comment by Nowakus** [comment] 2023-02-16 12:19
Let me add ATLAS reproducer based on the LCG dev3 Athena build:

% source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/AtlasSetup/current/AtlasSetup/scripts/asetup.sh master--dev3LCG,latest,Athena 
% root
root [0] new xAOD::IParticle();
/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Tue/ROOT/HEAD/x86_64-centos7-gcc11-opt/etc/cling/std.modulemap:497:10: error: module 'std.bits/uses_allocator_args.h' requires feature 'cplusplus20'
 *** Break *** segmentation violation

Marcin

**Comment by aandvalenzuela** [comment] 2023-02-16 14:37
Hello @vgvassilev! We were wrong, it seems the patch worked now (See logs at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2c2cf9/30658/). Thanks!!

**Comment by aandvalenzuela** [comment] 2023-02-16 15:06
Hi @vgvassilev! We were wrong, the patch works. Thanks for the fix! :)
(I commented before, but I cannot see the comment anymore...)

**Comment by vgvassilev** [comment] 2023-02-16 16:26
> Hi @vgvassilev! We were wrong, the patch works. Thanks for the fix! :) (I commented before, but I cannot see the comment anymore...)

Oh, great - I was wondering what was wrong... I will revert my recent changes to the PR and merge it in...

**Comment by iarspider** [comment] 2023-02-16 16:28
@vgvassilev just to clarify things: [this](f945434a97c345a7a26ba5cc55db836441c53ed1) did not work, but after you (and we) [updated](f945434a97c345a7a26ba5cc55db836441c53ed1) the patch, it worked.

**Comment by davidlange6** [comment] 2023-02-16 16:32
https://github.com/cms-sw/cmsdist/pull/8312/commits/3722765fb237aa25f434bbfa98bb2be358f1e917

**Comment by davidlange6** [comment] 2023-02-16 16:33
is what fixed it (not obvious to me how @iarspider  picked up the commit before it seems to have gotten to this pr, but ok.. maybe someones clock is wrong?

**Comment by vgvassilev** [comment] 2023-02-17 09:13
@iarspider, can check if the issue is gone with ROOT's master now?

**Comment by aandvalenzuela** [comment] 2023-02-17 09:34
Testing at https://github.com/cms-sw/cmsdist/pull/8320

**Comment by aandvalenzuela** [comment] 2023-02-17 18:06
Tests just finished successfully. Thanks!

**Comment by vgvassilev** [comment] 2023-02-17 19:36
Sounds great. I assume the lcg builds are fixed too. Let’s close this issue now. Feel free to reopen if necessary.

**Comment by Axel-Naumann** [comment] 2023-02-27 12:26
@vgvassilev could you backport this into v6-28-00-patches, please?

**Comment by Nowakus** [comment] 2023-05-03 08:20
Hi @vgvassilev ,   
This problem crept back into both dev3 (since Mon build) and dev4 LCG nightlies. So it's both ROOT master and 6.28-patches. It can be reproduced the same way as I reported before:

% source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/AtlasSetup/current/AtlasSetup/scripts/asetup.sh master--dev3LCG,latest,Athena
% root
root [0] new xAOD::IParticle();
/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev3/Tue/ROOT/HEAD/x86_64-centos7-gcc11-opt/etc/cling/std.modulemap:554:10: error: module 'std.bits/uses_allocator_args.h' requires feature 'cplusplus20'
  module "bits/uses_allocator_args.h" [optional] {
         ^
/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos7/include/c++/11.3.0/memory_resource:42:10: note: submodule of top-level module 'std' implicitly imported here
#include <bits/uses_allocator_args.h>   // uninitialized_construct_using_alloc

*** Break *** segmentation violation

**Comment by vgvassilev** [comment] 2023-05-03 09:53
@Nowakus thanks for the report: I am trying a fix here: https://github.com/root-project/root/pull/12752

**Comment by Axel-Naumann** [comment] 2023-05-03 19:37
C++20 is taking a toll on us... Thanks for the fix, @vgvassilev - merged into master an v6-28-00-patches. @Nowakus could you confirm that the next nightlies look good, so I can tag v6.28/04 tomorrow?

**Comment by Axel-Naumann** [comment] 2023-05-05 13:11
Confirmed fixed, thanks, @Nowakus @elmsheus

**Closed** 2023-05-05 13:12 UTC
Labels: bug, priority:critical, experiment
