### ISSUE TITLE
[PyROOT] Conversion from `std::string` to `std::string_view` broken in 6.32

### ISSUE THREAD

**Issue by arizzi** [root-project/root#16298] opened 2024-08-23 08:01 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

The following code crashes in ROOT >= 6.32, it was ok in ROOT 6.30

```python
import ROOT

inputfile = ROOT.TFile.Open("root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/Run2012BC_DoubleMuParked_Muons.root")
inputtree=inputfile.Get("Events")
tmprdf = ROOT.RDataFrame(inputtree)
cols=tmprdf.GetColumnNames()

#THIS CRASHES
for col in cols:
    print(col)
    print( tmprdf.GetColumnType(col) )

# THIS WORKS:
#print(cols[0])
#print(tmprdf.GetColumnType(cols[0]))
```

### Reproducer

ssh lxplus
python3 ~arizzi/public/repro.py

### ROOT version

 ROOT 6.32.02 
lxplus default install

### Installation method

lxplus

### Operating system

lxplus

**Comment by guitargeek** [comment] 2024-08-23 08:50
This is the manifestation of a known problem with the `std::string_view` converters, that can be reproduced without RDataFrame:
```Python
import ROOT
import cppyy

cppyy.cppdef("""
    void foo(std::string_view input) { std::cout << input << std::endl; }
""")

my_string = cppyy.gbl.std.string("test")

cppyy.gbl.foo(my_string)
```
You'll see that the output in ROOT 6.32 is empty, meaning the `string_view` is not correctly initialized. This causes the RDF code to crash.

This problem was already fixed in upstream cppyy, and we have a PR open to apply these fixes:
https://github.com/root-project/root/pull/16212

However, the fix is breaking some other tests, so we can't apply them yet. Thanks for the report though, because this makes it clearer how #16212 needs to be prioritized.

In the meantime, the workaround is to convert your `std::strings` into Python strings, because the conversion to `std::string_view` works for them:
```python
for col in cols:
    print(col)
    print( tmprdf.GetColumnType(str(col) ))
```
This workaround is also backwards compatible.

**Comment by arizzi** [comment] 2024-08-23 11:43
@guitargeek thanks for the workaround, I've implemented it in our code

**Closed** 2024-08-27 23:27 UTC
Labels: bug, priority:high, in:PyROOT
