### ISSUE TITLE
wrong Python version found during build

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#12744] opened 2023-05-01 09:01 UTC
### Explain what you would like to see improved

I've compiled ROOT from this repository, but then it failed to launch with Python 3. Upon further investigation, I found lines

> _Python3_INTERPRETER_PROPERTIES:INTERNAL=Python;3;11;2;64;;cpython-311-x86_64-linux-gnu;abi3;/usr/lib/python3.11;/usr/lib/python3.11;/usr/lib/python3.11/site-packages;/usr/lib/python3.11/site-packages
> _Python3_LIBRARY_RELEASE:INTERNAL=/usr/lib/libpython3.11.so

in *CMakeCache.txt*.

However, my main Python version is 3.10.

    $ python -V
    Python 3.10.10
    $ls -l /usr/bin/python
    lrwxrwxrwx 1 root root 7 Mar  5 23:26 /usr/bin/python -> python3
    $ls -l /usr/bin/python3
    lrwxrwxrwx 1 root root 10 Mar  5 23:26 /usr/bin/python3 -> python3.10

that's why I get a crash,

```
python -c 'import ROOT'
Traceback (most recent call last):
  File "/opt/root/install/lib/cppyy/__init__.py", line 60, in <module>
    importlib.import_module(libcppyy_mod_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'libcppyy3_10'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/root/install/lib/ROOT/__init__.py", line 25, in <module>
    import cppyy
  File "/opt/root/install/lib/cppyy/__init__.py", line 62, in <module>
    raise ImportError(
ImportError: Failed to import libcppyy3_10. Please check that ROOT has been built for Python 3.10
```

### Optional: share how it could be improved

Can Python 3 version be found checking symlinks of `/usr/bin/python`, and not its highest version available?
I also use Python 2, hope it won't break its search.

### To Reproduce

1. Install Python version newer than the system one.
2. Build root.
3. Import Python ROOT (it will fail).

### Setup

1. ROOT version: ROOT Version: 6.29/01, From heads/master@v6-29-01-1273-g360c0c7c54.
2. Operating system: Arch Linux, Built for linuxx8664gcc.
3. Build myself from this repo.

### Additional context
I create software packages, that's why I use several Python versions (to provide better experience to users with different tools). It would not be very convenient to remove some python version in order to build ROOT.

I have no idea where this search is being performed. Yesterday I left a comment on an old issue, but can't find it. On another system of mine it is also written that "Python 3 not found", and then it is built fine.

**Comment by Axel-Naumann** [comment] 2023-05-03 07:47
We use `find_package(Python3 COMPONENTS Interpreter Development NumPy)` from CMake. Can you reproduce this behavior in a stand-alone cmake reproducer? I doubt there's much we can do on ROOT's side - except for helping you open a bug report with CMake :-)

**Comment by ynikitenko** [comment] 2023-05-03 12:41
Thanks for the clarification, Axel. I've submitted a [feature request](https://gitlab.kitware.com/cmake/cmake/-/issues/24878) to CMake (this is the default behaviour, so I don't think we have to reproduce that).

Meanwhile I can see that CMake allows choosing the Python interpreter via several flags (from this [SO answer](https://stackoverflow.com/a/73051915/952234)):

> -DPython3_ROOT_DIR="your_python3.9_install_dir"

Unfortunately, I don't know what dir should be provided for the interpreters themselves, because they seem to be located only in */usr/bin*. Maybe ROOT could add documentation how to deal with that?

**Comment by ynikitenko** [comment] 2023-05-03 14:40
Of course, I could try this variables myself, but I'm not sure how ROOT CMake script treats them. I don't develop anything with CMake, unfortunately.

**Comment by ynikitenko** [comment] 2023-05-06 09:45
I've got a funny continuation of this thread: Arch Linux has updated the default Python version to be 3.11, so now I can use ROOT with the "default" python and don't have to recompile anything.
However, I still think that to choose the Python version would be a good option.

**Comment by bellenot** [comment] 2023-05-16 07:56
Since it's a CMake issue and not really a ROOT one, I guess we can close this?

**Comment by ynikitenko** [comment] 2023-05-16 11:04
No, I think since you can change your CMakefile, I would leave it as a
feature request.

Bertrand Bellenot ***@***.***> schrieb am Di., 16. Mai 2023,
09:56:

**Comment by ynikitenko** [comment] 2023-05-16 14:48
Thank you very much! I'm sure there must be a way to do that. However, I think this must be a rather rare demand, so this should be some second-order feature...
But it may also be that it is already possible through command line/environment arguments - maybe someone who knows CMake could guide how to do that.

**Comment by guitargeek** [comment] 2024-04-03 18:44
The problem should be fixed with this PR:
https://github.com/root-project/root/pull/14703

The version Python that ROOT was compiled with is now not hardcoded in the library names anymore, so using ROOT with newer Python that the one a build time is totally possible!

@ynikitenko, feel free to open a new issue should you have similar problems.

**Closed by guitargeek** 2024-04-03 18:44 UTC
Labels: improvement, in:Build System, in:PyROOT

**Comment by ynikitenko** [comment] 2024-04-03 19:15
Thank you!
However, I've heard that new ROOT drops support for Python 2.
So I'm not sure whether this is the way I wanted. But still it is good to
compile ROOT with several Python versions, so thanks again for that update.

Jonas Rembser ***@***.***> schrieb am Mi., 3. Apr. 2024,
20:45:
