### ISSUE TITLE
Printing values in if-stmt

### ISSUE THREAD

**Issue by vgvassilev** [root-project/root#6644] opened 2020-10-14 21:06 UTC
```
root.exe -l
root [0] if (TFile::Open("tutorials/hsimple.root")) ntuple->GetTitle()
root [1] 
```

Whereas it should have printed:

```
root.exe -l
root [0] if (TFile::Open("tutorials/hsimple.root")) ntuple->GetTitle()
root [1] ntuple->GetTitle()
(const char *) "Demo ntuple"
root [2] 
```

**Comment by Axel-Naumann** [comment] 2020-10-21 09:36
I'd claim that this is not a bug, just maybe surprising behavior that can be addressed by thinking ;-) `if` is control flow, it doesn't have an expression type, so there's nothing to be printed. If we were to "fix" this, why would we not also "fix"
```
while (true) 1
```
which currently (I claim correctly) prints nothing, but to be consistent with the `if` "bug" above should print lots and lots of `1`s?

**Comment by vgvassilev** [comment] 2020-10-21 09:47
I'd be in favor of actually making `while (true) 1` print.

**Comment by Axel-Naumann** [comment] 2020-10-21 10:02
OK, what about
```
do 1 while (true)`
```
? I.e. where do we stop? (Note that this isn't parsable, and appending a trailing ';' doesn't help.)

For me, an inner block (even if the '{}' are omitted) is not considered by the value printer; changing that is likely not work it and will create many more inconsistencies than is warranted by "repairing" the seemingly inconsistent behavior of this ticket. To be more precise, why isn't
```
if (true) { 1 }
```
considered to print? What is
```
switch (a) case 1: 42
```
supposed to print? I think the current mental model of the "outer-most expression" is compatible with the syntax ("add a ';' to make it valid C++") and comprehensible for users; changing this is a design change that I am not convinced of as it might hurt more than it heals, and causes confusion on the user side plus lots of added complexity.

**Comment by vgvassilev** [comment] 2020-10-21 10:11
> OK, what about
> 
> ```
> do 1 while (true)`
> ```
> 
> ? I.e. where do we stop? (Note that this isn't parsable, and appending a trailing ';' doesn't help.)

  I think you just said what's the rule -- appending trailing ; and making the code compile.

> 
> For me, an inner block (even if the '{}' are omitted) is not considered by the value printer; changing that is likely not work it and will create many more inconsistencies than is warranted by "repairing" the seemingly inconsistent behavior of this ticket. To be more precise, why isn't
> 
> ```
> if (true) { 1 }
> ```

  This should not print because the current implementation makes it hard to support as it is implicit. Eg, we omit certain syntax and rely on fixing it. If the implementation was explicit and we had a smarter marker what should or should not print we could leave that decision to the user. Eg -- `if (true) {1;;}` print then all would be solved :)

> 
> considered to print? What is
> 
> ```
> switch (a) case 1: 42
> ```
> 
> supposed to print? I think the current mental model of the "outer-most expression" is compatible with the syntax ("add a ';' to make it valid C++") and comprehensible for users; changing this is a design change that I am not convinced of as it might hurt more than it heals, and causes confusion on the user side plus lots of added complexity.

I cannot agree with this. Fixing the particular bug is not a design change. Moving towards a generic explicit implementation based on a markers is. I think the current rule whether or not to print is "the last expression without a trailing semicolon should print". And I see no problem in supporting the switch case.

**Comment by Axel-Naumann** [comment] 2020-10-21 12:02
> Moving towards a generic explicit implementation based on a markers is

I cannot follow - who's proposing to move to something, which explicit markers? I'm arguing that the status quo (last top-level expression's value is printed if missing trailing semicolon) should be kept.

**Comment by jalopezg-uc3m** [comment] 2020-10-21 12:36
> > Moving towards a generic explicit implementation based on a markers is
> 
> I cannot follow - who's proposing to move to something, which explicit markers? I'm arguing that the status quo (last top-level expression's value is printed if missing trailing semicolon) should be kept for consistency and simplicity reasons.
> 
> Let's hear some other opinions here, e.g. @SimeonEhrig @jalopezg-uc3m @pcanal ?

After reading the discussion, I have no clear opinion, but...  What about preserving the current behavior plus the one that @vgvassilev suggests, i.e. a marker (e.g. NullStmt) can be used to indicate that the previous expression should be printed?

**Comment by Axel-Naumann** [comment] 2020-10-21 14:18
IIUC a NullStmt would mean `if (true) {1;;}`.

I'd prefer to keep value printing simple and instead invest where it's relevant: devtoolset, debug symbols, llvm upgrade (to llvm 11!), etc. This is a trade-off we should consciously do, and given that this is the first time I hear a request for value printing within nested blocks I'm not yet convinced that it's worth the effort (and yes, that's an additional counter argument). And I'm not just talking dev time but also long-term maintenance: more code, more clang interfaces used.

**Comment by SimeonEhrig** [comment] 2020-10-21 15:04
> IIUC a NullStmt would mean `if (true) {1;;}`.
> 
> I'd prefer to keep value printing simple and instead invest where it's relevant: devtoolset, debug symbols, llvm upgrade (to llvm 11!), etc. This is a trade-off we should consciously do, and given that this is the first time I hear a request for value printing within nested blocks I'm not yet convinced that it's worth the effort (and yes, that's an additional counter argument). And I'm not just talking dev time but also long-term maintenance: more code, more clang interfaces used.

I agree with Axel. A smarter value printer is nice to have but we have enough more important issues.

**Comment by vgvassilev** [comment] 2020-10-21 17:59
> > Moving towards a generic explicit implementation based on a markers is
> 
> I cannot follow - who's proposing to move to something, which explicit markers? I'm arguing that the status quo (last top-level expression's value is printed if missing trailing semicolon) should be kept for consistency and simplicity reasons.
> 
> Let's hear some other opinions here, e.g. @SimeonEhrig @jalopezg-uc3m @pcanal ?

I do realize my post was terse. Here is more text as the discussion went in another direction.

Since early days, as you already mentioned, the rule seems to be "the last expression without a trailing semicolon should print". If that is the rule, then it clearly does not handle short-hand operators. Namely, `if (x) expr`. That rule does not extend to your examples `do 1 while(true)` as `while` is not really an user-defined expression. `if (x) { expr }` does not fall there either as it is in a compound statement. It is pretty clear where we stop. The construct `if(x) expr`, as shown in the example, enables an interactive programming pattern wrt error handling where in case of an error we can just ask cling to print details.

> I'd prefer to keep value printing simple

The implementation of what I propose requires 2-3 lines [here](https://github.com/vgvassilev/cling/blob/856f8e92f82f9037b3dbb27ae7f94add2ed6121f/lib/Utils/AST.cpp#L141-L152). And actually makes the value printing rule more comprehensible. It took me some time to realize what's wrong and I implemented it, so I'd say it would be less comprehensible to other people.

> and instead invest where it's relevant: devtoolset, debug symbols, llvm upgrade (to llvm 11!), etc. This is a trade-off we should consciously do, and given that this is the first time I hear a request for value printing within nested blocks 

We have had that in the past. I do not think having not user requests should be an argument against this bug.

> I'm not yet convinced that it's worth the effort (and yes, that's an additional counter argument). And I'm not just talking dev time but also long-term maintenance: more code, more clang interfaces used.

 The implementation does not require clang interfaces and it is couple of lines.

**Comment by Axel-Naumann** [comment] 2020-10-22 09:34
> it is couple of lines

Well then. I'm still not convinced that it's an improvement in terms of consistency, but you seem to be convinced otherwise.

Please make sure these "couple of lines" handle `if`, `while`, `switch` etc - to not increase inconsistency. Please make sure this does not introduce a lifetime issue with `if (int a = 42) a`. Please make sure `if (true) while (true) if (true) 42` is handled, again for consistency reasons.

**Closed** 2024-04-24 12:48 UTC
Labels: bug, in:Cling

**Comment by pcanal** [comment] 2024-04-24 17:58
Note, in my opinion the current behavior is to replace:
```
expression_not_ending_with_semi_colon
```
with the moral equivalent of 
```
auto tobeprinted = expression_not_ending_with_semi_colon;
std::cout << tobeprinted << std::endl;
```
which the current implementation handles as expected:
```
root [0] auto x = if (true) 1;
ROOT_prompt_0:1:10: error: expected expression
auto x = if (true) 1;
         ^
root [1] true ? 1 : 0
(int) 1
```
