### ISSUE TITLE
Error in modulemap.overlay

### ISSUE THREAD

**Issue by etejedor** [root-project/root#8157] opened 2021-05-11 14:23 UTC
### Describe the bug

I booted a CERN Openstack VM with the CentOS7 image.

I sourced dev3 on CVMFS, i.e. the LCG stack with ROOT master. In particular:

`source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc8-opt/setup.sh`

and I tried to import ROOT from Python.

When doing so, I observed the following error:

```
error: entry with relative path at the root level is not discoverable
{ 'name': '', 'type': 'directory',
          ^~
Error in modulemap.overlay!

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 7 (Thread 0x7f7003fff700 (LWP 1242) "python"):
#0  0x00007f704d3e3549 in waitpid () from /lib64/libc.so.6
#1  0x00007f704d360f62 in do_system () from /lib64/libc.so.6
#2  0x00007f704d361311 in system () from /lib64/libc.so.6
#3  0x00007f7003163e83 in TUnixSystem::StackTrace() () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCore.so
#4  0x00007f70031667a5 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCore.so
#5  <signal handler called>
#6  0x00007f6ff7060608 in llvm::vfs::OverlayFileSystem::pushOverlay(llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#7  0x00007f6ff46b3b3c in (anonymous namespace)::collectModuleMaps(clang::CompilerInstance&, llvm::SmallVectorImpl<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&) [clone .constprop.586] () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#8  0x00007f6ff46b45fe in (anonymous namespace)::setupCxxModules(clang::CompilerInstance&) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#9  0x00007f6ff46b6e01 in (anonymous namespace)::createCIImpl(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, cling::CompilerOptions const&, char const*, std::unique_ptr<clang::ASTConsumer, std::default_delete<clang::ASTConsumer> >, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, bool, bool) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#10 0x00007f6ff46b8b0c in cling::CIFactory::createCI(llvm::StringRef, cling::InvocationOptions const&, char const*, std::unique_ptr<clang::ASTConsumer, std::default_delete<clang::ASTConsumer> >, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#11 0x00007f6ff476e825 in cling::IncrementalParser::IncrementalParser(cling::Interpreter*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#12 0x00007f6ff46e6eeb in cling::Interpreter::Interpreter(int, char const* const*, char const*, std::vector<std::shared_ptr<clang::ModuleFileExtension>, std::allocator<std::shared_ptr<clang::ModuleFileExtension> > > const&, bool, cling::Interpreter const*) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#13 0x00007f6ff46276da in TCling::TCling(char const*, char const*, char const* const*) () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#14 0x00007f6ff4628c20 in CreateInterpreter () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCling.so
#15 0x00007f70030165d9 in TROOT::InitInterpreter() () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCore.so
#16 0x00007f7003016a8f in ROOT::Internal::GetROOT2() () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libCore.so
#17 0x00007f70035e68a2 in __static_initialization_and_destruction_0(int, int) [clone .constprop.376] () from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Mon/x86_64-centos7-gcc8-opt/lib/libcppyy_backend3_8.so
#18 0x00007f704e7d19c3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#19 0x00007f704e7d659e in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#20 0x00007f704e7d17d4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#21 0x00007f704e7d5b8b in _dl_open () from /lib64/ld-linux-x86-64.so.2
#22 0x00007f704dbf1fab in dlopen_doit () from /lib64/libdl.so.2
#23 0x00007f704e7d17d4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#24 0x00007f704dbf25ad in _dlerror_run () from /lib64/libdl.so.2
#25 0x00007f704dbf2041 in dlopen

GLIBC_2.2.5 () from /lib64/libdl.so.2
... (more Python-related stack)
```

Installing the ROOT dependencies in the system fixed the error. I ran the following command:

`sudo yum install git make cmake3 gcc-c++ gcc binutils libX11-devel libXpm-devel libXft-devel libXext-devel python openssl-devel`

but I don't know exactly what dependency fixed it.

**Comment by dpiparo** [comment] 2024-08-22 12:55
@etejedor I am really sorry to come back to this after all this time. I cannot reproduce any more the issue, and we did not get any report about it at least during the last 10 months. I am closing the issue, inviting you to re-open another one in case you encounter the problem again.

**Closed by dpiparo** 2024-08-22 12:55 UTC
Labels: bug, affects:master, in:C++ modules
