### ISSUE TITLE
[ROOT-10973] TASImage read from file not displayed (correctly)

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14545] opened 2024-02-04 17:41 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-10973

If store canvas from `tutorials/image/rose_image.C` into file, read it back and draw,
most of the images are not drawn. On the terminal I see errors:
```
libpng error: invalid screen gamma in png_set_gamma
libpng error: invalid screen gamma in png_set_gamma
libpng error: invalid screen gamma in png_set_gamma
libpng error: invalid screen gamma in png_set_gamma
Error in <TASImage::Paint>: no image set
Error in <TASImage::Paint>: no image set
Error in <TASImage::Paint>: no image set
Error in <TASImage::Paint>: no image set
```
Seems to be, all images which are internally stored in PNG format, fails.
Two remaining images are shown with palette, which is not a case with original macro.

### Reproducer

As per description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by ferdymercury** [comment] 2024-02-05 07:51
maybe related: https://github.com/root-project/root/issues/8125

**Comment by couet** [comment] 2024-02-13 10:40
I cannot reproduce this issue. I saved the image produced by tutorials/image/rose_image.C into a .root file. Then in a fresh ROOT session, I read it back and display the image. It works fine. No errors.  I am on Mac. Maybe @linev can tell if that's what it tried?

**Comment by linev** [comment] 2024-02-13 11:37
There was commit ~9 months ago: https://github.com/root-project/root/commit/47fd0a113e590b703b0f8e529d573307f8cb5ce3

After this commit warning `invalid screen gamma` disappeared. 
And now stored canvas can be correctly shown - works for 6.28, 6.30 and master.

Seems to be problem is resolved

**Comment by hahnjo** [comment] 2024-02-14 10:30
Then I guess we should close this issue.

**Closed by hahnjo** 2024-02-14 10:30 UTC
Labels: bug, fixathon
