### ISSUE TITLE
Crash in macro when function does not return value

### ISSUE THREAD

**Issue by linev** [root-project/root#17133] opened 2024-11-29 08:23 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

When run simple macro which defined as:
```
int simple()
{
   printf("Return nothing\n");
}
```

I get warning that macro does not return value, but then ROOT crashes.
On my Mac it just terminate ROOT process, on Linux I getting a stack trace like:

```
#0  0x00007ff0e3b04d87 in wait4 () from /lib64/libc.so.6
#1  0x00007ff0e3a5557b in do_system () from /lib64/libc.so.6
#2  0x00007ff0e4516873 in TUnixSystem::StackTrace() () from /home/linev/build/webgui/lib/libCore.so
#3  0x00007ff0e45161c4 in TUnixSystem::DispatchSignals(ESignals) () from /home/linev/build/webgui/lib/libCore.so
#4  <signal handler called>
#5  0x00007ff0e3c7901a in ?? ()
#6  0x00007ffe0a5f6a40 in ?? ()
#7  0x00007ff0e4807029 in ?? ()
#8  0x00007ffe0a5f7170 in ?? ()
#9  0x0000000021232f10 in ?? ()
#10 0x00007ffe0a5f7170 in ?? ()
#11 0x00007ff0dd038404 in cling::IncrementalExecutor::executeWrapper(llvm::StringRef, cling::Value*) const () from /home/linev/build/webgui/lib/libCling.so
#12 0x00007ff0dcfb3226 in cling::Interpreter::RunFunction(clang::FunctionDecl const*, cling::Value*) () from /home/linev/build/webgui/lib/libCling.so
#13 0x00007ff0dcfb4ce8 in cling::Interpreter::EvaluateInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) () from /home/linev/build/webgui/lib/libCling.so
#14 0x00007ff0dd0ab897 in cling::MetaSema::actOnxCommand(llvm::StringRef, llvm::StringRef, cling::Value*) () from /home/linev/build/webgui/lib/libCling.so
#15 0x00007ff0dd0bedac in cling::MetaParser::isXCommand(cling::MetaSema::ActionResult&, cling::Value*) () from /home/linev/build/webgui/lib/libCling.so
#16 0x00007ff0dd0c0375 in cling::MetaParser::isCommand(cling::MetaSema::ActionResult&, cling::Value*) () from /home/linev/build/webgui/lib/libCling.so
#17 0x00007ff0dd0a38b0 in cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) () from /home/linev/build/webgui/lib/libCling.so
#18 0x00007ff0dceab5aa in HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) () from /home/linev/build/webgui/lib/libCling.so
#19 0x00007ff0dcece42f in TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) () from /home/linev/build/webgui/lib/libCling.so
#20 0x00007ff0dcece85f in TCling::ProcessLineSynch(char const*, TInterpreter::EErrorCode*) () from /home/linev/build/webgui/lib/libCling.so
#21 0x00007ff0e439d037 in TApplication::ExecuteFile(char const*, int*, bool) () from /home/linev/build/webgui/lib/libCore.so
#22 0x00007ff0e4841e4b in TRint::ProcessLineNr(char const*, char const*, int*) () from /home/linev/build/webgui/lib/libRint.so
#23 0x00007ff0e4843571 in TRint::Run(bool) () from /home/linev/build/webgui/lib/libRint.so
#24 0x00000000004011bd in main ()
```

### Reproducer

To reproduce, just run attached macro.
[simple.cxx.txt](https://github.com/user-attachments/files/17956314/simple.cxx.txt)

### ROOT version

master

### Installation method

Build from source

### Operating system

OpenSUSE Linux

**Comment by ferdymercury** [comment] 2024-11-29 10:12
This is a duplicate of https://github.com/root-project/root/issues/15537

**Closed by ferdymercury** 2024-11-29 10:12 UTC
Labels: bug, affects:master, in:Cling

**Comment by linev** [comment] 2024-11-29 10:25
Sorry - did not check dor duplicates
