### ISSUE TITLE
PyROOT cannot call templated ctors on Windows

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#6393] opened 2020-09-21 13:06 UTC
## Describe the bug

Templated ctors cannot be called on Windows because demangling of the constructor *template* (!) fails - likely because there is no mangling standard for the template. See https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx#L1693

## Expected behavior

Template ctor should be called.

## To Reproduce

@hageboeck has it.

## Setup

Master, with MSVC.

## Additional context

Instead of demangling and looking for '<' we could add a new interface: `TFunction::`-is-this-a-template.

**Comment by hageboeck** [comment] 2020-09-21 14:38
This blocks #6323 

### To reproduce:
On top of the branch hageboeck/RooArgSetUsability_small, run the windows equivalent of:
```.py
import ROOT
x = ROOT.RooRealVar()
s = ROOT.RooArgSet(x)
```

Or run the pythonisation ctests from the linked PR.

**Comment by wlav** [comment] 2020-09-21 17:31
"Templated ctors cannot be called on Windows because demangling of the constructor template (!) fails"

No ... it fails b/c either ROOT/meta or the Cling lookupHelper is not capable of recognizing constructor names with provided template parameters. The demangling hack was just a quick & easy way around that, esp. the lookupHelper being a very brittle piece of code that is hard to modify. However, since the demangling by definition does not allow anything except an exact match (the lookupHelper being a tad more flexible, albeit not by enough), it's a very poor option.

But cppyy handles templated constructors just fine on Windows, so there is probably some truth in this patch:
  https://bitbucket.org/wlav/cppyy-backend/src/master/cling/patches/win64s2.diff

This patch removes the Clang internal marker for Windows mangled symbols. This marker is (mostly) gone in Clang master, too. There are other reasons for this patch, such as lookup of global variables, which is what started the initial discussion with Bertrand that grew into this patch.

However, I re-emphasize that it is better to fix the actual problem than muck with the workaround.

**Comment by Axel-Naumann** [comment] 2020-09-22 07:02
IIUC we have two options:
1) give the ctor a name that includes the template parameter list. This breaks an assumption used throughout ROOT on "ctors' name == class name". Maybe even cppyy? But it's code, we can change that.
2) provide cppyy with the templateness of functions.
So we'll have to "muck" either way. My guesstimate is that option 2) is less intrusive, also for our users. I am aware of modern llvm having improved the mangling; I still think (as you) that demangling isn't the perfect solution here in clingwrapper, and we're bitten by this now, with the llvm upgrade still ongoing.

Let me know your thoughts about (against?) option 2, or what other option I miss.

**Comment by wlav** [comment] 2020-09-22 15:07
The constructor comparison really shouldn't be necessary as ROOT/meta provides a flag. See this code in clingwrapper.cxx:

```
bool Cppyy::IsConstructor(TCppMethod_t method)
{
    if (method) {
        TFunction* f = m2f(method);
        return f->ExtraProperty() & kIsConstructor;
    }
    return false;
}
```
I presume it being in the overflow "extra" property means that it is relatively newer, so probably there's still code out there that does name comparisons, but that shouldn't be hard to fix.

Provide the "templateness of functions" is just as much a hack. Every single line of code beyond `GetMethodWithPrototype()` is a hack and should not have to exist. The solution would be for the lookupHelper to return all the candidates rather than shoe-horning the matching through the prototype string. Right now, a lookup call initiated from CPyCppyy can lead to as many as a dozen lookups, each finding and discarding (!) the candidates over and over, as it tries to massage the prototype string (and the series of hacks that follows) into submission. And can still fail!

This is a rather old problem and we've discussed it many times. And yet, here we are again, expending more time on the workarounds and other hacks instead of fixing it properly. Yeah sure, maybe libIncremental will fix it one day.

Now this Windows bug gets some love, but off the top of my head, I now at least 4 more bugs hampered by this: matching with enums for COOL (fixed in cppyy, broken in PyROOT); default template arguments for RDataFrame (fixed in cppyy, broken in PyROOT); mixing `obj*`, `obj&`, and `obj&&` (broken in both); mixing `std::initializer_list<>` and `std:vector<>` or other STL container (broken in both). Some of these bugs predate cppyy. Another (non-Python) user of clingwrapper more recently came up to the same problem of wanting the lookup candidates in order to facilitate a match. 

It's a horrible time sink and will remain so as long as the preference is to hack workarounds rather than fix the problem of the lookup.

**Comment by Axel-Naumann** [comment] 2020-09-22 15:21
A while back you said
```   OPAQUE_HANDLE h = interp->GetOverloads("func_name");
   for (sig : sigs) {
       f = interp->Match(h, sig);
       if (f) break;
   }
   interp->Delete(h);
   return f;
```
That's super awkward from compilers - some of the overloads
- need to be instantiated first
- are only visible through ADL
- are hidden friends
to name a couple of eeews that come to my mind.

The only reasonable way to do lookup in C++ is *with* the arguments, i.e. starting from an expression. Is that feasible for cppyy, e.g. possible code-path-wise, acceptable performance-wise?

**Comment by wlav** [comment] 2020-09-22 16:04
Performance-wise and functionality-wise would still work if for the duration of the trials, the state needed to do the matching is kept alive. That was mostly the idea with the code above, but is not how I would solve it today.

So, to your points:

No, it does not need to be instantiated first. For example, if I know that a _potential_ match has a signature of `T*`, then I'm not going to ask it to match `T&`, so even before instantiation, the lookup has useful information. Right now, CPyCppyy loops over each, so will eventually match if all types are by-pointer or all are by reference, but that fails combinations. Another good case is knowing which arguments are based on template parameters and which are not, so that the non-template ones need not be varied.

No, on the Python side it is fair game to provide the template arguments, and thus non-ADL happens, too. E.g. all int types are equivalent as far as Python is concerned, and although CPyCppyy will increase the template int argument if it has an argument value larger than will fit, it is not uncommon for Python users to simply fill in `int64_t` or whatever. In fact, as-is, if the prototype lookup, ie. argument dependent, fails, CPyCppyy will assume that we're dealing with the common case where all argument types are template parameters. (It's a human thing to make that order consistent, which is why it works quite often, but it is not a language requirement/guarantee.) It then asks for the full name in a non-ADL manner.

ROOT/meta (lookupHelper, I think) does not even support friends, so no worries there.

Whether you think it is "eeew" or not is irrelevant. That's highly a technical term. What is relevant is that just before the lookupHelper does a `BestViableFunction()` it has a `OverloadCandidateSet` and I can do a much better job finding my own match than can do Sema, b/c the rules to apply aren't exactly the C++ ones (the only ones that Sema knows). Unfortunately, I can't just return the set, as it's deep in the bowels of lookupHelper, whose bowels are very deep if you ever looked, and AFAICT, there is a current transaction that needs to be returned with it and maybe more. Plus if returned, there also needs to be a cleanupHelper.

**Comment by Axel-Naumann** [comment] 2020-09-22 16:26
OK so what you're after is:
- ignore hidden friends, ignore ADL. This breaks any current stdlib usage; you have been warned :-)
- collect all occurrences of a name, be it function template or function.

Correct? Can be done, but you might not like the result. I understand that it's *better* than what we have now; but I think it's not good enough. Why can you not:

* pass Python integers as `int`, then `long`, then... (i.e. keep re-trying)?
* pass strings as `const char*`s
* pass collections as `begin(). end()`
*...

i.e. have a mapping into C++ expressions, instead of wanting to do (a C++ feature-restricted version of) overload resolution inside cppyy? Can you expand on "I can do a much better job finding my own match than can do Sema, b/c the rules to apply aren't exactly the C++ ones (the only ones that Sema knows)". Why can you not model type conversion options into C++ argument types, instead of doing that conversion model yourself from C++ function argument types? Is it performance?

`LookupHelper` exists, but I insist it's inadequate for expressions.

I will try to resist from being colloquial from here on, please slap me should it ever happen again ;-)

**Comment by wlav** [comment] 2020-09-22 18:07
The problem with trying one after the other is that the number of combinations quickly goes through the roof. Consider that a python-side proxy can be freely converted from/to `T*`, `T**`, `T[]`, `T&`, `T&&`, and their `std::shared_ptr<>` and `std::unique_ptr<>` equivalents. So, that may mean 15 tries. If there are 3 arguments, the number of combinations is 455, faculty being what it is. Sure, I can make some educated guess to put the most likely candidates first, and that is basically when is currently going on. But a single lookupHelper call for template instantiation can already be too slow to be usable: e.g. for PCL they run (after the first 7-14s loading, which modules should fix) they are still of the order of 0.1s.

(We have discussed that problem, too: contrary to normal Clang usage, Cling dumps everything in a single translation unit, vastly increasing the number of possible matches. Try going after `operator<<(std::ostream&)` or `operator==` in the global namespace, for example.)

You mention int, but there are `int8_t`, `uint8_t` (these are often `char` varieties), `short`, `unsigned short`, `int16_t`, `uint16_t`,  `int`, `unsigned int`, `long`, `unsigned long`, `long long`, and `unsigned long long` to try.

Sure, let's do `str` to `const char*`, but that won't work for `std::string&`, and `std::string` usage is more common. But ah, what about `wchar_t`, `char16_t`, `char32_t`, `std::wstring`?

Collections, sure, but what if instead I have a tuple or list on the Python side and the template expects some STL container? Then it can not just be that STL container of say `T*`, but also the STL container of pointer any of the base classes, or worse, a mix thereof.

And what if the tuple isn't actually targeting a container, but is an initalizer_list? There is often no (relevant) type information available at that point in Python, but many cases can still be resolved b/c the C++ side has some hints. For example `template<typename T, int N> void func(const std::array<T, N>&)` being given a Python tuple `(1, 2, 3)`. Absolutely clear what needs to be done for the conversion to work, but otherwise yet another case to add to the combinatorics.

The above, current, situation is very much "eeew" and "might not like the result." It has also reached its breaking point, as you can see from the open bug reports and the constant hacking on workarounds.

I appreciate that for the old PyROOT no-one actually seriously used templates, as folks avoided it in their interfaces b/c of non-support in the CINT world. The only client with moderately interesting templates would be RDataFrame. But in the real world, folks write modern C++ and template usage is much more pervasive. Just last week, I was looking at a massive series of variadically templated constructors: each peeled of an argument to eventually initialize a grand total of 3 data members. It was just a struct with an `unsigned int`, a `double`, and an `std::array<double, 3>`. The point of the whole set of constructors being that you can use initializer syntax with the data member in every order, either the "naked" types or with casts of explicitly named typedefs. Oh, it works _now_, with yet another workaround, but it actually crashed `lookupHelper` (segfault and die; and it's not the only one; I have a few more for Vassil, e.g. lookup in an unnamed namespace also crashes deep, deep inside Cling/Clang). So, I consider that another strong argument against "trying": anything beyond the usual basic stuff simply segfaults.

**Comment by Axel-Naumann** [comment] 2020-09-23 07:56
OK, so your approach would be to get the "obvious" set (I cannot think of a better term) of overloads, and for now just ignore hidden friends? (ADL can be worked around on the caller side, *if* people know where to find the suitable name.)

Hidden friends are very much appreciated in the standards committee, as the reduce the size of overload sets. You will then have to work around that on the cppyy side - I could imaging that to be possible, with some help from cling.

You will still have to sort out what to do for operators. Even today we run into a wall in clang with `operator@(T1 a, T2 b)` where clang isn't happy. I forgot the details (it was about being able to spell templated operators), but I remember the conclusion of Richard Smith: we'll have to switch to expression-based operator invocation (`a @ b`) rather than function-style invocation `operator@(a,b)`. As I said, that's what C++20 and later impose anyway. We might be lucky and not see this issue in lookup, only in evaluation - but I doubt that. So it'd be good if we could come up with a plan B here, too.

I will see that we implement the generic lookup you're after. I would still appreciate feedback on `op@` - I'd hate implementing something we cannot use in the end.

**Comment by wlav** [comment] 2020-09-23 15:18
Beyond that, I still think you do not understand at all how this would work. You seem to think that it is either letting `BestViableFunction()` do all the work _or_ doing all the work myself. But there are many scenario's where inspecting the set can provide better arguments to `BestViableFunction()`, such as already mentioned: knowing which parameters to keep fixed, which qualifiers to use, which STL containers to target. That alone would be a win before going on the fully reimplement that call.

Yes, friends are still an issue, but they're not supported today either yet. Yes, people need to know a name, that is true today, and always will be: nature of dynamic languages like Python. Those operators are a total non-issue, as I'm doing expression-based invocation already in my version of TClingCallFunc (precisely b/c templates and function-style do not mix), so yes, if you still have the same old code there in ROOT then it's totally a problem for PyROOT, but it's already fine for cppyy. (I've also switched in the last release to something similar for `operator<<`, b/c a) friends didn't work and b) some lookupHelper functions crashed when trying to find it).

**Comment by Axel-Naumann** [comment] 2020-09-23 16:11
> But there are many scenario's where inspecting the set can provide better arguments to BestViableFunction()

Yes, that's what you explained.

> I'm doing expression-based invocation already

OK excellent, then I don't see an issue. Note that you *cannot* spell the scope of hidden friends, i.e. you cannot invoke them by anything but expressions. It wasn't clear from what you said whether you were aware of that. And the fact that it's not a concern now is of no concern to me, as we should plan for C++20 and up, not the past.

We'll come up with an interface proposal and run that by you (problem as usual isn't so much brain but time). Until then: I hope you agree that #6389 is an incremental improvement, happy to hear your comments there as it also touches cppyy.

**Comment by wlav** [comment] 2020-09-23 16:46
> It wasn't clear from what you said whether you were aware of that.

There are zounds of things that I'm not aware of, but as said, the kind of C++ that folks outside of HEP expect to "just work" with cppyy is rather more advanced that the basic C++98 that most folk in HEP still use. Heck, you guys are even still hung up on Python2.7! Anyway, the reason I changed the implementation is b/c it is already not working _today_. C++20 (which Clang5 doesn't support anyway) is just gravy.

As for #6389, I'm too far diverged from since I forked ROOT/meta to apply it, so have no interest in it. I'm also not familiar with how the "special functions" boil upward. Note that, going back to the initiation of this thread: there was/is no issue with constructors for cppyy proper on Windows: both 32b and 64b, work fine. So, I see no benefit even in trying it out.

I'm currently fixing that crash in lookupHelper with unnamed namespaces. Seems the solution is upgrading Cling _and_ a judiciously placed `Interpreter::PushTransactionRAII` (the crash is actually an abort b/c of an open transaction). Then still modules, have to see how Windows looks now; after that, this change to lookupHelper's handling of templates is high on my list.

**Comment by wlav** [comment] 2020-09-23 17:26
Yeah, looks like ROOT/meta in master still does it wrong. Example:

```
import cppyy
  
cppyy.cppdef("""\
class TOIClass {
public:
    template<typename T>
    bool operator<(T t) { return true; }
};""")


from cppyy.gbl import TOIClass

assert (TOIClass() < 1)
```

which runs fine to completion, v.s.:

```
import ROOT
  
ROOT.gInterpreter.Declare("""\
class TOIClass {
public:
    template<typename T>
    bool operator<(T t) { return true; }
};""")


from ROOT import TOIClass

assert (TOIClass() < 1)
```

which gives me:
```
input_line_39:6:43: error: no member named 'operator<<' in 'TOIClass'
      new (ret) (bool) (((TOIClass*)obj)->operator<<int>(*(int*)args[0]));
                        ~~~~~~~~~~~~~~~~  ^
input_line_39:10:25: error: no member named 'operator<<' in 'TOIClass'
      ((TOIClass*)obj)->operator<<int>(*(int*)args[0]);
```

Sure, this is a trivial example, nothing to do with lookup per se, but it's one of many issues that are resolved by not calling operator functions explicitly.

**Comment by Axel-Naumann** [comment] 2020-09-23 17:56
> I'm too far diverged from since I forked ROOT/meta to apply it, so have no interest in it.

The beauty of forks. OK, we (ROOT) will discuss what to do.

> resolved by not calling operator functions explicitly.

Indeed, as I said :-)

**Comment by wlav** [comment] 2020-09-23 18:57
Forking was necessary; not looking back. Last release I followed, 6.20, broke so much stuff, especially on Windows. It's not tenable to follow ROOT master if one cares about more than a single version of Scientific Linux.

**Closed** 2020-10-01 13:10 UTC
Labels: affects:master, bug, in:PyROOT

**Comment by Axel-Naumann** [comment] 2020-10-05 13:40
> It's not tenable to follow ROOT master if one cares about more than a single version of Scientific Linux.

I either don't understand that statement or it's FUD, see e.g. master's nightlies https://lcgapp-services.cern.ch/root-jenkins/job/root-nightly-master/2653/
![Screenshot from 2020-10-05 15-38-53](https://user-images.githubusercontent.com/144675/95086565-ed820080-0720-11eb-8c3c-612725618361.png)

**Comment by wlav** [comment] 2020-10-05 14:40
FUD? The new way of finding python in 6.20 required python-dev, breaking conda builds. The introduction of modules, not disabled by minimal, broke mac-debug and Windows builds. In the core libraries, new code appeared that casted pointer types to long, causing more Win64 breakage. Not that ROOT runs on Win64 at all and requires the exact same compiler on the user's end on Win32. Users can also not trivially switch C++ versions unless they rebuild from source, this on any platform. Several of these issues were also reported on the ROOT forum.

What you are showing is that *you* are able to build ROOT on some carefully prepared machines with your carefully selected set of compilers. In that list of nightlies, you are not even building binaries on one machine and running them on others.

Again, this is why I forked: you obviously have different goals in mind when you dismiss clear problems as "FUD." I can't work in such an environment.

**Comment by Axel-Naumann** [comment] 2020-10-12 15:37
Your latest comment contains technical criticism that I find indeed relevant, thanks! (I still don't understand "a single version of Scientific Linux".)

FYI we're using the system's default compiler, not sure how that's "carefully selected". That does not address your point on ROOT being too compiler-version specific. As you probably know we're working on that (slowly...) - but we don't believe that generating PCMs on user side scales well. We might be proven wrong :-)

**Comment by wlav** [comment] 2020-10-12 18:15
Shipping PCMs is just another problem. For example, on Windows, MSVC likes to change header guards, so unless you use the _exact_ same compiler as ROOT was built with, you'll get a crash because of redefinitions. There are a couple of similar issues on Linux, which you "fix" by shipping Linux system headers (wchar.h, stat.h, time.h). But woe onto the poor bugger that has such headers significantly different from Scientific Linux on their system (e.g. Python's manylinux docker image ...).

An no, Windows does _not_ have a system compiler. *You* selected one that works for you. Windows applications are quite binary compatible (more so than e.g. Mac, and certainly easier than Linux varietals), so that's a choice.

Neither has Mac for that matter: folks are free to update Xcode or not. Of course, you're saved here b/c even older Clang on Mac is pretty up-to-date with C++, but no such luck on Windows. On the other hand, modern MSVC is fine, but then Clang5 underpinning Cling can not parse the C++ library headers of MSVC 19 with C++17 enabled. So catch-22.

Shipped PCMs also prevent developers from using OpenMP with Cling, but at least that can still be done in libraries, which can be linked without otherwise exposing OpenMP.

However, the baked-in choice for _not_ having AVX means not only that Cling can not use it, but also causes binary incompatability with libraries that were compiled with AVX enabled (e.g. many/most Eigen-based codes).

Then there is the version of C++ being fixed by the PCMs (and worse, in RConfig.h and the "backported" stringview classes, so it's not a simple matter of wiping the local PCMs and rebuilding), meaning C++11 is the only supported version unless you do a full recompile (and see the forum for how much fun that is).

And if you look at the whole list of nightlies of the past couple of weeks, and not only at the carefully selected all-green one out of a sea of red that you posted above, you'll see that non-Linux platforms fail disproportionally often. (In fact one of the recent "green" releases is only green b/c MacOS 10.15 and Windows10 are switched off.) That tells me that most of your developers work on Linux, and rely on the nightlies to catch any portability issues. That's a very poor approach b/c your matrix is necessarily limited given the enormous number of possible combinations. (That's another way of saying it's carefully selected.)

I don't actually know if all those Linux systems are SLC, but did note for example that the build failed on SuSE Tumbleweed with gcc9, b/c SuSE does not install TBB by default to go with that compiler, and the build was missing headers as a consequence. So I do strongly suspects a lot of conformity in distros there.

As-is, this approach of trying it, see if it fails, and if it doesn't fail declare it "portable" is exactly what causes folks to still cast pointers to long, for example. This would never happen if code was written with portability in mind from the get-go.

But your closer exemplifies that even better: given the choice between *potential* scaling problems and *guaranteed* portability problems, you choose to accept the latter. Clearly, portability isn't high on your list.

Portability is, however, very important. By providing a portable solution that works well within other environments, cppyy is now being used on large code bases in mathematics, chemistry, and biology. That work uncovers errors even deep inside Cling, because it is pushed harder and used differently than in the CINT-tamed HEP world.

Here is a current problem I'm working on for example. Try it in ROOT master, and watch memory consumption grow with top or whatever:

```
  $ root -l -b
  root [0] template <class T, class U> class __gmp_expr;
  root [1] typedef struct{ } __mpz_struct;
  root [2] typedef __gmp_expr<__mpz_struct[1],__mpz_struct[1]> mpz_class;
  root [3] for (;;) gInterpreter->ClassInfo_IsEnum("std::vector<mpz_class>::value_type")
```

That leak occurs when `findScope` in the LookupHelper starts parsing whenever `quickFindDecl()` fails (it's nothing to do with `mpz_class` or `ClassInfo_IsEnum` per se, just that that's where it was first found). If `quickFindDecl()` succeeds, then no leak. Since this is an accumulation of internal state, it will _not_ be reported by valgrind as a leak. Use of `findScope` is pervasive, not just from Python, but also from I/O and in clingutils. So, you're sitting on a leak even in HEP (where, especially in the LHC experiments, memory is precious), but your standard test tools won't catch it. To discover these types of deep problems, you need portable software, as that allows it to be used by a wider audience, causing it to be better tested simply through the virtue of having more eyes on it.
