### ISSUE TITLE
`TTreeReaderArray` does not support `Double32_t `

### ISSUE THREAD

**Issue by pcanal** [root-project/root#11260] opened 2022-08-26 23:04 UTC
With the example below, we get:

```
Error in <TTreeReaderArrayBase::GetBranchContentDataType()>: The branch h.fData.fPx contains a data type 9 for which the dictionary cannot be retrieved.
```

This was seen during investigations by CMSSW team of leveraging `Double32_t` and `Float16_t` to reduce data size.

Cheers,
Philippe.

```
#include "TTree.h"
#include "TTreeReader.h"
#include "TTreeReaderArray.h"

struct Inside {
  Double32_t fPx;
  double fPy;
};

struct Holder {
  std::vector<Double32_t> fValues;
  std::vector<Inside> fData;
};

#ifdef __ROOTCLING__
#pragma link C++ class Inside+;
#pragma link C++ class Holder+;
#pragma link C++ class std::vector<Inside>+;
#pragma link C++ class std::vector<Double32_t>+;
#endif

void exec()
{
  auto t = new TTree("t","t");
  Holder h;
  t->Branch("h.", &h);
  t->Fill();
  t->Print();
  TTreeReader r(t);
  //TTreeReaderArray<Double32_t> arr1(r, "h.fValues");
  TTreeReaderArray<Double32_t> arr2(r, "h.fData.fPx");
  TTreeReaderArray<Double32_t> arr3(r, "h.fData.fPy");
  r.Next();
 // arr1.GetSize();
  arr2.GetSize();
  arr3.GetSize();
}
```

**Comment by pcanal** [comment] 2022-08-26 23:05
@Dr15Jones I can reproduce the problem.

**Comment by eguiraud** [comment] 2022-08-29 08:54
@pcanal this might be a duplicate of https://github.com/root-project/root/issues/10645

**Closed** 2022-09-01 17:41 UTC
Labels: bug
