### ISSUE TITLE
docs for RooAbsPdf have some method signatures missing

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#8533] opened 2021-06-24 14:41 UTC
- [github] Checked for duplicates

### Describe the bug
Open the docs for [RooAbsPdf::createChi2()](https://root.cern.ch/doc/master/classRooAbsPdf.html#afa0fa22e51246c8360116b730acefa54). The function is written as

    RooAbsReal * RooAbsReal::createChi2

while in the header (in the list of all methods at the top of the page), it has some parameters

     virtual RooAbsReal * createChi2 (RooDataHist &data, const RooCmdArg, ...)

Look at several overloaded methods too, some have missing signatures as well.

### Expected behavior

Method signatures should be present (like for other methods).

**Comment by couet** [comment] 2021-06-24 16:10
It is a bit more weird than that because `RooAbsReal* RooAbsReal::createChi2` appears in the `RooAbsPdf` doc.

**Comment by couet** [comment] 2021-06-25 07:03
RooAbsPdf inherits from RooAbsReal . When looking at createChi2 from [RooAbsReal](https://root.cern.ch/doc/master/classRooAbsReal.html#a2887f87bb87fd035c6a0ee5db55aef35) it shows the parameters when looking at it from [RooAbdPdf](https://root.cern.ch/doc/master/classRooAbsPdf.html#a2887f87bb87fd035c6a0ee5db55aef35) it doesn't. I have no answer yet. It might be a doxygen issue.

**Comment by couet** [comment] 2021-06-25 09:03
It seems to be a doxygen issue. I submitted  an issue, with a simple reproducer,  in the doxygen repository: 
https://github.com/doxygen/doxygen/issues/8620

**Comment by couet** [comment] 2021-06-28 07:17
This is now fixed in doxygen. See doxygen/doxygen#8620

**Closed** 2021-07-05 04:56 UTC
Labels: bug, in:Documentation
