### ISSUE TITLE
[bug] Clang builds ROOT libraries that emit FPEs

### ISSUE THREAD

**Issue by andriish** [root-project/root#6677] opened 2020-10-20 15:09 UTC
### Describe the bug

ROOT libraries compiled with clang and high optimization level emit floating point exceptions in the simplest codes.

### Expected behavior
No FPEs.

### To Reproduce
Compile the code below  using clang
```
clang++ -D_FORTIFY_SOURCE=2 -O4 -pipe -g -Wall -D_REENTRANT -D_GLIBCXX_ASSERTIONS -std=c++1y -o color5.exe color5.cxx
```
and run 
```
./color5.exe
```
Output of the reproducer

```
msum   0.300000 0.100000
Floating point exception (core dumped)
```

The same compilation with ``-O1`` produces a working executable.

Please note that this code is a reproducer obtained from the TColor::RGB2HLS  static function.

```
#include <iostream>
#include <stdlib.h>

#include <fenv.h>
#define Float_t float
#ifndef HAVE_FEENABLEEXCEPT
#if defined(__APPLE__) && defined(__MACH__)

// Public domain polyfill for feenableexcept on OS X
// http://www-personal.umich.edu/~williams/archive/computation/fe-handling-example.c

inline int feenableexcept(unsigned int excepts)
{
    static fenv_t fenv;
    unsigned int new_excepts = excepts & FE_ALL_EXCEPT;
    // previous masks
    unsigned int old_excepts;

    if (fegetenv(&fenv)) {
        return -1;
    }
    old_excepts = fenv.__control & FE_ALL_EXCEPT;

    // unmask
    fenv.__control &= ~new_excepts;
    fenv.__mxcsr   &= ~(new_excepts << 7);

    return fesetenv(&fenv) ? -1 : old_excepts;
}

inline int fedisableexcept(unsigned int excepts)
{
    static fenv_t fenv;
    unsigned int new_excepts = excepts & FE_ALL_EXCEPT;
    // all previous masks
    unsigned int old_excepts;

    if (fegetenv(&fenv)) {
        return -1;
    }
    old_excepts = fenv.__control & FE_ALL_EXCEPT;

    // mask
    fenv.__control |= new_excepts;
    fenv.__mxcsr   |= new_excepts << 7;

    return fesetenv(&fenv) ? -1 : old_excepts;
}

#else
inline int feenableexcept(unsigned int excepts)
{
#pragma STDC FENV_ACCESS ON
    fexcept_t flags;
    /* Save current exception flags. */
    fegetexceptflag(&flags, FE_ALL_EXCEPT);

    feclearexcept(FE_ALL_EXCEPT);   /* clear all fp exception conditions */
    return fesetexceptflag(&flags, excepts) != 0 ? -1 : flags; /* set new flags */

}

inline int fedisableexcept(unsigned int excepts)
{
#pragma STDC FENV_ACCESS ON
    fexcept_t flags;
    /* Save current exception flags. */
    fegetexceptflag(&flags, FE_ALL_EXCEPT);

    feclearexcept(FE_ALL_EXCEPT);   /* clear all fp exception conditions */
    return fesetexceptflag(&flags, ~excepts) != 0 ? -1 : flags; /* set new flags */
}

#endif
#endif


void FakeRGB2HLS(Float_t rr, Float_t gg, Float_t bb,
                 Float_t &hue, Float_t &light, Float_t &satur)
{
    Float_t rnorm, gnorm, bnorm, minval, maxval, msum, mdiff, r, g, b;
    minval = maxval =0 ;
    r = g = b = 0;
    if (rr > 0) {
        r = rr;
        if (r > 1) r = 1;
    }
    if (gg > 0) {
        g = gg;
        if (g > 1) g = 1;
    }
    if (bb > 0) {
        b = bb;
        if (b > 1) b = 1;
    }

    minval = r;
    if (g < minval) minval = g;
    if (b < minval) minval = b;
    maxval = r;
    if (g > maxval) maxval = g;
    if (b > maxval) maxval = b;

    rnorm = gnorm = bnorm = 0;
    mdiff = maxval - minval;
    msum  = maxval + minval;
    printf("msum   %f %f\n",msum,mdiff);
    light = 0.5 * msum;
    if (maxval != minval) {
        rnorm = (maxval - r)/mdiff;
        gnorm = (maxval - g)/mdiff;
        bnorm = (maxval - b)/mdiff;
    } else {
        satur = hue = 0;
        return;
    }

    if (light < 0.5)
        satur = mdiff/msum;
    else
        satur = mdiff/(2.0 - msum);

    if (r == maxval)
    {
        printf("hue 1\n");
        hue = 60.0 * (6.0 + bnorm - gnorm);
    }
    else if (g == maxval)
    {
        printf("hue 2\n");
        hue = 60.0 * (2.0 + rnorm - bnorm);
    }
    else
    {
        printf("hue 3\n");
        hue = 60.0 * (4.0 + gnorm - rnorm);

    }
    if (hue > 360)
        hue = hue - 360;
}


int main(int argc, char **argv) {
    feenableexcept(FE_DIVBYZERO | FE_INVALID | FE_OVERFLOW);
    Float_t fr = 0.1;
    Float_t fg = 0.1;
    //Float_t fb = 0.1; // no crash
    Float_t fb = 0.2; // crash
    Float_t fh = 0.;
    Float_t fl = 0.;
    Float_t fs = 0.;
    FakeRGB2HLS(fr,fg, fb, fh, fl, fs);
    printf("%10.10f %10.10f  %10.10f \n", fh, fl, fs);
    return 0;
}
```

### Setup
CentOS 7 x86_64 , clang 7.0.1

also observed on  Mac OSX

First seen with official ROOT 6.22 for MacOS X as floating point exception in TColor class.

### Additional context

This  bug was seen first in #6373 

Tag @couet

**Comment by bellenot** [comment] 2020-10-20 15:19
Did you try with non-ROOT related code? (it might be an issue with Clang itself)

**Comment by andriish** [comment] 2020-10-20 15:30
Hi @bellenot  ,

> it might be an issue with Clang itself

That is exactly the point.  clang produces wrong math in libraries/executables with anything higher than -O1. That affects at least some routines in ROOT.

The code I've posted above is a standalone code, despite it is based on code from ROOT.

On the ROOT side one can only change the compilation flags for clang.


Best regards,

Andrii

**Comment by Axel-Naumann** [comment] 2020-10-21 09:28
The example code enables fp exceptions. fp operations are not "stable" - high optimization levels can re-order / re-arrange fp operations, causing fp exceptions that wouldn't be there for lower optimization levels.

I like to understand why fp exceptions are a topic for you. While ROOT does offer an interface to manipulate the fp exception mask, it does *not* turn on fp exceptions by default. I wonder why they are on for you?

**Comment by andriish** [comment] 2020-10-21 09:51
Hi @Axel-Naumann  ,

> high optimization levels can re-order / re-arrange fp operations, causing fp exceptions that wouldn't be there for lower optimization levels.

Yes, I do understand that. However it would make sense to use "fp-save" flags for optimization for software that deals with numerics.  One can assure that with gcc even at high optimization levels, but it looks a bit more complicated task for clang.

> why fp exceptions are a topic for you. 

In general I **always** turn the FP exceptions on for codes that deal with numerics either with or without ROOT. There is no other way to get reliable results. 

In this particular case I was debugging an event display application.  There is some math inside (e.g. to display tracking and calorimeter information) and that is important to be sure all the calculations are reasonable. 


Best regards,
Andrii

Best regards,
Andrii

**Comment by Axel-Naumann** [comment] 2020-10-21 12:20
OK thanks. I believe that "there is no other way to get reliable results" is a bit of an exaggeration - many numerical libraries and programs do not turn fp exceptions on. IEEE 754 allows them to survive just fine the cases you are hunting down, because (as you certainly know) IEEE 754 brings defined behavior to "degenerate" (not in the IEEE 754 sense) cases.

As a matter of fact, I believe you have just proven to yourself that "there is no other way to get reliable results" is also incorrect, as the optimizer might change fp operations. Yes, GCC tries to keep them "fp-safe" but that might change in any of the upcoming versions, just like it did for instance for clang, the Intel compiler, and - if I remember correctly - MSVC.

Our approach is not to rely on fp exceptions but on coverage in regression tests. That has limited reach (as would fp exceptions) but it allows us to detect when results change in a visible, "unreliable" way.

Shall we close this then or is there something left to be clarified?

**Comment by andriish** [comment] 2020-10-21 13:48
Hi @Axel-Naumann ,

>IEEE 754 brings defined behavior to "degenerate" (not in the IEEE 754 sense) cases.

That is true. But does not help practically. It is better that a program (e.g. with complicated  integration) fails with FPE in 30 minutes than ends successfully in a week and delivers a well-defined result '-NaN'. Or, even worse, produces a result that looks fine but is incorrect and then user (e.g. me) will spend some days to understand where the problem is.

> as the optimizer might change fp operations. Yes, GCC tries to keep them "fp-safe" but that might change in any of the upcoming versions

As far as I understand, very formally clang did nothing wrong there, it is just GCC that tried to be a bit smarter -- in the  code I've copied from TColor  all the used constants should be in float and not in (standard) double. No FPE in this case.  
So one can blame the code, but because mixing floats and double constants is a common practice I would blame the compiler. 

>is there something left to be clarified
Ok. As far as I understood, changing the flags for the release builds is not an option, right?
If so, would a patch that assures all constants in TColor::RGB2HLS are float an acceptable solution? I can do that.


Best regards,
Andrii

**Comment by Axel-Naumann** [comment] 2020-10-21 14:02
> changing the flags for the release builds is not an option, right?

It certainly is, but we have not received any request from an experiment, and you are the first user ever to mention this :-) Given these statistics I'd prefer to keep our build system simpler rather than adding complexity, especially as you can always build your own ROOT if needed, with the flags that you prefer!

> would a patch that assures all constants in TColor::RGB2HLS are float an acceptable solution?

I'll assign this to @couet so he can decide whether that's useful!

**Comment by couet** [comment] 2020-10-21 14:11
> would a patch that assures all constants in TColor::RGB2HLS are float an acceptable solution? I can do that.

Why not, if that provides a more secure version of the method. But that's not the only one to be considered I guess:  All the XXX2YYY methods in TColor should be checked, shouldn't they ? If you provide a PR a test going with it would be also appreciated. (in core/base/test)

**Comment by andriish** [comment] 2020-10-21 15:13
Hi @Axel-Naumann , @couet 

>Given these statistics 

OK. Makes sense. 

>you can always build your own ROOT

The idea is to make things work with what you build so the people who will use that event display will avoid building ROOT and related issues. Also, I do not build "own" ROOT since many years. See no reason to do that -- there are great  binary packages in repositories and on the ROOT site.


> If you provide a PR 
Please see 

#6684

> a test going with it would be also appreciated.

Will to to add it.

Best regards,

Andrii

**Comment by Axel-Naumann** [comment] 2020-10-21 15:30
Thanks a lot, @andriish !

> so the people who will use that event display will avoid building ROOT and related issues

One last question (likely!) to understand the context: do you run the GUI with fp exceptions on in production, or is this for testing / development only?

**Comment by andriish** [comment] 2020-10-21 15:47
Hi @Axel-Naumann  ,

I would say "both".  That is an event display from ZEUS, "ported" from ROOT5/Make to ROOT6/CMake. The userbase is small, so whenever someone needs it, some smaller of greater issues arise for various reasons (e.g. ROOT/OS/compiler update)  and one has to debug them with the people who need that. No clear separation of "debug" and "production". And well, this event display is kind of small and fast, so there are no reasons to disable debug information "in production". Speed is lesser issue than correctness and stability.


Best regards,

Andrii

**Comment by Axel-Naumann** [comment] 2020-10-21 15:53
Thanks, Andrii! (And especially for your many recent contributions, much appreciated!)

**Comment by andriish** [comment] 2020-10-21 16:06
Thank you and colleagues!

**Closed** 2020-11-04 11:39 UTC
Labels: affects:master, improvement
