### ISSUE TITLE
AfterImage compilation broken with binutils 2.36

### ISSUE THREAD

**Issue by daritter** [root-project/root#7558] opened 2021-03-17 08:49 UTC
- [x] Checked for duplicates

### Describe the bug

Trying to compile root 6.24r1 with binutils 2.36 or later fails if `builtin_afterImage=ON` with the following error

```
CMake Error at .../root/AFTERIMAGE-prefix/src/AFTERIMAGE-stamp/AFTERIMAGE-build-RelWithDebInfo.cmake:49 (message):
  Command failed: 2

   'make'

  See also

    .../root/AFTERIMAGE-prefix/src/AFTERIMAGE-stamp/AFTERIMAGE-build-*.log
```

The mentioned logfiles show

```
ar: libdeps specified more than once
make[5]: *** [libAfterImage.a] Error 1
```

This is caused by a change to `ar` in [binutils 2.36](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=binutils/NEWS;hb=refs/tags/binutils-2_36) so that the "previously unused modifier l" now has a meaning. 

The fix is quite simple, one can just replace `ar clq` in the AfterImage Makefile with `ar cq`, see for example a similar problem in tightvnc: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1789948.html

### Expected behavior

Expected behavior is to compile successfully 

### To Reproduce

You need a system with binutils 2.36 installed (can be easily installed in a local prefix).

### Setup

* Ubuntu 18.04, 
* GCC 10.2,
* ROOT 6.24rc1 from https://github.com/root-project/root/archive/v6-24-00-rc1.tar.gz
* Compilation using `-Dasimage=ON -Dbuiltin_afterimage=ON`

**Comment by linev** [comment] 2021-03-17 08:55
https://github.com/root-project/root/commit/22c2423 should fix the problem.
Patch applied to master, 6.24 and 6.22 branches.
Unfortunately, 6.24rc1 is not working

**Comment by eguiraud** [comment] 2021-03-17 08:55
Duplicate of https://github.com/root-project/root/issues/7345 , should be already fixed in master and v6-24-00-patches.

**Closed by linev** 2021-03-17 08:55 UTC
Labels: bug
