### ISSUE TITLE
Can pyroot code prompt?

### ISSUE THREAD

**Issue by Esword618** [root-project/root#14427] opened 2024-01-25 04:08 UTC
### Feature description

I see that pyroot uses cppyy, but I wonder if I can use pybind11 to generate a python ROOT package, so that ROOT can have code prompts, but also very convenient.

**Comment by vepadulano** [comment] 2024-01-25 09:46
Dear @Esword618 ,

We have no experience on binding Python extensions with ROOT and pybind11. In principle, if you could abstract away the rest of ROOT maybe there could be a way to produce your own bindings for your own classes that make use of some other ROOT class internally. I would think that a nice idea to try out. If you are willing to give it a shot, let us know the results of your experiment!

I will keep the issue open in case you want to update us, otherwise we can close this :+1:

**Comment by pcanal** [comment] 2024-01-25 21:42
What would be the advantage of using `pybind11` to expose the ROOT classes to a python prompt instead of `pyroot`?  (or did I misunderstand you request).

**Comment by Esword618** [comment] 2024-01-26 01:37
At present, there is no code prompt in the code editor, but for some novices, will not use C++, but use python, then python code prompt is very important, so that you can write code more easily, do not need to go to the manual.

**Comment by vepadulano** [comment] 2024-01-29 10:07
@Esword618 ,

Do you mean just using ROOT classes within Python, or something more? Because you can already use ROOT at a Python prompt

```bash
$: python
>>> import ROOT
>>> h = ROOT.TH1F()
>>> h.FillRandom("gaus")
>>> 
```

**Comment by Esword618** [comment] 2024-01-30 13:21
If this is the case, the code prompts in vscode or pycharm and other editors, as shown below.

<img width="383" alt="image" src="https://github.com/root-project/root/assets/73058062/4f4551e9-99e8-4ebf-a36a-465ff385255b">

**Comment by vepadulano** [comment] 2024-01-31 22:31
Dear @Esword618 ,

I see what you mean now, thanks for the clarification. That feature is not available in ROOT. It would also somehow conflict with the policy of lazily loading the different parts of ROOT that happens today in PyROOT (by design). But you can let us know if you need help in understanding some parts of the codebase.

**Comment by Esword618** [comment] 2024-02-05 07:03
OK, thank you.

**Comment by dpiparo** [comment] 2024-02-05 09:14
I am closing the issue since it seems clarified. I support what @vepadulano said above, please do not hesitate to reach out to us on https://root-forum.cern.ch/ if you need support.

**Closed by dpiparo** 2024-02-05 09:14 UTC
Labels: new feature
