### ISSUE TITLE
Infinite loop in TDirectoryFile::ls

### ISSUE THREAD

**Issue by SilentAssassinMa** [root-project/root#13182] opened 2023-07-05 09:59 UTC
### Check duplicate issues.

- [x] Checked for duplicates

### Description

In this [source file](https://root.cern.ch/doc/v628/TDirectoryFile_8cxx_source.html), line 1212, should be a 
```c++
lnk = lnk->Next()
```
called before `continue`, otherwise calling `ls` with a regex input would cause a dead loop.

### Reproducer

non

### ROOT version

6.28.04

### Installation method

non

### Operating system

centos7

**Comment by jalopezg-git** [comment] 2023-07-05 10:06
Many thanks for reporting the issue, @SilentAssassinMa!  I took a quick look and it seems that you are absolutely right.

**Comment by ferdymercury** [comment] 2023-07-09 10:51
Could this maybe be a dupe of https://github.com/root-project/root/issues/8650 ?

**Comment by ferdymercury** [comment] 2023-07-09 11:22
Bug probably introduced here: https://github.com/root-project/root/commit/72a3242c91b7ca3e4cf31e7a6d5ddc9638270d27

**Closed** 2023-07-18 15:52 UTC
Labels: bug, in:I/O

**Comment by jalopezg-git** [comment] 2023-07-19 17:51
I guess #13217 should be backported to 6.28/06, no?  Will you take care of that or should I?

**Comment by pcanal** [comment] 2023-07-19 18:42
@jalopezg-git Yes, can you open a PR?

**Comment by jalopezg-git** [comment] 2023-07-19 20:06
> @jalopezg-git Yes, can you open a PR?

@ferdymercury as you are the original author of #13217, do you want to take care of the backport?

**Comment by ferdymercury** [comment] 2023-07-20 07:38
> > @jalopezg-git Yes, can you open a PR?
> 
> @ferdymercury as you are the original author of #13217, do you want to take care of the backport?

I could do it, but I have never done it before, so I need some guidelines. Should I use rebase on some XY branch and then cherry-picking only my commit or sth like that?

**Comment by jalopezg-git** [comment] 2023-07-20 10:05
> > > @jalopezg-git Yes, can you open a PR?
> > 
> > 
> > @ferdymercury as you are the original author of #13217, do you want to take care of the backport?
> 
> I could do it, but I have never done it before, so I need some guidelines. Should I use rebase on some XY branch and then cherry-picking only my commit or sth like that?

Assuming that the remote `origin` refers to upstream and `ferdymercury` to `https://github.com/ferdymercury/root/`, the simplest way is to
```bash
$ git fetch origin v6-28-00-patches:v6-28-00-patches
$ git checkout -b TDirectoryFile-ls-v6.28 v6-28-00-patches
$ git cherry-pick ... # your commit here (I think it was 2 commits)
$ git push ferdymercury TDirectoryFile-ls-v6.28
```
, and then open a PR to be merged against the `v6-28-00-patches` branch.  I'll let you try; if you don't manage, I'll do it instead :slightly_smiling_face:.

**Comment by ferdymercury** [comment] 2023-07-20 11:35
I did: (note to self)
Thanks for the help!

```
git clone git@github.com:root-project/root
cd root
git remote add ferdymercury git@github.com:/ferdymercury/root
git remote -v
ferdymercury	git@github.com:ferdymercury/root.git (fetch)
ferdymercury	git@github.com:ferdymercury/root.git (push)
origin	git@github.com:root-project/root (fetch)
origin	git@github.com:root-project/root (push)
git fetch origin v6-28-00-patches:v6-28-00-patches
git checkout -b TDirectoryFile-ls-v6.28 v6-28-00-patches
git config user.name "ferdymercury"
git config user.email "ferdymercury@users.noreply.github.com"
git cherry-pick 18c847267b8651b7b392116767c5671f14c1c46e cb08bb7445a0b8db0a64a505399844c85ed048a4
git push ferdymercury TDirectoryFile-ls-v6.28
```
