### ISSUE TITLE
Unable to build with external LLVM 9

### ISSUE THREAD

**Issue by chrisburr** [root-project/root#7176] opened 2021-02-11 16:34 UTC
When testing #6385 I've had issues with the linking order of the LLVM libs due to CMake not knowing about their dependencies. I don't have a log or reproducer to hand but this patch was enough to fix it:

https://github.com/chrisburr/root-feedstock/blob/4dff10152d66bd0e873b60150e72cf0f9bfa8c19/recipe/patches/0001-Use-find_package-for-llvm-clang.patch

The `get_directory_property` call was also an issue. That patch contains the values copied from a build with `builtin_llvm=ON`.

**Comment by Axel-Naumann** [comment] 2021-02-11 17:44
Thanks, Chris.

> That patch contains the values copied from a build with `builtin_llvm=ON`

IMHO that's fine - during the x years of cling we never had to touch those. Hard-coding those shouldn't be an issue.

**Comment by guitargeek** [comment] 2023-12-01 15:16
I'll close this expired issue. ROOT underwent some LLVM upgrade since then, so building with and external LLVM 9 anymore is not a supported case. The author of this issue also opened a PR to address this issue, but progress on this PR has also stalled. I conclude that this means the issue is also not important for the original author anymore.

@chrisburr, if you have further issues with the way you're currently building ROOT, feel free to open new issues on GitHub!

Cheers,
Jonas

**Closed by guitargeek** 2023-12-01 15:16 UTC
Labels: bug
