### ISSUE TITLE
[ROOT-10196] boundary check in TH1::AddBinContent is missing

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14575] opened 2024-02-04 18:18 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-10196

Since boundary check of TH1D::fArray is not performed in TH1D::AddBinContent, the method can cause memory issues.

 

I understand that TH1::AddBinContent is very frequently called from TH1::Fill and thus I guess the developers do not want to repeat a boundary check again in TH1::AddBinContent. But TH1::SetBinContent does a boundary check and users like me expect that TH1::AddBinContent also checks the TH1::fArray boundary.

```cpp
void test() {}
  int nbins = 500;
  TH1D* h = new TH1D("h", "", nbins, 0, nbins);

  for(int j = 0; j < 1000; j++){
     int bin = h->GetBin(500);
     for(int i = bin; i < bin + 100; i++){
       h->AddBinContent(i, 1);
     }
   }
```
```
$ root
root [0] .L test.C
root [1] for(int i = 0; i < 100; i++) test();
Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).
Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).
Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).
Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).
Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).
Warning in <TROOT::Append>: Replacing existing TH1: h (Potential memory leak).
root.exe(67870,0x10be0f5c0) malloc: Incorrect checksum for freed object 0x7fedb5190a00: probably modified after being freed.
Corrupt value: 0x408f400000000000}}{{root.exe(67870,0x10be0f5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by ferdymercury** [comment] 2024-02-05 08:12
I think this is a duplicate of https://github.com/root-project/root/issues/6671
There is a draft PR: https://github.com/root-project/root/pull/14271

But checking bin content saturation on floating variables is rather non-trivial.

**Comment by atolosadelgado** [comment] 2024-02-13 09:56
Hi,

I started to take a look to this issue: the boundary check is not performed by the `TH1` methods that access a bin, e.g., `TH1C h("h","",10,0,10); h.AddBinContent(12312312); ` and it can lead to undefined behavior (there is a piece of memory spoiled by this action).

After reading the methods of TH1S, TH1I, TH1F, TH1D that access a bin content I can say:
* Each histogram class derives from the corresponding TArray class, e.g., TH1F derives from TArrayF
* Internally, the access to the bin is done _a la C_, straight to the element of the array , e.g. `fArray[nbin]` 
* The boundary check is already implemented for the methods `TArray::operator()[]` 

A potential solution would be to use `TArray::operator()[]`, which actually check the boundary of the array. Another solution could be a simple `if` to check of the boundary without using the `TArray` features. 

It is likely that this methods `SetBin*`, `AddBin*` may be called quite often, and such boundary check could have a great impact in performance. Is there experience of such case? @lmoneta , may I ask for your advice on this issue?

Best,
Alvaro

**Comment by ferdymercury** [comment] 2024-02-13 10:06
In my opinion, we could just add an "assert" statement that is skipped in release mode; and add a note on the doxygen documentation that passing an out-of-range bin leads to undefined behavior.

**Closed** 2024-02-14 15:29 UTC
Labels: bug, fixathon
