### ISSUE TITLE
Root_x86 failed to run "roottest-cling-exception-nullderef-e test on release and debug configuration with MSVC on windows.

### ISSUE THREAD

**Issue by rachelhe123** [root-project/root#9742] opened 2022-01-28 08:45 UTC
**Describe the bug**

Root_x86 failed to run "roottest-cling-exception-nullderef-e" test on release and debug configuration with MSVC on windows. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**Expected behavior**
For Root_x86, "roottest-cling-exception-nullderef-e" test should be run pass on the windows.

**To Reproduce**
1. git clone  https://github.com/root-project/root F:\gitP\root-project\root
2. mkdir F:\gitP\root-project\root\build_x86
3. cd F:\gitP\root-project\root\build_x86
4. set PATH=%PATH:C:\Strawberry\perl\bin;=%
5. python.exe -m pip install pytest
6. cmake -G "{0}" -A {1} -DCMAKE_SYSTEM_VERSION={2} -DCMAKE_BUILD_TYPE=Release -Dtesting=ON -Droottest=ON .. 
7. set PATH=%PATH:C:\Strawberry\perl\bin;=%
8. msbuild /m /p:Platform=Win32 /p:Configuration=Debug ALL_BUILD.vcxproj /t:Rebuild
9. powershell.exe -NoProfile -ExecutionPolicy Bypass "..\..\tools\LongPathsEnabled.ps1"
10. ctest -C Release --output-on-failure -j8 -R "roottest" -E "roottest-root-meta"

**Setup**
VS 2019 + Windows Server 2019

**Additional context**
[test_release.log](https://github.com/root-project/root/files/7957119/test_release.log)

**Comment by hahnjo** [comment] 2022-01-28 15:35
Can you check that your `roottest` is up-to-date and you have https://github.com/root-project/roottest/commit/5c6d4c56f2145afc1fd32470459753efad8c95e9? There was a recent change in `master` and you need that commit or the test will fail.

**Comment by bellenot** [comment] 2022-01-31 16:27
Just tested with latest ROOT (master) and roottest (master) with both VS 2019 and VS 2022:
```
C:\Users\bellenot\build\x86\release>ctest -C Release -R roottest-cling-exception-nullderef-e
Test project C:/Users/bellenot/build/x86/release
    Start 1122: roottest-cling-exception-nullderef-e
1/1 Test #1122: roottest-cling-exception-nullderef-e ...   Passed    0.48 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
cling         =   0.48 sec*proc (1 test)
regression    =   0.48 sec*proc (1 test)
roottest      =   0.48 sec*proc (1 test)

Total Test time (real) =   1.88 sec
```
And BTW, no need to report the tests failures, we are aware of some tests filing with some versions of Visual Studio and architecture (e.g. with VS 2022 x64). And since we run  al the tests in our CI, we see immediately if something fails. Note that we are aware of some failing tests, some due to incompatibilities between VS and LLVMClang. for example, the 64 bit build of ROOT still has failures (31 tests fail out of 1948)

**Comment by bellenot** [comment] 2022-02-02 07:29
Closing this issue, since it is clarified and not reproducible.

**Closed by bellenot** 2022-02-02 07:29 UTC
Labels: bug
