### ISSUE TITLE
PyROOT: bad CPU performance for 6.27 (dev3 LCG nightly slot at cvmfs) 

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#11927] opened 2022-12-19 09:40 UTC
For my project (based on PyROOT) I regularly test it against decv LCG nightly builds.
For last days I see a significant degradation  in the CPU performance 
e.g. for the very simple simple   [script](https://gist.github.com/VanyaBelyaev/66b08ae5b974ae3a279e67ddd0ae33e8)
I see a huge factor, almost an order of magnitude, degradation CPU performance with respect to ROOT 6.24 or 6.26.
I've checked the exiting dev3 builds and I see tat while even the earliest (laet week Tue)  build is much slower than  6.24&6.26, 
but a factor of 2 in the performance comes from the last Friday build.  
Something bad happens between Thu and Fri slots... 

You can find some numbers in the comment
 to [this gist](https://gist.github.com/VanyaBelyaev/66b08ae5b974ae3a279e67ddd0ae33e8)

**Comment by vepadulano** [comment] 2022-12-19 10:05
Hi @VanyaBelyaev,
thanks for reaching out! This may be related to the recent upgrade to LLVM 13, it seems there is an unexpected slowdown with JITted code. The root cause is not known yet, but we'll make sure to test with your example script as well once we have some patch.

**Comment by VanyaBelyaev** [comment] 2022-12-19 10:08
thank you @vepadulano 
but please note that  performace for the "pre-Friday" slot is also not perfect.. It will be very good to come back to the numbers obtained with 6.26

**Comment by vepadulano** [comment] 2022-12-19 10:10
The LLVM upgrade was merged on Friday December 9th. Do you see this degradation before that date too?

**Comment by VanyaBelyaev** [comment] 2022-12-19 10:18
the first two weeks of December I've not run my tests very often.
Actually all my GitHub actions tests started to fail to due to timeout from the Friday.
And inspecting the overall CPU time for all tests, I do not see large steps/peaks  
around December 8 for my [tests](https://github.com/OstapHEP/ostap/actions?page=2)

**Comment by vgvassilev** [comment] 2022-12-21 06:45
Can you provide a Flamegraph or anything that hints us where to look?

**Comment by Axel-Naumann** [comment] 2022-12-21 06:54
FYI I'm on it, I will continue after the break early 2023. It currently seems to be a combination of slower jitting and missing optimization, I am working on fixing the latter today. We saw these effects also in our own benchmarks.

**Comment by VanyaBelyaev** [comment] 2022-12-21 07:37
@Axel-Naumann 
I have one relatively small  [module](https://github.com/OstapHEP/ostap/blob/master/ostap/core/core.py) , that loads many native ROOT classes and many my own C++ classes and then performs some  "decoration" for these classes - no loops, no CPU expensive data manipulations. It takes 3s with  ROOT 6.26 (LCG_102 release) and 190s with  ROOT 6.27 (dev3 LCG nightly slot). It demonstrates the scale of the problem (and probably indirectly indicates the source of it)

**Comment by Axel-Naumann** [comment] 2022-12-21 08:12
I cannot reproduce this :-/ I'm looking at ROOT just-before-the-llvm-upgrade (I do realize that you detected a perf regression also wrt to that - but let's focus on the llvm upgrade first) and ROOT right after, in a release-with-debug build, running
```
time python3 ./tst100.py
```
For user CPU time I get 2.60s for llvm9 and 2.69s for llvm13. So indeed it would be good to have flamegraphs from you - or anything like that (callgrind,...).

@VanyaBelyaev could you update your sentence from the [first post](https://github.com/root-project/root/issues/11927#issue-1502617659)

>  but about of factor of 2 in performance comes from the of 2 of this difference that comes the Friday build.

I guess I know what you mean but I'd like to make sure :-)

**Comment by VanyaBelyaev** [comment] 2022-12-21 08:28
@Axel-Naumann 
In case simple `-m profile` can be helpful:

```
( lb-set-platform x86_64-centos7-gcc11-opt ;  source /cvmfs/sft.cern.ch/lcg/views/LCG_102/${CMTCONFIG}/setup.sh ; echo $ROOTSYS ; time python -m profile ./tst100.py | tee root626.txt) 
... 
real	0m14.144s
user	0m10.412s
sys	0m2.730s

( lb-set-platform x86_64-centos7-gcc12-opt ;  source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/${CMTCONFIG}/setup.sh ; echo $ROOTSYS ; time python -m profile ./tst100.py | tee root627.txt  )
...

real	0m45.779s
user	0m36.429s
sys	0m4.734s

```
output files:  
 [root626.txt](https://gist.github.com/VanyaBelyaev/17884a2fb55deea182d27fe1b3076c70)
 [root627.txt](https://gist.github.com/VanyaBelyaev/c8bc792ead4f2a76c08edb0392046211)

**Comment by VanyaBelyaev** [comment] 2022-12-21 08:40
For  completeness  dev3/Fri vs dev3/Thu

```
( lb-set-platform x86_64-centos7-gcc12-opt ;  source /cvmfs/sft.cern.ch/lcg/views/dev3/Fri/${CMTCONFIG}/setup.sh ; echo $ROOTSYS ; time python -m profile ./tst100.py | tee root627_friday.txt  
...
real	0m45.976s
user	0m36.305s
sys	0m5.073s

( lb-set-platform x86_64-centos7-gcc12-opt ;  source /cvmfs/sft.cern.ch/lcg/views/dev3/Thu/${CMTCONFIG}/setup.sh ; echo $ROOTSYS ; time python -m profile ./tst100.py | tee root627_thursday.txt  )
...

real	0m31.001s
user	0m12.790s
sys	0m4.830s

```

this time no factor of 2, but 1.5 

[log-files](https://gist.github.com/VanyaBelyaev/0e55d321d554af63b56b8f881804e7eb)

but much more impoirtant for me - that  [GitHub Action](https://github.com/OstapHEP/ostap/actions)  tests for my real project clearly show  a jump in bad direction fo rCPU perfoemance - from something a bit smaller than 2 hours to something exceedig 6 hours with fails due to timeover

**Comment by Axel-Naumann** [comment] 2022-12-21 09:40
I completely believe that you're seeing this - all I'm saying is that I don't know how to reproduce this, so we'll need your help here. The Python profiles don't help because the slow-down is in the C++ world. You can e.g. run [callgrind (see "CPU Profiling")](https://root-forum.cern.ch/t/valgrind-and-root/28506) and share the output.

**Comment by VanyaBelyaev** [comment] 2022-12-21 12:45
thank you, @Axel-Naumann 
it will take some time for me and likely I will be able to do it only in January.

**Comment by VanyaBelyaev** [comment] 2023-01-23 07:26
after very long pause (sorry), I've rerun my tests  with dev3 LCG nightly slot and I see that performance is close  to values  from the start of December. Likely the the problem is solved and the issue can be closed.

**Comment by Axel-Naumann** [comment] 2023-01-23 08:18
Phew. Thanks, Vanya!

**Closed by Axel-Naumann** 2023-01-23 08:18 UTC
