### ISSUE TITLE
Bitdefender found a virus in WIN64 version of Root 6.26

### ISSUE THREAD

**Issue by giamas** [root-project/root#11473] opened 2022-10-01 14:30 UTC
Unfortunately I can't install Win64 version of Root 6.26 becasue of virus detection. See error during unzip and Btdefender report

![error1](https://user-images.githubusercontent.com/75624059/193414303-f5b7d9c8-4837-431d-b7e2-e7f04c94e34b.JPG)
![error2](https://user-images.githubusercontent.com/75624059/193414309-ece88fe7-b75c-47ce-ac39-620b567ba7b3.JPG)

**Comment by jalopezg-r00t** [comment] 2022-10-04 08:14
Hi @giamas,

that's most likely caused by something in your environment (as opposed to ROOT proper).  However, I'm assigning @bellenot so that he can confirm, just in case.

Cheers,
Javier.

**Comment by bellenot** [comment] 2022-10-04 08:15
Hi @giamas , this is most probably a false positive. We had this kind of issue in the past. See [this virustotal result](https://www.virustotal.com/gui/file/ea73818f7868f9e092db33a3a356041179f362ec7bb70d917429a92d0a679b7a)

**Comment by bellenot** [comment] 2022-10-18 07:10
A [new analysis](https://www.virustotal.com/gui/file/ea73818f7868f9e092db33a3a356041179f362ec7bb70d917429a92d0a679b7a?nocache=1) only has one false positive. Closing this issue

**Closed by bellenot** 2022-10-18 07:10 UTC
Labels: priority:default
