### ISSUE TITLE
root macOS libc++abi issue

### ISSUE THREAD

**Issue by fliu8788** [root-project/root#13002] opened 2023-06-13 10:22 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Describe the bug

When I tried to run TMVA test code with the follow errors

root [0] 
Processing TMVA_Higgs_Classification.C...
<FATAL>                         : Can't import __main__
***> abort program execution
libc++abi: terminating due to uncaught exception of type std::runtime_error: FATAL error

macOS 13.4, M1, root 6.28.04, any solution? thanks. 

### What is the expected behaviour?

run TMVA tutorial code on macOS M1 it reported an error about libc++abi exceptions

### How to reproduce?

root $ROOTSYS/tutorials/tmva/TMVA_Higgs_Classification.C 
on macOS 13.4 M1  processor.

### ROOT version

6.28.04

### How did you install ROOT?

download from root.cern.ch

### Which operating system are you using?

macOS 13.4

**Comment by hahnjo** [comment] 2023-06-14 08:40
might be related to https://github.com/root-project/root/issues/7541 - the question is: is the test code supposed to throw exceptions (from / through interpreted code)?

**Comment by hansenjo** [comment] 2023-06-16 16:27
I have the same/similar issue. ROOT 6.28.04 installed from source, macOS 13.4, Xcode 14.3.1, MacBook Pro with Intel i9-9880H. Running TMVA tests in the build directory, I get

```
$ ctest --output-on-failure -R TMVA-DNN-MethodDL-SGD-Optimization-Cpu
Test project /Users/ole/Develop/BUILD/ROOT/6.28.04b
    Start 357: TMVA-DNN-MethodDL-SGD-Optimization-Cpu
1/1 Test #357: TMVA-DNN-MethodDL-SGD-Optimization-Cpu ...***Failed    0.61 sec
Testing Method DL with SGD Optimizer for CPU backend:
libc++abi: __cxa_guard_acquire detected recursive initialization
CMake Error at /Users/ole/Develop/BUILD/ROOT/root-6.28.04/cmake/modules/RootTestDriver.cmake:232 (message):
  error code: Subprocess aborted

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.74 sec

The following tests FAILED:
	357 - TMVA-DNN-MethodDL-SGD-Optimization-Cpu (Failed)
Errors while running CTest
```

When running all the TMVA tests:
```
$ ctest -R "^TMVA" -j6
...
81% tests passed, 7 tests failed out of 36

Total Test time (real) =  10.47 sec

The following tests FAILED:
	357 - TMVA-DNN-MethodDL-SGD-Optimization-Cpu (Failed)
	358 - TMVA-DNN-MethodDL-Adam-Optimization-Cpu (Failed)
	359 - TMVA-DNN-MethodDL-Adagrad-Optimization-Cpu (Failed)
	360 - TMVA-DNN-MethodDL-RMSProp-Optimization-Cpu (Failed)
	361 - TMVA-DNN-MethodDL-Adadelta-Optimization-Cpu (Failed)
	362 - TMVA-DNN-Regression-Cpu (Failed)
	376 - TMVA-DNN-GRU-Backward-Cpu (Failed)
Errors while running CTest
```
All these failing tests abort with "libc++abi: __cxa_guard_acquire detected recursive initialization".

The TMVA.* tests pass without any issue on a different system: ROOT 6.28.04 installed from source (exact same configuration as the installation with errors mentioned above), macOS 11.7.7, Xcode 13.2.1, Intel  i7-10700K.

Seems to be related to the newer libc++ on the macOS 13.4/Xcode 14 system.

**Comment by dpiparo** [comment] 2023-11-30 09:09
Dear @hansenjo, thanks for reporting this issue. This seems to be a mismatch between the XCode on the machine and the one used for building ROOT binaries. Presently, we are unable to reproduce the issue and by now apple clang moved to version 15. I am closing this issue but feel free to re-open it if this is still a problem for you.

**Closed by dpiparo** 2023-11-30 09:09 UTC
Labels: bug
