### ISSUE TITLE
[MSVC] Root is failed with error G694476FC: static_assert failed "Unexpected size"

### ISSUE THREAD

**Issue by NEIL-smtg** [root-project/root#15321] opened 2024-04-24 07:53 UTC
### Check duplicate issues.

- [x] Checked for duplicates

### Description

We've been using MSVC to build ROOT, and we've recently encountered the following error:

`error G694476FC: static_assert failed "Unexpected size"`

Our developer has suggested the compiler that was used needs to implement the Defect Report https://cplusplus.github.io/CWG/issues/2518.html (which has been implemented by MSVC and Clang).

### Reproducer

Repro step:

1. Open "x64 Native Tools Command Prompt for VS 2022"
2. git clone https://github.com/root-project/root.git
3. mkdir root\build_amd64
4. cd /d root\build_amd64
5. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
6. python.exe -m pip install pytest 2>&1
7. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -Dtesting=ON -Droottest=ON -Droofit=off .. 2>&1
8. msbuild /m /p:Platform=x64 /p:Configuration=Release ALL_BUILD.vcxproj /t:Rebuild 2>&1

### Expected result:
Build succesfully.

### ROOT version

We are using the latest commit.

### Installation method

git

### Operating system

Windows server 2022 data center

### Additional context

Detailed log:
[Build.log](https://github.com/root-project/root/files/15090474/Build.log)

**Comment by bellenot** [comment] 2024-04-25 11:58
So I cannot reproduce the error with the recipe you give. But looking at you log file, I see you set more environment variables. That is:
```
set _CL_= /Bcapture_repro C:\a\_work\_temp\rwc_project_logs\ROOT\preprocessed_repro_build & set _LINK_= /onfailrepro:C:\a\_work\_temp\rwc_project_logs\ROOT\link_repro_build
```
Without those variables the build works just fine. This is maybe related to https://github.com/root-project/root/issues/9445

**Comment by StephanTLavavej** [comment] 2024-04-25 19:15
Neil omitted an important bit of info - this involves a very recent change to MSVC's STL, https://github.com/microsoft/STL/pull/4591 . To reproduce it, you'll either have to build and consume our open-source STL, or wait for VS 2022 17.11 Preview 2 to ship (which will contain this commit). We changed the STL to say `static_assert(false)` instead of `static_assert(_Always_false<SomeType>)`.

**Comment by StephanTLavavej** [comment] 2024-04-26 15:19
Correct. To fix this, implement [CWG-2518](https://cplusplus.github.io/CWG/issues/2518.html) in Cling (if that's the tool that's emitting this error), allowing `static_assert(false)` to work in templates. MSVC and Clang have already implemented this Core DR.

**Comment by pcanal** [comment] 2024-04-26 19:24
> Clang have already implemented this Core DR.

Do you happen to know which version this appeared in? (Or better yet which Merge Request added it).  Cling uses `Clang` underneath; currently version 16; Moving the Clang version used is a long process but backporting a narrow Merge Request might be possible.

**Comment by StephanTLavavej** [comment] 2024-04-27 23:32
It shipped in Clang 17, which is the version that microsoft/STL currently requires. https://clang.llvm.org/cxx_dr_status.html documents this.

I *believe* that https://github.com/llvm/llvm-project/commit/00e2098bf49f0ed45b3b8c22894cd3ac9a530e0f implemented it, but there's a slight chance there were followup commits that I'm unaware of.

**Comment by bellenot** [comment] 2024-04-29 07:20
OK, thanks a lot for the information! And since it's in Clang/Cling, let's add @vgvassilev in the loop...

**Comment by vgvassilev** [comment] 2024-04-29 07:39
We probably should backport this commit. @hahnjo what do you think?

**Comment by hahnjo** [comment] 2024-04-29 07:49
Probably, but I'm a bit confused about the error message: Why would Cling output MSVC style error messages?

**Comment by StephanTLavavej** [comment] 2024-04-30 04:09
I don't actually know what the G694476FC error code is (the only codes I recognize are MSVC Cnnnn, IntelliSense Ennnn, and Clang named warnings/errors), but the "Unexpected size" is coming from the STL. We have `static_assert(false, "Unexpected size")` in a template, and after the DR resolution, we expect that this should be activated only when that `if constexpr` branch is actually taken.

**Comment by hahnjo** [comment] 2024-05-07 12:31
> I _believe_ that [llvm/llvm-project@00e2098](https://github.com/llvm/llvm-project/commit/00e2098bf49f0ed45b3b8c22894cd3ac9a530e0f) implemented it, but there's a slight chance there were followup commits that I'm unaware of.

Seems reasonable and applies cleanly to our LLVM 16 - I opened https://github.com/root-project/root/pull/15437 with the backport. I will wait for confirmation that this is all we need before syncing to our LLVM monorepo fork and eventually merging.

**Comment by hahnjo** [comment] 2024-06-05 06:59
Fixed by https://github.com/root-project/root/pull/15437, backport to v6.32 via https://github.com/root-project/root/pull/15753

**Closed by hahnjo** 2024-06-05 06:59 UTC
Labels: bug, in:Cling
