### ISSUE TITLE
can't compile RNTupleDS

### ISSUE THREAD

**Issue by ynikitenko** [root-project/root#13103] opened 2023-06-26 19:34 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When building ROOT from source, I got an error:

```
/opt/root/src/tree/dataframe/src/RNTupleDS.cxx: In member function ‘virtual const ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations& ROOT::Experimental::Internal::RRDFCardinalityField::GetColumnRepresentations() const’:
/opt/root/src/tree/dataframe/src/RNTupleDS.cxx:78:25: error: ‘kSplitIndex64’ is not a member of ‘ROOT::Experimental::EColumnType’; did you mean ‘kSplitIndex32’?
   78 |          {{EColumnType::kSplitIndex64}, {EColumnType::kIndex64}, {EColumnType::kSplitIndex32}, {EColumnType::kIndex32}},
      |                         ^~~~~~~~~~~~~
      |                         kSplitIndex32
/opt/root/src/tree/dataframe/src/RNTupleDS.cxx:78:55: error: ‘kIndex64’ is not a member of ‘ROOT::Experimental::EColumnType’; did you mean ‘kIndex32’?
   78 |          {{EColumnType::kSplitIndex64}, {EColumnType::kIndex64}, {EColumnType::kSplitIndex32}, {EColumnType::kIndex32}},
      |                                                       ^~~~~~~~
      |                                                       kIndex32
/opt/root/src/tree/dataframe/src/RNTupleDS.cxx:79:12: error: no matching function for call to ‘ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations::RColumnRepresentations(<brace-enclosed initializer list>, <brace-enclosed initializer list>)’
   79 |          {});
      |            ^
In file included from /opt/root/src/tree/dataframe/src/RNTupleDS.cxx:19:
/opt/root/install/include/ROOT/RField.hxx:111:7: note: candidate: ‘ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations::RColumnRepresentations(const TypesList_t&, const TypesList_t&)’
  111 |       RColumnRepresentations(const TypesList_t &serializationTypes, const TypesList_t &deserializationExtraTypes);
      |       ^~~~~~~~~~~~~~~~~~~~~~
/opt/root/install/include/ROOT/RField.hxx:111:49: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations::TypesList_t&’ {aka ‘const std::vector<std::vector<ROOT::Experimental::EColumnType> >&’}
  111 |       RColumnRepresentations(const TypesList_t &serializationTypes, const TypesList_t &deserializationExtraTypes);
      |                              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/opt/root/install/include/ROOT/RField.hxx:110:7: note: candidate: ‘ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations::RColumnRepresentations()’
  110 |       RColumnRepresentations();
      |       ^~~~~~~~~~~~~~~~~~~~~~
/opt/root/install/include/ROOT/RField.hxx:110:7: note:   candidate expects 0 arguments, 2 provided
/opt/root/install/include/ROOT/RField.hxx:107:10: note: candidate: ‘ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations::RColumnRepresentations(const ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations&)’
  107 |    class RColumnRepresentations {
      |          ^~~~~~~~~~~~~~~~~~~~~~
/opt/root/install/include/ROOT/RField.hxx:107:10: note:   candidate expects 1 argument, 2 provided
/opt/root/install/include/ROOT/RField.hxx:107:10: note: candidate: ‘ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations::RColumnRepresentations(ROOT::Experimental::Detail::RFieldBase::RColumnRepresentations&&)’
/opt/root/install/include/ROOT/RField.hxx:107:10: note:   candidate expects 1 argument, 2 provided
make[2]: *** [tree/dataframe/CMakeFiles/ROOTDataFrame.dir/build.make:524: tree/dataframe/CMakeFiles/ROOTDataFrame.dir/src/RNTupleDS.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:36193: tree/dataframe/CMakeFiles/ROOTDataFrame.dir/all] Error 2
```

No header inclusion helped; it's really strange why 32 bit fields from the very same structure (enumeration) are visible, and 64 are not...
Had to comment out 

> // {EColumnType::kSplitIndex64}, {EColumnType::kIndex64},

### Reproducer

Clone ROOT repository, go to the build directory,

    cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_INSTALL_PREFIX=../install ../src
    cmake --build . -- install -j4

### ROOT version

Most recent ROOT version from the master branch at that time.

commit https://github.com/root-project/root/commit/870618f1bfa43376c73bc07fa4becc0a54caa9ed (HEAD -> master, origin/master, origin/HEAD)

### Installation method

built from source

### Operating system

Arch Linux

### Additional context

Had several problems while installing ROOT from source today (submitted bugs). Hope this is not because of my own system.

**Comment by guitargeek** [comment] 2023-06-26 22:38
Duplicate of https://github.com/root-project/root/issues/13101.

**Closed by guitargeek** 2023-06-26 22:38 UTC
Labels: bug
