### ISSUE TITLE
THStack behaviour is not aligned with behaviour of other objects when drawing - TopMargin is non-zero

### ISSUE THREAD

**Issue by edbird** [root-project/root#6642] opened 2020-10-14 16:09 UTC
Please see

https://root-forum.cern.ch/t/thstack-what-is-the-correct-way-to-set-the-y-axis-limits/41851/12

In short,

THStack appears to have a default non-zero value of "SetTopMargin"

whereas other objects have default value of zero. (TH2D for example)

**Comment by couet** [comment] 2020-10-15 12:34
Completely different thing and normal behaviour as the zoom on the Y axis for TH1 is done using SetMinimum() and SetMaximum()

**Comment by couet** [comment] 2020-10-15 12:36
@etejedor it is not a bug strictly speaking as @edbird is asking for a behavior change which sound reasonable. I am looking into it.

**Comment by couet** [comment] 2020-10-15 14:01
Fixed by https://github.com/root-project/root/pull/6649

**Closed** 2020-10-15 14:02 UTC
Labels: in:Graphics
