### ISSUE TITLE
std::source_location not found when running with c++20 enabled

### ISSUE THREAD

**Issue by ktf** [root-project/root#14601] opened 2024-02-06 12:58 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

See the reproducer. Despite ROOT is able to find the header (i.e. `#include <source_location>` works) it fails to find `std::source_location` in the namespace and fails with:

```
In file included from input_line_8:1:
/Users/ktf/src/sw/BUILD/892abf24b97cb0ff623b7a495dedcfb95e9c6445/O2Physics/foo.C:5:8: error: no type named 'source_location' in namespace 'std'
  std::source_location loc = std::source_location::current();
  ~~~~~^
/Users/ktf/src/sw/BUILD/892abf24b97cb0ff623b7a495dedcfb95e9c6445/O2Physics/foo.C:5:35: error: no member named 'source_location' in namespace 'std'
  std::source_location loc = std::source_location::current();
                             ~~~~~^
```

### Reproducer

Just put the following in `foo.C` and then run with `root.exe foo.C`.

```C++
#include <source_location>
#include <iostream>

int foo() {
  std::source_location loc = std::source_location::current();
  std::cout << "File: " << loc.function_name() << std::endl;
  return 0;
}
```

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.30/01                        https://root.cern |
  | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on Jan 26 2024, 10:35:25                   |
  | From tags/v6-30-01-alice2@v6-30-01-2-g526782cfe8                 |
  | With Apple clang version 15.0.0 (clang-1500.1.0.2.5)             |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

aliBuild

### Operating system

macOS

**Comment by hahnjo** [comment] 2024-02-06 13:25
Correct, this is a duplicate of https://github.com/root-project/root/issues/12993. The short summary of https://github.com/root-project/root/issues/12993 is that LLVM 13 in ROOT 6.30 didn't implement `__builtin_source_location`. It works after the upgrade to LLVM 16 that is not yet in a ROOT release.

**Closed by hahnjo** 2024-02-06 13:25 UTC
Labels: bug

**Comment by ktf** [comment] 2024-02-06 13:39
Apologies. I did search for `std::source_location` but apparently I mistyped it, as I got no results.
