### ISSUE TITLE
Suspicious behavior of TUnuran::SampleMulti 

### ISSUE THREAD

**Issue by DingXuefeng** [root-project/root#10222] opened 2022-03-24 02:31 UTC
- [x] Checked for duplicates

### Describe the bug

It seems that to sample a N-dimensional vector, we need to call this method N times.

See log file:
```
for (int j = 0; j < 20000; j++) {
    hzmodel.Sample(&flux_real[0]);
    if(j<10)
    std::cout<<j<<" "<<flux_real[0]<<" "<<flux_real[1]<<" "<<flux_real[2]<<std::endl;
```
output

```
1 5.73992 4.99711 4.88
2 5.73992 4.99711 5.26624
3 5.72944 4.99459 5.25179
4 5.34123 4.99459 5.25179
5 5.34123 4.96792 5.25179
6 5.34123 4.96792 5.2696
7 5.26477 4.99232 5.52042
8 5.59451 4.99232 5.52042
9 5.59451 5.04631 5.52042
```

### Expected behavior

By calling `SampleMulti`, all components should be randomized.

### To Reproduce

try [ROOT tutorial](https://root.cern/doc/master/unuranDemo_8C.html)

### Setup

tested on 
ubuntu 20.04 + ROOT v6.26.00 (wget)
ubuntu 20.04 + ROOT v6.24.06 (wget)
MacOS 10.15 + ROOT v6.26.00 (brew)

### Additional context

N/A

**Comment by DingXuefeng** [comment] 2022-03-27 02:47
It seems deeper problems exists. In my study, I need to sample a 3D multi-variate gaussian distribution. For comparison, I set correlation to zero, so that I can simply sample three independent variables. The results using unuran and the one using three indepent variables are incompatible, even with above mentioned dirty fix.

Currently I switch to alternative methods, yet it might be useful to understand what is the problem.

I think some unit test and integration test should be implemented.

**Comment by lmoneta** [comment] 2022-09-19 15:10
The problem is that the default method Unuran uses for multi-dimensional distribution (`hitro`)  is based on Markov-Chain MC so it is expected to observe this behaviour if you look at the single events, instead, you should use at the generated obtained distribution. See for example https://search.r-project.org/CRAN/refmans/Runuran/html/hitro.new.html
If you switch unuran (in the `TUnuran::Init`) to use the method `vnrou` then it will be fine when looking at the single events generated.  
Before closing this issue, I think we need to improve the documentation in `TUnuran` for this.

**Closed** 2024-03-08 12:58 UTC
Labels: bug, in:Math Libraries, affects:6.26, fixathon
