### ISSUE TITLE
Windows CI runs roottest despite build failure

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#6441] opened 2020-09-24 16:05 UTC
roottest / testing should not be done if the build failed.

**Comment by dpiparo** [comment] 2024-02-02 14:25
Is this a "Won't fix" because of this cause de force majeure?

**Comment by bellenot** [comment] 2024-02-02 14:43
I guess so, but I can cross-check again...

**Comment by pcanal** [comment] 2024-02-02 20:31
Is there an possible work-around? (for example create a special file is case of success and check for that in lieu of the error code of the script)

**Comment by dpiparo** [comment] 2024-03-16 11:44
I would favour that: @bellenot would that be possible?

**Comment by bellenot** [comment] 2024-03-16 13:57
I think this was on Jenkins only, so not valid anymore with the new CI. To be confirmed

**Comment by dpiparo** [comment] 2024-04-24 12:43
Can this be confirmed, e.g. with a PR that make the build fail (e.g. invalid c++ in a random file)? It would be nice to close this item.

**Comment by bellenot** [comment] 2024-04-24 15:27
So this is confirmed by PR #15327: This issue was for Jenkins and not relevant anymore with the new CI, therefore I close this issue.

**Closed by bellenot** 2024-04-24 15:27 UTC
Labels: bug, in:Build System
