### ISSUE TITLE
SofieCompileModels_PyTorch fails to compile on old Torch versions

### ISSUE THREAD

**Issue by egpbos** [root-project/root#9079] opened 2021-10-06 19:01 UTC
- [x] Checked for duplicates

### Describe the bug
During compilation, I get the following error:
```
[6/20] Running utility command for SofieCompileModels_PyTorch
Torch Version: 1.7.0
RecursiveScriptModule(
  original_name=Model
  (fc1): RecursiveScriptModule(original_name=Linear)
  (relu): RecursiveScriptModule(original_name=ReLU)
)
RecursiveScriptModule(
  original_name=Model
  (fc1): RecursiveScriptModule(original_name=Linear)
  (relu): RecursiveScriptModule(original_name=ReLU)
)
libc++abi: terminating with uncaught exception of type std::runtime_error: TMVA::SOFIE - Parsing PyTorch node onnx::Shape is not yet supported 
/bin/sh: line 1: 21308 Abort trap: 6           ./emitFromPyTorch
```

### Expected behavior
I expect this to just compile. I believe the problem may lie with the PyTorch version I had installed, 1.7.0. CMake should detect the version and disable incompatible tests. Indeed, installing PyTorch 1.9.1 makes the problem go away.

### To Reproduce
Install PyTorch 1.7.0 with conda or pip, make sure it's in your PATH so CMake detects it, and build the `SofieCompileModels_PyTorch` target.

### Setup
1. ROOT version: master
2. Operating system: macOS 11.6
3. How you obtained ROOT: built it myself

**Comment by guitargeek** [comment] 2024-04-05 00:54
Sorry that we never addressed this, but it seems to me the issue is not relevant anymore. When I grep in the repo for `SofieCompileModels`, I can't find `SofieCompileModels_PyTorch`.

Feel free to open a new issue if this is relevant to you, but I will close this one as "timed out". Also because it is related to a PyTorch version that is probably not in use anymore. Sorry again!

**Closed by guitargeek** 2024-04-05 00:54 UTC
Labels: bug, in:TMVA
