### ISSUE TITLE
`root-config` fails if spaces are part of `ROOTSYS` path

### ISSUE THREAD

**Issue by olifre** [root-project/root#10759] opened 2022-06-14 20:54 UTC
- [x] Checked for duplicates

### Describe the bug
The `root-config` script fails in several ways when located in a `PATH` containing spaces. 

### Expected behavior
No errors when there are spaces in the path. 

### To Reproduce
```
mkdir foo\ bar
cd foo\ bar
wget https://root.cern/download/root_v6.26.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
tar xf root_v6.26.04.Linux-ubuntu18-x86_64-gcc7.5.tar.gz
source root/bin/thisroot.sh                             
/home/me/foo bar/root/bin/root-config: line 26: [: too many arguments
/home/me/foo bar/root/bin/root-config: line 26: [: too many arguments
/home/me/foo bar/root/bin/root-config: line 31: [: too many arguments
```
It also affects other output (as expected):
```
$ root-config --incdir                                                         
/home/me/foo bar/root/bin/root-config: line 26: [: too many arguments
/home/me/foo bar/root/bin/root-config: line 26: [: too many arguments
/home/me/foo bar/root/bin/root-config: line 31: [: too many arguments
/home/me ./include
```
and:
```
$ root-config --version
/home/me/foo bar/root/bin/root-config: line 26: [: too many arguments
/home/me/foo bar/root/bin/root-config: line 26: [: too many arguments
/home/me/foo bar/root/bin/root-config: line 31: [: too many arguments
/home/me/foo bar/root/bin/root-config: line 553: test: /home/me: binary operator expected
cannot read /home/me
./include/RVersion.h
```

### Setup
1. ROOT: versions: seen with 6.14, 6.26, likely others
2. Operating system: any Linux-based system (seen with Ubuntu in WSL, Gentoo)

### Additional context
While spaces in paths are always nasty, this case was reported by a student of mine (who extracted the tarball in a subdirectory with spaces).

**Comment by eguiraud** [comment] 2022-06-15 13:50
Duplicate of https://github.com/root-project/root/issues/7311 ?

**Comment by eguiraud** [comment] 2022-06-15 16:05
Ah no, in my cursory read I missed that important difference. Let's leave this open then, thank you for the report

**Comment by andresailer** [comment] 2022-07-18 08:58
Hi @bellenot 
Mostly a heads-up, but the quotes are causing issues in some autoconf macros for two packages in the LCG stack. E.g., http://cdash.cern.ch/viewFiles.php?buildid=1779881
Cheers,
Andre

**Comment by andresailer** [comment] 2022-07-18 09:07
@bellenot Sorry, I accidentally added a 1 to the link, fixed in above message

**Comment by bellenot** [comment] 2022-07-18 09:10
@andresailer thanks! So I guess I'll revert that commit...

**Comment by andresailer** [comment] 2022-07-18 16:08
Thanks, but, this is not fixing the problem for the packages. They use the root-config options `--cflags` and `--glibs`.

**Comment by bellenot** [comment] 2022-07-19 06:49
@andresailer it looks like it works: http://cdash.cern.ch/buildSummary.php?buildid=178155. Or did I miss something?

**Comment by andresailer** [comment] 2022-07-19 07:06
Dev3 is still failing the same as before, http://cdash.cern.ch/viewFiles.php?buildid=178184

**Comment by bellenot** [comment] 2022-07-19 07:09
OK, thanks. Then I'll revert it completely, and we'll then forbid spaces in `ROOTSYS` on Linux and Mac...

**Comment by bellenot** [comment] 2022-07-19 07:14
@andresailer BTW, how can I try quickly without having to wait the next LCG build?

**Comment by andresailer** [comment] 2022-07-19 07:23
Easiest I can think off is described here:
https://lcgdocs.web.cern.ch/lcgdocs/tasks/newstackpackages/#working-from-build-node
Before running `cmake` switch to the branch you want to test ROOT for in `lcgcmake/cmake/toolchain/heptools-dev3.cmake` switch to the ROOT branch you want to test.
then `make mctester` or `make hepmcanalysis`

**Comment by bellenot** [comment] 2022-07-19 07:24
OK, thanks, I'll try

**Comment by bellenot** [comment] 2022-07-19 07:33
OK, doesn't work. I'll find another solution

**Comment by bellenot** [comment] 2022-07-19 07:53
@andresailer [this PR](https://github.com/root-project/root/pull/10987) should fix the LCG builds and still fix this current issue. We'll see at next build...

**Comment by bellenot** [comment] 2022-07-20 06:24
@andresailer please let me know if it works now, so I can backport the fix in v6-26-00-patches. Thanks!

**Comment by andresailer** [comment] 2022-07-20 07:55
Yes, dev3 is working again! Thanks!

**Comment by bellenot** [comment] 2022-07-20 07:58
Cool, thanks!

**Comment by bellenot** [comment] 2022-07-20 12:41
Fixed in master and v6-26-00-patches

**Closed by bellenot** 2022-07-20 12:41 UTC
Labels: bug, in:Build System
