### ISSUE TITLE
Standalone ROOT scripts require X

### ISSUE THREAD

**Issue by ntadej** [root-project/root#13922] opened 2023-10-23 14:34 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

Standalone ROOT scripts such as `rootls` require X server in the 6.28 series. Also some other PyROOT-based scripts started to require it which indicates a core change in one of the calls or the treatment of batch running has changed.

### Reproducer

1. SSH on a Linux machine from a macOS.
2. Setup LCG view with the latest ROOT
```
lsetup "views LCG_104b x86_64-el9-gcc13-opt"
```
3. Inspect any file with `rootls`.
4. X will spawn although it should not.

### ROOT version

6.28.8 (from LCG 104b)

### Installation method

LCG

### Operating system

Linux via SSH on macOS

**Comment by couet** [comment] 2023-10-31 15:58
I just installed ROOT master (6.31/01) on an Ubuntu machine:
```
Linux root-ubuntu-2004-3 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
I am logged on it from a Mac via `ssh`.
`rootls` gives:
```
$ rootls ./tutorials/hsimple.root
hprof  hpx  hpxpy  ntuple
```
and the X server is not spawned.

**Comment by dpiparo** [comment] 2024-02-05 09:30
@andresailer do you have a hint for us?

**Comment by andresailer** [comment] 2024-02-05 09:59
@dpiparo I cannot reproduce the issue. (What does "X" spawn mean? A window pops up?)
(To be more precise: my colleague with a mac cannot) Can you reproduce the issue?

```
ssh lxplus
source /cvmfs/sft.cern.ch/lcg/views/LCG_104b/x86_64-el9-gcc13-opt/setup.sh
rootls some/path/to/a/file.root
```

@ntadej: Does it still happen with 104d (delta)?

Could it be some magic behind `lsetup`?

**Comment by dpiparo** [comment] 2024-02-06 08:59
Thanks @andresailer . Since also @couet commented last October I propose to close the issue and invite @ntadej to re-open in case this is still a problem and we can help with it at the ROOT level.

**Closed by dpiparo** 2024-02-06 08:59 UTC
Labels: bug
