### ISSUE TITLE
Assertion exception including header file with GaudiPython module

### ISSUE THREAD

**Issue by peremato** [root-project/root#7950] opened 2021-04-21 13:45 UTC
### Describe the bug
Importing `GaudiPython` module with current master version of [Py]ROOT produces exception and program crash. 

### To Reproduce
```
$ source /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc9-dbg/setup.sh
$ python -c 'import GaudiPython'
```
produces:
```
# setting LC_ALL to "C"
In file included from GaudiPythonDict dictionary payload:71:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/GaudiKernel/Chrono.h:22:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/GaudiKernel/ChronoEntity.h:19:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/GaudiKernel/StatEntity.h:12:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/Gaudi/Accumulators.h:14:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/Gaudi/MonitoringHub.h:15:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/nlohmann/json.hpp:49:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/nlohmann/adl_serializer.hpp:5:
In file included from /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/nlohmann/detail/conversions/from_json.hpp:18:
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/nlohmann/detail/meta/type_traits.hpp:11:10: fatal error: cannot open file '/build/jenkins/workspace/lcg_nightly_pipeline/install/dev3/jsonmcpp/3.9.1/x86_64-centos7-gcc9-dbg/include/nlohmann/json_fwd.hpp': No such file or directory
#include <nlohmann/json_fwd.hpp>
         ^
python: /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/interpreter/cling/lib/Interpreter/TransactionUnloader.cpp:72: bool cling::TransactionUnloader::unloadFromPreprocessor(cling::Transaction*, cling::DeclUnloader&): Assertion `Successful && "Cannot handle that yet!"' failed.
 *** Break *** abort
...
```
The header file being loaded is in `/cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/Tue/x86_64-centos7-gcc9-dbg/include/nlohmann/json_fwd.hpp`, which is included in `ROOT_INCLUDE_PATH `

According to Vassil. This is due to some bug/feature in clang when it resolves include paths with symlinks. The problem is avoided if the realpath of the directory containing the header is prepended explicitely to `ROOT_INCLUDE_PATH`.

```
$ export ROOT_INCLUDE_PATH=/cvmfs/sft.cern.ch/lcg/releases/jsonmcpp/3.9.1-72770/x86_64-centos7-gcc9-dbg/include:$ROOT_INCLUDE_PATH
$ python -c 'import GaudiPython'
```

**Comment by linev** [comment] 2021-04-22 09:09
Seems to be, main problem is clang and symlinks. While `json.hpp` and `json_fwd.hpp` are on their places.
I adding @vgvassilev

**Comment by guitargeek** [comment] 2023-12-18 18:59
I tried to reproduce this issue on `lxplus7`, using a newer compiler version because the current LGC stacks don't have gcc9 anymore:
```bash
source /cvmfs/sft-nightlies.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc11-dbg/setup.sh
python -c 'import GaudiPython'
```

However, everything works just fine. So something must have fixed the issue in the meantime and I'll close it.

@peremato, please feel free to re-open or create a new issue with a new reproducer, in case you are still encountering this in other environments!

**Closed by guitargeek** 2023-12-18 18:59 UTC
Labels: bug
