### ISSUE TITLE
build failure because of `nlohmann_json`

### ISSUE THREAD

**Issue by cburgard** [root-project/root#11236] opened 2022-08-22 15:26 UTC
### Describe the bug
I try to build the current master with the `-Dbuiltin_nlohmannjson=on`, but I obtain a lot of error messages [(make.log)](https://drive.google.com/file/d/161nAtyhRd3VFMud4V-F4xSQoype3T-Lt/view?usp=sharing)

### Expected behavior
The build succeeds.

### Setup

1. ROOT version: current master (452f82119a07fb873a7b050004477d9d9f93120d)
2. Operating system: Archlinux, gcc 12.1.1

**Comment by hahnjo** [comment] 2022-08-23 07:50
This is caused by having two (incompatible) `nlohmann/json` libraries, the builtin one from `/home/cburgard/Physics/root/src/builtins/nlohmann/json.hpp` and the system one from `/usr/include/nlohmann/json_fwd.hpp`. You can either just use the builtin one (should compile now with version 3.11+) or the builtin one will be fixed by https://github.com/root-project/root/pull/11223

**Comment by hahnjo** [comment] 2022-08-29 09:18
Should be fixed after https://github.com/root-project/root/pull/11223 was merged

**Closed by hahnjo** 2022-08-29 09:18 UTC
Labels: bug
