### ISSUE TITLE
Valgrind Source and destination overlap in memcpy(0x1ffeff0c78, 0x1ffeff0c78, 12)

### ISSUE THREAD

**Issue by wddgit** [root-project/root#6792] opened 2020-11-10 15:56 UTC
While attempting to debug a crash in CMS code, we ran valgrind and valgrind reported the following error. At this point, we don't know whether this is related to the crash we have seen or not. It is undefined behavior. The full error from valgrind follows:

==15413== Source and destination overlap in memcpy(0x1ffeff0c78, 0x1ffeff0c78, 12)
==15413== at 0x40322A8: memcpy@@GLIBC_2.14 (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/external/valgrind/3.15.0-bcolbf2/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15413== by 0x15A64868: void llvm::SmallVectorImpl::append<char const*, void>(char const*, char const*) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x17A3FD9F: (anonymous namespace)::RedirectingFileSystemParser::parseEntry(llvm::yaml::Node*, (anonymous namespace)::RedirectingFileSystem*) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x17A40C05: (anonymous namespace)::RedirectingFileSystem::create(std::unique_ptr<llvm::MemoryBuffer, std::default_deletellvm::MemoryBuffer >, void ()(llvm::SMDiagnostic const&, void), llvm::StringRef, void*, llvm::IntrusiveRefCntPtrclang::vfs::FileSystem) [clone .isra.519] (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x17A40EC5: clang::vfs::getVFSFromYAML(std::unique_ptr<llvm::MemoryBuffer, std::default_deletellvm::MemoryBuffer >, void ()(llvm::SMDiagnostic const&, void), llvm::StringRef, void*, llvm::IntrusiveRefCntPtrclang::vfs::FileSystem) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x15A690B4: (anonymous namespace)::collectModuleMaps(clang::CompilerInstance&, llvm::SmallVectorImpl<std::__cxx11::basic_string<char, std::char_traits, std::allocator > >&) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x15A69FE3: (anonymous namespace)::setupCxxModules(clang::CompilerInstance&) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x15A6EEE7: (anonymous namespace)::createCIImpl(std::unique_ptr<llvm::MemoryBuffer, std::default_deletellvm::MemoryBuffer >, cling::CompilerOptions const&, char const*, std::unique_ptr<clang::ASTConsumer, std::default_deleteclang::ASTConsumer >, std::vector<std::shared_ptrclang::ModuleFileExtension, std::allocator<std::shared_ptrclang::ModuleFileExtension > > const&, bool, bool) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x15A6FF2A: cling::CIFactory::createCI(llvm::StringRef, cling::InvocationOptions const&, char const*, std::unique_ptr<clang::ASTConsumer, std::default_deleteclang::ASTConsumer >, std::vector<std::shared_ptrclang::ModuleFileExtension, std::allocator<std::shared_ptrclang::ModuleFileExtension > > const&) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x15B0A9FC: cling::IncrementalParser::IncrementalParser(cling::Interpreter*, char const*, std::vector<std::shared_ptrclang::ModuleFileExtension, std::allocator<std::shared_ptrclang::ModuleFileExtension > > const&) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x15A94236: cling::Interpreter::Interpreter(int, char const* const*, char const*, std::vector<std::shared_ptrclang::ModuleFileExtension, std::allocator<std::shared_ptrclang::ModuleFileExtension > > const&, bool, cling::Interpreter const*) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x15A1E925: TCling::TCling(char const*, char const*, char const* const*) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x15A1FB93: CreateInterpreter (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCling.so)
==15413== by 0x68F7398: TROOT::InitInterpreter() (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCore.so)
==15413== by 0x68F784E: ROOT::Internal::GetROOT2() (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/lcg/root/6.22.03-b2018e1d820c64836287b955b51776e2/lib/libCore.so)
==15413== by 0x138725BC: TFileAdaptor::TFileAdaptor(edm::ParameterSet const&, edm::ActivityRegistry&) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-08-2300/lib/slc7_amd64_gcc820/libIOPoolTFileAdaptor.so)
==15413== by 0xF95AEE1: edm::serviceregistry::ServiceMaker<TFileAdaptor, edm::serviceregistry::AllArgsMaker<TFileAdaptor, TFileAdaptor> >::make(edm::ParameterSet const&, edm::ActivityRegistry&, edm::serviceregistry::ServicesManager&) const (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-08-2300/lib/slc7_amd64_gcc820/pluginIOPoolTFileAdaptorAuto.so)
==15413== by 0x40E7B68: edm::serviceregistry::ServicesManager::MakerHolder::add(edm::serviceregistry::ServicesManager&) const (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-08-2300/lib/slc7_amd64_gcc820/libFWCoreServiceRegistry.so)
==15413== by 0x40E7D20: edm::serviceregistry::ServicesManager::createServiceFor(edm::serviceregistry::ServicesManager::MakerHolder const&) (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-08-2300/lib/slc7_amd64_gcc820/libFWCoreServiceRegistry.so)
==15413== by 0x40E7E76: edm::serviceregistry::ServicesManager::createServices() (in /cvmfs/cms-ib.cern.ch/nweek-02654/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-11-08-2300/lib/slc7_amd64_gcc820/libFWCoreServiceRegis
...

**Comment by eguiraud** [comment] 2020-11-11 07:56
Duplicate of https://sft.its.cern.ch/jira/browse/ROOT-10806

**Comment by Axel-Naumann** [comment] 2020-11-18 09:36
Thanks, @wddgit - we are aware, please follow https://sft.its.cern.ch/jira/browse/ROOT-10806 where this was first reported. Closing this.

**Closed by Axel-Naumann** 2020-11-18 09:36 UTC
Labels: bug
