### ISSUE TITLE
Wrongly printing root CLI help message when using pyROOT with '-h' or '--help' in sys.argv

### ISSUE THREAD

**Issue by AlkaidCheng** [root-project/root#7161] opened 2021-02-09 16:18 UTC
### Version
ROOT version: 6.18/04
OS: Linux, SLC7
How you obtained ROOT: conda install
### Describe the bug

When using pyROOT (might not necessarily be due to using pyROOT) with '-h' or '--help' in sys.argv, if a ROOT method is called, a root CLI help message will be wrongly printed out.

In a lot of cases when designing a python package that uses ROOT with CLI support, this bug will make the CLI print out the root help instead of the intended help message from the python package.

### To reproduce the issue (e.g. using python interpreter):
```
import sys
sys.argv.append('-h')
import ROOT
ROOT.Double()
```
This will print out the following message:

"""
usage: root [-b B] [-x X] [-e E] [-n N] [-t T] [-q Q] [-l L] [-config CONFIG]
            [-memstat MEMSTAT] [-h HELP] [--version VERSION]
            [--notebook NOTEBOOK] [--web WEB] [--web=<browser> WEB=<BROWSER>]
            [dir] [file:data.root] [file1.C...fileN.C]

OPTIONS:
  -b                             Run in batch mode without graphics
  -x                             Exit on exceptions
  -e                             Execute the command passed between single quotes
  -n                             Do not execute logon and logoff macros as specified in .rootrc
  -t                             Enable thread-safety and implicit multi-threading (IMT)
  -q                             Exit after processing command line macro files
  -l                             Do not show splash screen
  -config                        print ./configure options
  -memstat                       run with memory usage monitoring
  -h, -?, --help                 Show summary of options
  --version                      Show the ROOT version
  --notebook                     Execute ROOT notebook
  --web                          Display graphics in a default web browser
  --web=<browser>                Display graphics in specified web browser
  [dir]                          if dir is a valid directory cd to it before executing
  [file:data.root]               Open the ROOT file data.root
  [file1.C...fileN.C]            Execute the the ROOT macro file1.C ... fileN.C
"""
And the program will terminate.

### Expected behaviour

No root CLI help message should be printed out

**Comment by eguiraud** [comment] 2021-02-09 16:50
@AlkaidCheng could you check whether that's still the case in 6.22? I think this might be a duplicate of https://sft.its.cern.ch/jira/browse/ROOT-9447 .

**Comment by etejedor** [comment] 2021-02-09 16:53
Indeed, as @eguiraud has mentioned, this behaviour is not present anymore in ROOT >= 6.22, where ROOT does not parse the command line arguments by default. This is documented here:

https://root.cern/manual/python/#user-interface

(see `IgnoreCommandLineOptions` option).

**Comment by etejedor** [comment] 2021-02-09 16:59
If moving to a newer ROOT version is not an option, you can still disable this behaviour by typing at the beginning of your script:
```
import ROOT
ROOT.PyConfig.IgnoreCommandLineOptions = True
```

**Comment by AlkaidCheng** [comment] 2021-02-10 07:16
> If moving to a newer ROOT version is not an option, you can still disable this behaviour by typing at the beginning of your script:
> 
> ```
> import ROOT
> ROOT.PyConfig.IgnoreCommandLineOptions = True
> ```

This worked for me. Thank you!

**Closed** 2021-02-10 07:57 UTC
Labels: in:PyROOT
