### ISSUE TITLE
Memory  leak when running FrequentistCalculator scan in RooStats

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#7890] opened 2021-04-15 13:57 UTC
The problem has been reported in https://root-forum.cern.ch/t/significantly-increased-memory-consumption-of-standardhypotestinvdemo-c-in-6-20-06-compared-to-6-14-04/44405

When running the FrequentistCalculator scan in RooStats with the StandardHypoTestInvDemo.C  a large memory increase is observed after 6.14. 
To reproduce is enough to  use the workspace created from the `example.xml` of the histfactory tutorial. Do for example : 
``` 
/usr/bin/time --verbose root.exe -l -b -q "StandardHypoTestInvDemo.C(\"example_combined_GaussExample_model.root\")"
```

Running bisect the cause of this memory increase is this PR: 
#2866

**Comment by lmoneta** [comment] 2021-04-15 14:00
Valgrind reports these leaks in RooArgSet:
```
==759== 1,008,000 bytes in 1 blocks are still reachable in loss record 18,282 of 18,292
==759==    at 0x4C2A593: operator new(unsigned long) (vg_replace_malloc.c:344)
==759==    by 0x15B5CF61: RooArgSet::operator new(unsigned long) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B60B12: RooArgSet::create(char const*) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15AF77B6: RooAbsCollection::snapshot(bool) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C353A9: RooProdPdf::RooProdPdf(RooProdPdf const&, char const*) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C3EC34: RooProdPdf::clone(char const*) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15AF6694: RooAbsCollection::snapshot(RooAbsCollection&, bool) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15AF77D6: RooAbsCollection::snapshot(bool) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B24D7C: RooAbsReal::fillDataHist(RooDataHist*, RooArgSet const*, double, bool, bool) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B62CCA: RooBinnedGenContext::generate(double, bool, bool) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C6F42F: RooSimSplitGenContext::generate(double, bool, bool) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B1A91B: RooAbsPdf::generate(RooAbsPdf::GenSpec&) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759== 
==759== 1,008,000 bytes in 1 blocks are still reachable in loss record 18,283 of 18,292
==759==    at 0x4C2A593: operator new(unsigned long) (vg_replace_malloc.c:344)
==759==    by 0x15B5CF61: RooArgSet::operator new(unsigned long) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C4FC8F: RooRealIntegral::RooRealIntegral(char const*, char const*, RooAbsReal const&, RooArgSet const&, RooArgSet const*, RooNumIntConfig const*, char const*) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B28A45: RooAbsReal::createIntObj(RooArgSet const&, RooArgSet const*, RooNumIntConfig const*, char const*) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B2915F: RooAbsReal::createIntegral(RooArgSet const&, RooArgSet const*, RooNumIntConfig const*, char const*) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C376A2: RooProdPdf::processProductTerm(RooArgSet const*, RooArgSet const*, char const*, RooArgSet const*, RooArgSet const&, RooArgSet const&, bool&, bool) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C3CF87: RooProdPdf::getPartIntList(RooArgSet const*, RooArgSet const*, RooArgList*&, RooLinkedList*&, int&, char const*) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C3DC47: RooProdPdf::evaluate() const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B12590: RooAbsPdf::getValV(RooArgSet const*) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B24E8E: RooAbsReal::fillDataHist(RooDataHist*, RooArgSet const*, double, bool, bool) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B62CCA: RooBinnedGenContext::generate(double, bool, bool) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C6F42F: RooSimSplitGenContext::generate(double, bool, bool) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759== 
==759== 1,008,000 bytes in 1 blocks are still reachable in loss record 18,284 of 18,292
==759==    at 0x4C2A593: operator new(unsigned long) (vg_replace_malloc.c:344)
==759==    by 0x15B5CF61: RooArgSet::operator new(unsigned long) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C35B09: RooProdPdf::factorizeProduct(RooArgSet const&, RooArgSet const&, RooLinkedList&, RooLinkedList&, RooLinkedList&, RooLinkedList&, RooLinkedList&) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C39FF7: RooProdPdf::getPartIntList(RooArgSet const*, RooArgSet const*, RooArgList*&, RooLinkedList*&, int&, char const*) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C3DC47: RooProdPdf::evaluate() const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B12590: RooAbsPdf::getValV(RooArgSet const*) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B24E8E: RooAbsReal::fillDataHist(RooDataHist*, RooArgSet const*, double, bool, bool) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B62CCA: RooBinnedGenContext::generate(double, bool, bool) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15C6F42F: RooSimSplitGenContext::generate(double, bool, bool) (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x15B1A91B: RooAbsPdf::generate(RooAbsPdf::GenSpec&) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooFitCore.so.6.16.00)
==759==    by 0x1A650F7D: RooStats::ToyMCSampler::Generate(RooAbsPdf&, RooArgSet&, RooDataSet const*, int) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooStats.so.6.16.00)
==759==    by 0x1A651FCA: RooStats::ToyMCSampler::GenerateToyData(RooArgSet&, double&, RooAbsPdf&) const (in /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.16.00/x86_64-centos7-gcc48-opt/lib/libRooStats.so.6.16.00)
==759== 
```

**Comment by hageboeck** [comment] 2021-04-19 07:36
Leaks found (and fixed in #7904; merging soon), but still needs backports to:
- [ ] 6.18
- [ ] 6.20
- [ ] 6.22
- [ ] 6.24

**Comment by hageboeck** [comment] 2021-04-22 07:42
Github closed this automatically. Reopen since backports are missing.

**Comment by guitargeek** [comment] 2021-04-22 18:08
This issue can be closed once all the backports are merged:
* 6.18: https://github.com/root-project/root/pull/7972
* 6.20: https://github.com/root-project/root/pull/7973
* 6.22: https://github.com/root-project/root/pull/7974
* 6.24: https://github.com/root-project/root/pull/7975

**Closed** 2021-04-22 21:19 UTC
Labels: affects:6.18, affects:6.20, affects:6.22, affects:6.24, bug, in:RooFit/RooStats, priority:critical

**Comment by guitargeek** [comment] 2021-05-10 15:38
Hi @luilongo, I think there are very likely related. Can you please open a new issue with this problem, so it gets the spotlight it deserves and is better to track for us? If possible, please also add some code to reproduce the problem in that new issue (or point to the repository where we can find the code from the slides, if its public).

Thanks!
