### ISSUE TITLE
Bus error when trying to draw TH1F on macos 14.4

### ISSUE THREAD

**Issue by TheCodeEater** [root-project/root#15129] opened 2024-04-04 08:22 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When trying to draw a TH1F from interactive interpreter, i get a bus error and the program crashes. 
```
  ------------------------------------------------------------------
  | Welcome to ROOT 6.30/06                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on Apr 03 2024, 10:22:56                   |
  | From tags/v6.30.06-0-g4f4e716372@v6.30.06-0-g4f4e716372          |
  | With Apple clang version 15.0.0 (clang-1500.3.9.4)               |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] TH1F* h=new TH1F("histo","h",5,-10,10);
root [1] h->Fill(5);
root [2] h->Draw();

 *** Break *** bus error
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO] PNGReadPlugin::InitializePluginData(IIOImageReadSession*, IIODictionary*, IIODictionary*, CGImageMetadata*, CGColorSpace**, ReadPluginData&, PNGPluginData&, __CFDictionary*) (no debug info)
[/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO] IIOReadPlugin::callInitialize() (no debug info)
[/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO] IIO_Reader::initImageAtOffset(CGImagePlugin*, unsigned long, unsigned long, unsigned long) (no debug info)
[/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO] IIOImageSource::makeImagePlus(unsigned long, IIODictionary*) (no debug info)
[/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO] IIOImageSource::getPropertiesAtIndexInternal(unsigned long, IIODictionary*) (no debug info)
[/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO] IIOImageSource::copyPropertiesAtIndex(unsigned long, IIODictionary*) (no debug info)
[/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO] CGImageSourceCopyPropertiesAtIndex (no debug info)
[/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit] ImageSourceOptionsForCGImageSource_index_ (no debug info)
[/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit] +[NSBitmapImageRep _imagesWithData:hfsFileType:extension:zone:expandImageContentNow:includeAllReps:] (no debug info)
[/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit] +[NSBitmapImageRep _imageRepsWithData:hfsFileType:extension:expandImageContentNow:] (no debug info)
[/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit] +[NSImageRep _imageRepsWithContentsOfURL:expandImageContentNow:giveUpOnNetworkURLsWithoutGoodExtensions:] (no debug info)
[/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit] -[NSImage initWithContentsOfURL:] (no debug info)
[/Applications/root_v6.30.06/lib/libGCocoa.so] TGCocoa::SetApplicationIcon() (no debug info)
[/Applications/root_v6.30.06/lib/libGCocoa.so] TGCocoa::MapWindow(unsigned long) (no debug info)
[/Applications/root_v6.30.06/lib/libGui.so] TGStatusBar::TGStatusBar(TGWindow const*, unsigned int, unsigned int, unsigned int, unsigned long) (no debug info)
[/Applications/root_v6.30.06/lib/libGui.so] TRootCanvas::CreateCanvas(char const*) (no debug info)
[/Applications/root_v6.30.06/lib/libGui.so] TRootCanvas::TRootCanvas(TCanvas*, char const*, int, int, unsigned int, unsigned int) (no debug info)
[/Applications/root_v6.30.06/lib/libGui.so] TRootGuiFactory::CreateCanvasImp(TCanvas*, char const*, int, int, unsigned int, unsigned int) (no debug info)
[/Applications/root_v6.30.06/lib/libGpad.so] TCanvas::Constructor(char const*, char const*, int) (no debug info)
[/Applications/root_v6.30.06/lib/libGpad.so] TCanvas::TCanvas(char const*, char const*, int) (no debug info)
[/Applications/root_v6.30.06/lib/libGpad.so] TCanvas::MakeDefCanvas() (no debug info)
[<unknown binary>] (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::IncrementalExecutor::executeWrapper(llvm::StringRef, cling::Value*) const (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::Interpreter::RunFunction(clang::FunctionDecl const*, cling::Value*) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::Interpreter::EvaluateInternal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::Interpreter::process(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, cling::Value*, cling::Transaction**, bool) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) (no debug info)
[/Applications/root_v6.30.06/lib/libCore.so] TROOT::ProcessLine(char const*, int*) (no debug info)
[/Applications/root_v6.30.06/lib/libCore.so] TObject::AppendPad(char const*) (no debug info)
[/Applications/root_v6.30.06/lib/libHist.so] TH1::Draw(char const*) (no debug info)
[<unknown binary>] (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::IncrementalExecutor::executeWrapper(llvm::StringRef, cling::Value*) const (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::Interpreter::RunFunction(clang::FunctionDecl const*, cling::Value*) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::Interpreter::EvaluateInternal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::Interpreter::process(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, cling::Value*, cling::Transaction**, bool) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) (no debug info)
[/Applications/root_v6.30.06/lib/libCling.so] TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) (no debug info)
[/Applications/root_v6.30.06/lib/libRint.so] TRint::ProcessLineNr(char const*, char const*, int*) (no debug info)
[/Applications/root_v6.30.06/lib/libRint.so] TRint::HandleTermInput() (no debug info)
[/Applications/root_v6.30.06/lib/libCore.so] TUnixSystem::CheckDescriptors() (no debug info)
[/Applications/root_v6.30.06/lib/libCore.so] TMacOSXSystem::DispatchOneEvent(bool) (no debug info)
[/Applications/root_v6.30.06/lib/libCore.so] TSystem::InnerLoop() (no debug info)
[/Applications/root_v6.30.06/lib/libCore.so] TSystem::Run() (no debug info)
[/Applications/root_v6.30.06/lib/libCore.so] TApplication::Run(bool) (no debug info)
[/Applications/root_v6.30.06/lib/libRint.so] TRint::Run(bool) (no debug info)
[/Applications/root_v6.30.06/bin/root.exe] main (no debug info)
[/usr/lib/dyld] start (no debug info)
Root > 
```

### Reproducer

On macos 14.4 running on m1 arm 64 using xcode 15.3, open root in a terminal and run this code:
```
root [0] TH1F* h=new TH1F("histo","h",5,-10,10);
root [1] h->Fill(5);
root [2] h->Draw();
```

### ROOT version
```
 ------------------------------------------------------------------
  | Welcome to ROOT 6.30/06                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on Apr 03 2024, 10:22:56                   |
  | From tags/v6.30.06-0-g4f4e716372@v6.30.06-0-g4f4e716372          |
  | With Apple clang version 15.0.0 (clang-1500.3.9.4)               |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

### Installation method

macOS 14.4 arm64 Xcode 15 pre built binary with .pkg installer

### Operating system

MacOS Sonoma 14.4

### Additional context

I had previously installed root 6.28 from hombrew and it worked until i updated the system to sonoma 13. At this point I uninstalled it.
I tried to install from source 6.26 and it worked (with c++14), until i decided to upgrade to a newer version (6.30) in macos 14.3. It built, but it still gave bus error so i manually removed installed files from system directories

**Comment by couet** [comment] 2024-04-05 14:25
I tried on MAcOS 14.4 on Intel. I do not see the problem. I will tie on ARM

**Comment by couet** [comment] 2024-04-05 14:57
I tried it on MacOS 14.4.1 on an M2 machine with ROOT master and it is working fine. I cannot reproduce this issue.

**Comment by vepadulano** [comment] 2024-04-11 22:03
Hi @TheCodeEater ,

I have tried on MacOS 14.4.1 and XCode 15.2. I downloaded the `.pkg` binary from https://root.cern/releases/release-63006/ . Your reproducer does not crash on my system:

<img width="713" alt="Screenshot 2024-04-12 at 00 02 18" src="https://github.com/root-project/root/assets/15638895/1d23b494-07e5-44b3-acc6-277b18d38710">

**Comment by TheCodeEater** [comment] 2024-04-20 14:20
Hi,
i tried again but still does not work. Since in the past i tried to install root from source and then had to uninstall manually (the compiled files had been scattered in the bin, include and alike system folders) i guess there could be some 6.26 libraries in system search paths, which are loaded by root instead of its own? I will try to further clean my directories or force somehow root to search only in its versions' folder.
Thank you all for your feedkback.

**Comment by dpiparo** [comment] 2024-05-17 08:23
I am closing, assuming that the issue is clarified. Of course, do not hesitate to re-open in case this is a real problem we need to address. Thanks again for reporting.

**Closed by dpiparo** 2024-05-17 08:23 UTC
Labels: bug

**Comment by flanni64** [comment] 2024-05-23 18:38
Hi,
My apologies if i shouldn't post in this forum.

I have a similar problem, i.e. a bus error on my MacBook Air M2 Sonoma 14.5 (Xcode 15.4 / clang 15.0.0) - root 6.30/06 
(I've tried the binaries from the 'official' distribution, from homebrew and even recompiling the sources).

If I run root from Terminal.app it gives me a bus error with the same "message" as TheCodeEater on April 3rd. 

root [0] new TBrowser()

 *** Break *** bus error
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO] PNGReadPlugin::InitializePluginData(IIOImageReadSession*, IIODictionary*, IIODictionary*, CGImageMetadata*, CGColorSpace**, ReadPluginData&, PNGPluginData&, __CFDictionary*) (no debug info)


But i **don't get** a bus error IF: 
a) I run root as regular user from an xterm 
b) I run "sudo root" from the Mac's  Terminal.App

Any help is appreciated.
Francesco
