### ISSUE TITLE
[RF][HS3] ATLAS ttbar workspaces roundtrip

### ISSUE THREAD

**Issue by cburgard** [root-project/root#15756] opened 2024-06-05 07:59 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

An ATLAS analysis using top quarks is currently struggling to publish the HEPdata entry because of issues with the HS3 roundtrip-capability.

This needs to be fixed in a patch release ASAP.

This issue is WIP.

### Reproducer

@guitargeek has received the neccessary inputs.

### ROOT version

6.32.00

### Installation method

any

### Operating system

any

**Comment by dpiparo** [comment] 2024-06-05 15:54
Thanks for reporting. Is this perhaps a duplicate of https://github.com/root-project/root/issues/15755 ?

**Comment by guitargeek** [comment] 2024-06-05 16:15
No, we already know that these are separate problems, unfortunately

**Comment by dpiparo** [comment] 2024-06-10 18:02
Thanks for the clarification and to @cburgard for the reports.

**Closed** 2024-06-13 15:50 UTC
Labels: bug, in:RooFit/RooStats
