### ISSUE TITLE
[PyROOT] Cannot use SofieFunctor in Python

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#10684] opened 2022-06-01 09:51 UTC
When using the SofieFunctor to integrate the SOFIE inference in RDF from Python, it works if we declare in C++ and
JIT the code as in line 51 of the tutorial `tmva/TMVA_SOFIE_RDataFrame.py`, see 
https://github.com/root-project/root/blob/master/tutorials/tmva/TMVA_SOFIE_RDataFrame.py#L51

but if we replace that line with 
```
sofie_functor = ROOT.TMVA.Experimental.SofieFunctor[7,'TMVA_SOFIE_Higgs_trained_model::Session'](0,"")
```
and then later use the other signature of `RDataFrame::Define`
```
 df1.Define("DNN_Value", sofie_functor, ["rdfslot_","m_jj", "m_jjj", "m_lv", "m_jlv", "m_bb", "m_wbb", "m_wwbb"])
```

it does not work. Doing: 
`print(sofie_functor)` results in None object.

Trying also this , it does not work: 
```
 df1.Define("DNN_Value",  ROOT.TMVA.Experimental.SofieFunctor[7,'TMVA_SOFIE_Higgs_trained_model::Session'](0,""), ["rdfslot_","m_jj", "m_jjj", "m_lv", "m_jlv", "m_bb", "m_wbb", "m_wwbb"])
```

Trying instead to make a simpler reproducible with a similar template functor works fine.

**Comment by etejedor** [comment] 2022-06-27 12:09
A more standalone repro:
```python
import ROOT

ROOT.gInterpreter.Declare('''
#include <utility>

template <typename T>
class MySofieFunctorHelper {
};

auto helper_function() -> MySofieFunctorHelper<std::make_index_sequence<1>>
{
   return MySofieFunctorHelper<std::make_index_sequence<1>>();
}

auto helper = MySofieFunctorHelper<std::make_index_sequence<1>>();
''')

print(ROOT.helper)
print(ROOT.helper_function())
```
prints
```
<cppyy.gbl.MySofieFunctorHelper<integer_sequence<unsigned long,0> > object at 0x7f9190f75020>
None
```
So printing the variable works fine, but printing the return value of the function doesn't. `std::make_index_sequence` seems to play some role here, because replacing it by e.g. `std::vector<int>` in the template argument makes the function also work.

**Comment by etejedor** [comment] 2022-06-28 12:22
The issue happens in this [function](https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/cppyy-backend/clingwrapper/src/clingwrapper.cxx#L1507), when trying to get the return type normalized name of the `helper_function` function in the reproducer above.

This is a C++ reproducer of the problem:
```C++
#include <utility>

template <typename T>
class MySofieFunctorHelper {
};

auto helper_function() -> MySofieFunctorHelper<std::make_index_sequence<1>>
{
   return MySofieFunctorHelper<std::make_index_sequence<1>>();
}

void sofie_repro()
{
   auto f = gROOT->GetGlobalFunction("helper_function");
   auto ret_type = f->GetReturnTypeName();
   cout << ret_type << endl; // prints MySofieFunctorHelper<make_index_sequence<1> > 
   auto ret_type_norm = f->GetReturnTypeNormalizedName(); // breaks
}
```
When calling `GetReturnTypeNormalizedName()` on the `TFunction` object of `helper_function`, an assertion error shows up. E.g. from lxplus:
```
[etejedor@lxplus768 ~]$ source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc11-dbg/setup.sh 
[etejedor@lxplus768 ~]$ root -q sofie_repro.C 
   ------------------------------------------------------------------
  | Welcome to ROOT 6.27/01                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Jun 28 2022, 03:01:00                 |
  | From heads/master@v6-25-02-1592-ge9fa243                         |
  | With g++ (GCC) 11.2.0                                            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------


Processing sofie_repro.C...
MySofieFunctorHelper<make_index_sequence<1> >
root.exe: /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-HEAD/src/ROOT/HEAD/interpreter/llvm/src/tools/clang/include/clang/AST/TemplateBase.h:257: clang::QualType clang::TemplateArgument::getAsType() const: Assertion `getKind() == Type && "Unexpected kind"' failed.
```

I think we need @Axel-Naumann .

**Comment by dpiparo** [comment] 2024-02-04 07:21
This seems fixed in master. All repros work. @lmoneta could you confirm it works for the original case?

**Comment by dpiparo** [comment] 2024-04-04 15:23
I am closing. Please re-open in case this is still an issue (I retested on the 6.30.06 release and it works just fine)

**Closed** 2024-04-04 20:42 UTC
Labels: bug, in:Cling, in:PyROOT
