### ISSUE TITLE
[ROOT-4828] TMatrixTBase<double>::GetMatrix2Array bug in "Fortran" format

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14559] opened 2024-02-04 18:01 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-4828

I need to extract the contents of the TMatrixD m = [[1 2 3][4 5 6]] as a flat array hF = [1 4 2 5 3 6] (fortran style). The function GetMatrix2Array with option "F"  should do this, but the array returned is hF = [3 6 0 0 0 0]. Default "C" format works fine, though.

Please find below an example script displaying the problem:

```cpp
{
TMatrixD m(2,3);
for(int i = 0; i &amp;lt; 2; i++)
{
for(int j = 0; j &amp;lt; 3; j++)
{
m[i][j] = i*3 \+ j \+ 1;
}
}
m.Print();

Double_t hC[6];
Double_t hF[6];

m.GetMatrix2Array(hC);
m.GetMatrix2Array(hF, &amp;quot;F&amp;quot;);

cout<< "C | F" << Lendl;
cout << "-------" << endl;
for(int i = 0; i &amp;lt; 6; i++)
{
cout << " " << hC[i] << "|" << hF[i] << endl;
}

}
```

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by devajithvs** [comment] 2024-02-14 10:43
Cannot reproduce this issue, I get the following (correct) output:
```bash
dvalapar@pceproot007:~/work/root/clingbuild (dev.fix_9672-1)$ root test.C
   ------------------------------------------------------------------
  | Welcome to ROOT 6.31/01                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Feb 13 2024, 09:36:41                 |
  | From heads/dev.fix_9672@v6-31-01-997-gc30c4035f6                 |
  | With Ubuntu clang version 14.0.0-1ubuntu1.1                      |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] 
Processing test.C...

2x3 matrix is as follows

     |      0    |      1    |      2    |
--------------------------------------------
   0 |          1           2           3 
   1 |          4           5           6 

C | F
-------
 1|1
 2|4
 3|2
 4|5
 5|3
 6|6
root [1] 
```

**Comment by mdessole** [comment] 2024-02-15 13:05
This was fixed (here)[https://github.com/root-project/root/commit/2fc350d0762f54ccef4378035dfa15281ff75626]

**Comment by devajithvs** [comment] 2024-02-15 13:55
> This was fixed [here](https://github.com/root-project/root/commit/2fc350d0762f54ccef4378035dfa15281ff75626)

Thanks @mdessole. Can we close this issue then?

**Closed** 2024-02-20 16:47 UTC
Labels: bug, fixathon
