### ISSUE TITLE
[PyROOT] Python list of strings -> std::initializer_list< std::string > conversion is broken

### ISSUE THREAD

**Issue by etejedor** [root-project/root#11411] opened 2022-09-22 09:42 UTC
This is a spinoff from #10092 .

The following reproducer segfaults:

```python
import ROOT
ROOT.gInterpreter.Declare("""
void foo (const std::initializer_list< std::string > &columns) {}
""")
ROOT.foo(["x"])
```

**Comment by dpiparo** [comment] 2024-02-05 04:53
Interesting. It does crash on linux but not on macos.

**Comment by guitargeek** [comment] 2024-02-05 09:57
On which Linux, @dpiparo? For me on Arch Linux it works with ROOT `master`.

I have created a unit test for ROOT test, like this we can maybe see on which platforms it still fails:
https://github.com/root-project/roottest/pull/1052

**Comment by dpiparo** [comment] 2024-02-07 12:27
This is odd. It works on 6.30 on el9 but not for master. Take for example `source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-el9-gcc11-opt/setup.sh` on `lxplus`.

**Comment by guitargeek** [comment] 2024-02-29 12:43
New insights:

* when adding the reproducer to `roottest`, most of the Jenkins platforms will fail:
  https://github.com/root-project/roottest/pull/1052

* when testing the reproducer together with the CPyCppyy upgrade, the test `projectroot.roottest.python.cpp.roottest_python_cpp_cpp11` will instead pass on all platforms:
  https://github.com/root-project/roottest/pull/1071
  (note that there are other failures related to the CPyCppyy upgrade that are unrelated to the issue)

Therefore, I can attest that this issue will be fixed with the CPyCppyy upgrade. This makes total sense, because the upgrade includes a patch that fixes the conversion of initializer lists:
https://github.com/wlav/CPyCppyy/pull/14

**Closed** 2024-03-19 16:49 UTC
Labels: bug, in:PyROOT
