### ISSUE TITLE
rdf TChain and branches interaction

### ISSUE THREAD

**Issue by andrzejnovak** [root-project/root#7084] opened 2021-01-23 18:09 UTC
I was trying to make  a skim from multiple files in the following way 
```
fChain = ROOT.TChain("Events")
           
    for f in filelist:
        fChain.Add(f)
    events_df = ROOT.RDataFrame(fChain)
    events_out = events_df .Filter(...
    outVars = ....
    events_out.Snapshot("Events", out, outVars)
```

Unfortunately, I've found that in a limited number of cases I had files that did not have all the required branches. Which threw the following error 
```
    TypeError: could not convert argument 3
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RJittedFilter,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    runtime_error: Column "HLT_AK8PFJet500" is not in a dataset and is not a custom column been defined.
  Failed to instantiate "Snapshot(std::string,std::string,std::vector<string>*)"
  ROOT::RDF::RResultPtr<ROOT::RDF::RInterface<ROOT::Detail::RDF::RLoopManager,void> > ROOT::RDF::RInterface<ROOT::Detail::RDF::RJittedFilter,void>::Snapshot(basic_string_view<char,char_traits<char> > treename, basic_string_view<char,char_traits<char> > filename, const vector<string>& columnList, const ROOT::RDF::RSnapshotOptions& options = ROOT::RDF::RSnapshotOptions()) =>
    runtime_error: Column "HLT_AK8PFJet500" is not in a dataset and is not a custom column been defined.
```

Is there a way around this? Curiously I've also accidentally tried it in an older env with `6.18`  which displayed an error, but created the output file anyway.  `Error in <TTreeReader::SetEntryBase()>: There was an error while notifying the proxies` I am not sure about the specific branches, but the file as a whole was still readable.

**Comment by eguiraud** [comment] 2021-01-25 09:27
Hi Andrzej,
I think throwing an error is ok, we don't want to create an output where some branches have less entries than others or something like that.

In the future we would like to introduce the possibility to specify something like "if this branch is not there, use this default value instead" but it's a bit tricky, `TChain` and `TTreeReader` (which RDF uses under the hood) are not really built for this case.

A workaround of course is to do a first pass over the files and use `df.GetColumnNames()` to separate the files with all branches from the ones where some branches are missing, and process the "weird" files separately.

**Comment by andrzejnovak** [comment] 2021-01-25 09:53
Thanks for the explanation @eguiraud! Indeed it would be convenient to have to option to fill a default if missing, but indeed I would be better if this didn't come up in the first place

**Comment by eguiraud** [comment] 2021-01-25 14:52
Alright, so I'm closing this bug report as "not a bug", but feel free to open an "improvement" issue about the "fallback values for missing branches in TChain".

Cheers!
Enrico

**Closed by eguiraud** 2021-01-25 14:52 UTC
Labels: bug, in:RDataFrame
