### ISSUE TITLE
Importing NumPy in python after importing ROOT results in segmentation error on Python 3.11.2

### ISSUE THREAD

**Issue by DanteNiewenhuis** [root-project/root#12874] opened 2023-05-24 12:04 UTC
- [x] Checked for duplicates

### Describe the bug
When importing NumPy in Python 3.11.2 after ROOT has been imported, a segmentation error is returned. 
![image](https://github.com/root-project/root/assets/25668305/47651cbe-5113-410f-844c-17fd97ce4f03)

There are no problems when importing numpy before importing ROOT:
![image](https://github.com/root-project/root/assets/25668305/6d0baf18-2ada-4f94-91bd-c000c4bebdc7)

### To Reproduce
1. Run the following code in Python 3.11.2
`import ROOT`
`import numpy`

### Setup
1. ROOT version: 6.29/01 
2. Operating system: Ubuntu 23.04, Python 3.11.2 
3. How you obtained ROOT: Build from source, pulled from the github today

**Comment by vepadulano** [comment] 2023-05-25 10:05
Hi @DanteNiewenhuis ,

Thanks for the report. I have tested on Fedora36 with Python 3.11.2 and numpy 1.24.3. I cannot reproduce the issue. numpy works with Python 3.11 only since version 1.24, so I tested 1.24.[0-3] but still no segfault.

I will try to build in a ubuntu container and report back

**Comment by vepadulano** [comment] 2023-05-25 11:42
Also on a fresh ubuntu docker image I can't trigger the segfault:
```
root@0deac9fbdde6:/rootproject# cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Ubuntu 23.04"
root@0deac9fbdde6:/rootproject# root --version
ROOT Version: 6.29/01
Built for linuxx8664gcc on May 25 2023, 10:46:00
From heads/master@v6-25-02-4827-g0f578379d8
root@0deac9fbdde6:/rootproject# python -c "import ROOT; import numpy"
root@0deac9fbdde6:/rootproject# python --version
Python 3.11.2
```

Maybe we are using different cmake configurations, I just build with `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo`.

**Comment by musinsky** [comment] 2023-05-25 15:28
Check on Fedora 38 (Python 3.11.3, numpy 1.24.3) with ROOT build from source (pulled today) and without problem.

**Comment by Axel-Naumann** [comment] 2023-05-30 13:17
@DanteNiewenhuis how did you build ROOT, what are the flags?

Can you attach gdb to Python and share the backtrace of the crash?

**Comment by hahnjo** [comment] 2023-06-14 08:08
Potentially related failure on macbeta: https://lcgapp-services.cern.ch/root-jenkins/job/root-nightly-master/LABEL=macbeta,SPEC=cxx20,V=master/3525/testReport/junit/projectroot.roottest.python/stl/roottest_python_stl_stl/

```
../../../../roottest/python/stl/PyROOT_stltests.py .....Fatal Python error: Segmentation fault

Current thread 0x00007ff851579c80 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/python.py", line 1789 in runtest
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/runner.py", line 167 in pytest_runtest_call
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/runner.py", line 260 in <lambda>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/runner.py", line 339 in from_call
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/runner.py", line 220 in call_and_report
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/main.py", line 324 in _main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/Users/sftnight/build/jenkins/night/LABEL/macbeta/SPEC/cxx20/V/master/roottest/python/common.py", line 46 in run_pytest
  File "/Users/sftnight/build/jenkins/night/LABEL/macbeta/SPEC/cxx20/V/master/roottest/python/stl/PyROOT_stltests.py", line 530 in <module>
```

No involvement of NumPy, but potentially we're still not properly setting up garbage collection with the changes in Python 3.11...

**Comment by guitargeek** [comment] 2023-11-07 07:58
Closing as "not planned" since we can't reproduce the problem

**Closed by guitargeek** 2023-11-07 07:58 UTC
Labels: bug, in:PyROOT
