### ISSUE TITLE
CUDA-enabled ROOT 'HEAD' builds failing in LCG nightlies

### ISSUE THREAD

**Issue by dkonst13** [root-project/root#13415] opened 2023-08-08 13:01 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

Hi ROOT team,

We ran into some trouble last night with the ROOT "HEAD" builds that have CUDA enabled in our LCG nightlies.

The builds failed on these platforms: x86_64-centos7-gcc11-opt, x86_64-centos8-gcc11-opt, and el9-gcc11-opt. These are the ones we use for this configuration.

@bellenot:  asked me to let you know, so here's the ticket.

Here's the error message we got:

```
Error: Module 'RooFitCuda.pcm' failed to load.
```
and this:
```
make[5]: *** [roofit/roofitcore/CMakeFiles/G__RooFitCore.dir/build.make:519: roofit/roofitcore/G__RooFitCore.cxx] Error 1
make[5]: Target 'roofit/roofitcore/CMakeFiles/G__RooFitCore.dir/depend' not remade because of errors.
make[4]: *** [CMakeFiles/Makefile2:44521: roofit/roofitcore/CMakeFiles/G__RooFitCore.dir/all] Error 2
```

you can find the full build logs here:

http://cdash.cern.ch/upload/d526fd513d6f4007d95aa0eeb56dfc0627929bf1/ROOT-HEAD-build.log

Thanks for looking into this, and let me know if you need anything else!

Cheers,
    Dmitri

### Reproducer

No reproducer

### ROOT version

HEAD

### Installation method

build from sources

### Operating system

Linux, centos7

**Comment by dkonst13** [comment] 2023-08-09 10:37
Sure.

[ROOT-HEAD-configure.log](https://github.com/root-project/root/files/12301180/ROOT-HEAD-configure.log)

And the configuration line:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/dkonst/install/dev3cuda/ROOT/HEAD/x86_64-centos7-gcc11-opt -Dtmva-sofie=ON -Droot7=ON -Dpyroot=ON -DPYTHON_EXECUTABLE=/tmp/dkonst/install/dev3cuda/Python/3.9.12/x86_64-centos7-gcc11-opt/bin/python -Dbuiltin_lz4=ON -Dbuiltin_pcre=ON -Dbuiltin_xxhash=ON -Dbuiltin_ftgl=ON -Dbuiltin_afterimage=ON -Dbuiltin_glew=ON -Dbuiltin_unuran=ON -Dbuiltin_zstd=ON -Dcintex=ON -Dcuda=ON -Dtmva-gpu=ON -DCMAKE_CUDA_STANDARD=17 -Ddavix=ON -Dexceptions=ON -Dexplicitlink=ON -Dfftw3=ON -Dgdml=ON -Dhttp=ON -Dgenvector=ON -Dvc=ON -Dmathmore=ON -Dminuit2=ON -Dmysql=ON -Dopengl=ON -Dpgsql=OFF -Dpythia6=OFF -Dpythia8=OFF -Dreflex=ON -Dr=OFF -Droofit=ON -Dssl=ON -Dunuran=ON -Dfortran=ON -Dxft=ON -Dxml=ON -Dxrootd=ON -Dzlib=ON -DCINTMAXSTRUCT=36000 -DCINTMAXTYPEDEF=36000 -DCINTLONGLINE=4096 -Dfail-on-missing=ON;-Dfitsio=ON -Doracle=OFF -DCMAKE_CXX_STANDARD=17 -Ddcache=ON -Doracle=ON -DORACLE_HOME=/tmp/dkonst/install/dev3cuda/oracle/19.19.0.0.0/x86_64-centos7-gcc11-opt -Dbuiltin_nlohmannjson=OFF -Droofit_multiprocess=OFF /tmp/dkonst/build/projects/ROOT-HEAD/src/ROOT/HEAD
```

**Comment by guitargeek** [comment] 2023-08-09 11:27
Hi, thanks! Let me know if the problem is fixed in the nightlies tomorrow morning, if yes I can close this issue :+1:

**Comment by dkonst13** [comment] 2023-08-10 14:13
Hi @guitargeek , it is fine now! Thank you for the fix! Cheers!

**Closed** 2023-08-10 14:55 UTC
Labels: bug, in:RooFit/RooStats
