### ISSUE TITLE
[ROOT-10847] Missing copy constructor in TH2Poly

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14548] opened 2024-02-04 17:45 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-10847

I'm trying to run a simple RDF program that fills a `TH2Poly` object:

```cpp
#include <ROOT/RDataFrame.hxx>
#include <TH2Poly.h>
#include <TCanvas.h>
#include <string>

int main()
{
   ROOT::RDataFrame df(100);

   auto filled = df.Define("b1", "(double) rdfentry_")
                    .Define("b2", "(double) rdfentry_ * rdfentry_")
                    .Fill<double, double>(TH2Poly("name", "title", 0, 10, 0, 100), {"b1", "b2"});

   TCanvas c{"", "", 600, 600};
   c.cd();

   filled->Draw("colz");

   c.Draw();
   c.SaveAs("rdf_fill_th2poly.png");
}
```

But getting errors because the copy constructor of `TH2Poly` is deleted:

```
/home/vincenzo/Programs/rootproject/build/masterdevoptsystemtbb/include/ROOT/RDF/ActionHelpers.hxx:298:24: error: use of deleted function ‘TH2Poly::TH2Poly(const TH2Poly&)’
  298 |          fObjects[i] = new HIST(*fObjects[0]);
      |                        ^~~~~~~~~~~~~~~~~~~~~~
In file included from rdf_fill_th2poly.cpp:2:
/home/vincenzo/Programs/rootproject/build/masterdevoptsystemtbb/include/TH2Poly.h:66:7: note: ‘TH2Poly::TH2Poly(const TH2Poly&)’ is implicitly deleted because the default definition would be ill-formed:
   66 | class TH2Poly : public TH2 {
```

Is it possible to add it ?

Cheers,
Vincenzo

### Reproducer

As per description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by guitargeek** [comment] 2024-02-05 10:00
Duplicate of this issue:
https://github.com/root-project/root/issues/13075

**Closed by guitargeek** 2024-02-05 10:00 UTC
Labels: bug, fixathon
