### ISSUE TITLE
Warnings about Missing std::pair dictionaries with 6.24

### ISSUE THREAD

**Issue by daritter** [root-project/root#7960] opened 2021-04-22 08:58 UTC
### Describe the bug

After switching to 6.24 (GCC 10.2) I see new warnings about missing dictionaries

```
TClass::Init:0: RuntimeWarning: no dictionary for class pair<int,unordered_map<int,vector<Belle2::ECLChargedPidPDFs::InputVar> > > is available
TClass::Init:0: RuntimeWarning: no dictionary for class pair<int,vector<Belle2::ECLChargedPidPDFs::InputVar> > is available
TClass::Init:0: RuntimeWarning: no dictionary for class pair<int,unordered_map<int,unordered_map<Belle2::ECLChargedPidPDFs::InputVar,TF1*> > > is available
TClass::Init:0: RuntimeWarning: no dictionary for class pair<int,unordered_map<Belle2::ECLChargedPidPDFs::InputVar,TF1*> > is available
TClass::Init:0: RuntimeWarning: no dictionary for class pair<Belle2::ECLChargedPidPDFs::InputVar,TF1*> is available
```

All of them seem to involve `std::pair`. In this case `Belle2::ECLChargedPidPDFs::InputVar` is an enum and I have one other case where there's also a `std::pair` and a enum involved. They were not present with 6.20/4

### Setup
* ROOT 6.24.0
* GCC 10.2
* Ubuntu 18.04

**Comment by pcanal** [comment] 2021-04-22 19:40
Is there dictionary request for each of the template arguments?  One major change is that we no longer automatically generate the dictionary for an std::pair of "unknown" type.

So the one to check are:
```
Belle2::ECLChargedPidPDFs::InputVar
vector<Belle2::ECLChargedPidPDFs::InputVar>
unordered_map<int,vector<Belle2::ECLChargedPidPDFs::InputVar> >
unordered_map<int,unordered_map<Belle2::ECLChargedPidPDFs::InputVar,TF1*> >
unordered_map<Belle2::ECLChargedPidPDFs::InputVar,TF1*>
```
Usually the dictionary for STL collection are implicitly requested if they are used in a class that has a dictionary.

**Comment by daritter** [comment] 2021-04-28 07:54
I think I might have found the problem: The `Belle2::ECLChargedPidPDFs::InputVar` was in the linkdef but after the class using it (and implicitly requiring all the STL collections).

**Comment by daritter** [comment] 2021-04-28 13:11
Ok, seems that changing in the order in the linkdef didn't help.

`InputVar` is a enum defined inside of `ECLChargedPidPDFs` and all the STL collections are used in `ECLChargedPidPDFs`. Both dictionary and the enum dictionary is requested first in the same linkdef file.

**Comment by pcanal** [comment] 2021-04-28 13:38
:(

Then I need a reproducer to fix this ...

**Comment by daritter** [comment] 2021-04-28 15:24
Ok, this seems to reproduce it for me: [pairdict.tar.gz](https://github.com/root-project/root/files/6392968/pairdict.tar.gz)

```
sh make.sh 
root [0] 
Attaching file test.root as _file0...
Warning in <TClass::Init>: no dictionary for class pair<int,MyClass::MyEnum> is available
(TFile *) 0x61800003d880
root [1]
```

Let me know what I did wrong :D

**Comment by daritter** [comment] 2021-04-29 13:35
So, I have just added the missing dictionaries manually and this doesn't seem to cause any other issues for us. 

I am thus fine with lowering the priority to normal.

**Comment by daritter** [comment] 2021-05-05 12:14
@pcanal @Axel-Naumann I spoke too soon.

While I can request the dictionaries manually to get rid of the error I run into a problem when checking them:

In the pairdict example I can run the following in the root prompt

```
root [2] c = TClass::GetClass("std::pair<int,MyClass::MyEnum>");
root [3] b = c->GetListOfBases()
(TList *) nullptr
```

So the list of base classes doesn't exist.  While for a `std::pair<int,int>` I get the correct base class to `__pair_base<int,int>` and it does have a class pointer:

```
root [1] c = TClass::GetClass("std::pair<int,int>");
root [2] b = c->GetListOfBases()
(TList *) @0x7ffd1c3fce98
root [3] TBaseClass* bc = (TBaseClass*) *(b->begin())
(TBaseClass *) 0x1a678d0
root [4] *bc
(TBaseClass &) Name: __pair_base<int,int> Title:
root [5] bc->GetClassPointer()
(TClass *) 0x1a3e5f0
```

Now after adding `#pragma link C++ class std::pair<int, MyClass::MyEnum>+;` to the `linkdef.h` I get the following

```
root [1] c = TClass::GetClass("std::pair<int,MyClass::MyEnum>");
root [2] b = c->GetListOfBases()
(TList *) @0x7fff4c93b268
root [3] TBaseClass* bc = (TBaseClass*) *(b->begin())
(TBaseClass *) 0x19c4bd0
root [4] *bc
(TBaseClass &) Name: __pair_base<int,MyClass::MyEnum> Title:
root [5] bc->GetClassPointer()
(TClass *) nullptr
```

I do have the proper hierarchy but the `__pair_base` base class doesn't have a valid ClassPointer so I'm not convinced this is all working as intended. Now I can solve this weirdness as well by requesting the `std::_pair_base<T1,T2>` dictionaries as well.

But at this point I am a bit skeptical so I would like some confirmation that this is not just some stupidity on my side. 

I did make sure the example is reproducible with the vanilla ROOT 6.24 from `/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.24.00/x86_64-ubuntu18-gcc75-opt`. 
That required a slight reordering of the compile flags but otherwise it produces exactly the same. 
The slightly updated version: [pairdict_v2.tar.gz](https://github.com/root-project/root/files/6426959/pairdict_v2.tar.gz)

**Comment by daritter** [comment] 2021-05-06 06:49
Speaking of `std::pair`, it might not be related but I just now spotted an error message which wasn't present with 6.20 when calling `GetStreamerInfo()` on two of our classes:

```
TStreamerInfo::BuildOld:0: RuntimeWarning: Cannot convert pair<int,array<vector<Belle2::TOPPDFCollection::Gaussian>,512> >::second from type: array<vector<Belle2::TOPPDFCollection::Gaussian>,512> to type: vector<Belle2::TOPPDFCollection::Gaussian>, skip element
TStreamerInfo::BuildOld:0: RuntimeWarning: Cannot convert pair<int,array<float,512> >::second from type: array<float,512> to type: array<float,512>, skip element
```
where the members in the class are `std::map<int, array<...>>` (Gaussian is just a struct of 3 floats)

Now this could be something different but it does strike me as odd because it also happens for `std::pair`.

**Comment by ferdymercury** [comment] 2022-04-25 13:59
Maybe related: https://github.com/root-project/root/pull/10335

**Comment by pcanal** [comment] 2022-04-25 23:15
@daritter Following a series of changes almost completed by https://github.com/root-project/root/pull/10230 (and/or the v6.26 version mentioned above).    With those changes a lot of warning related to pairs have been removed.   Also unless there is an explicitly dictionary, the (platform dependent) base class maybe not be listed.   In particular the original complaints:

```
After switching to 6.24 (GCC 10.2) I see new warnings about missing dictionaries
```

is addressed.


```
TStreamerInfo::BuildOld:0: RuntimeWarning: Cannot convert pair<int,array<vector<Belle2::TOPPDFCollection::Gaussian>,512> >::second from type: array<vector<Belle2::TOPPDFCollection::Gaussian>,512> to type: vector<Belle2::TOPPDFCollection::Gaussian>, skip element
TStreamerInfo::BuildOld:0: RuntimeWarning: Cannot convert pair<int,array<float,512> >::second from type: array<float,512> to type: array<float,512>, skip element
```
Those sounds strange as they "seem" the same type.  To investigate one would need to look at the contains of the StreamerInfo for the pair (the actual numerical type of the element might be different).

**Comment by guitargeek** [comment] 2023-12-18 20:21
Hi @daritter, @pcanal, is this issue still relevant?

**Comment by dpiparo** [comment] 2024-02-03 09:30
Closing as the issue is not there in 6.30. Please do not hesitate to re-open if some new information becomes available.

**Closed by dpiparo** 2024-02-03 09:30 UTC
Labels: bug, priority:high, in:Dictionaries, in:I/O
