### ISSUE TITLE
A crash when trying to initialise a vector from a >1D numpy array in PyROOT

### ISSUE THREAD

**Issue by lwpiotr** [root-project/root#12718] opened 2023-04-26 08:36 UTC
### Describe the bug
This code crashes:
```python
import ROOT
import numpy as np

b = np.arange(2*2, dtype=np.uint32).reshape(2,2)
a =  ROOT.std.vector("vector<unsigned int>")(b)
```
 as described in https://root-forum.cern.ch/t/stl-vector-and-numpy-types-in-pyroot/54073/9

In general, it is impossible to initialise a multidimensional vector from a multidimensional numpy array in PyROOT.

This is problematic for two reasons:
1) Numpy arrays are perhaps the most popular holder for numeric data in Python in scientific cases
2) They allow for the exact specification of types, often needed for proper interaction with ROOT.

### Setup
self-compiled ROOT 6.28.00, Fedora 37, Python 3.11.3

**Comment by guitargeek** [comment] 2023-04-26 09:24
Hi! `vector<unsigned int>` is not a multidimensional vector, but a 1 d container>. What would you expect to happen instead of a crash then? That the NumPy array is implicitly flattened? I think that would be dangerous.

**Comment by lwpiotr** [comment] 2023-04-26 09:26
But this is ROOT.std.vector("vector<unsigned int>"), so a vector<vector<unsigned int>>...

**Comment by vepadulano** [comment] 2023-05-09 14:12
Hi @lwpiotr ,

Sorry for the slow response and thanks for reaching out! This is known, and it should have a fix in upstream cppyy. I will find some time to dig into the cause of the bug and backport the fix.

Cheers,
Vincenzo

**Comment by lwpiotr** [comment] 2023-06-21 10:48
Hello. Any news on the issue?

**Comment by dpiparo** [comment] 2024-02-05 07:24
still there in master.

**Comment by guitargeek** [comment] 2024-02-05 10:12
This will indeed be fixed by updating to the most recent `CPyCppyy`.

**Comment by dpiparo** [comment] 2024-02-06 09:37
We should remember to review all issues related to PyROOT once we update.

**Closed** 2024-03-19 16:47 UTC
Labels: bug, in:PyROOT

**Comment by lwpiotr** [comment] 2024-04-22 09:09
When can we expect this feature to be added to the ROOT releases?

**Comment by guitargeek** [comment] 2024-04-22 13:11
With ROOT 6.32, which will be out in May

**Comment by lwpiotr** [comment] 2024-04-22 13:12
Thanks!
