### ISSUE TITLE
[RF] Possible memory leak when running upper-limits with toys

### ISSUE THREAD

**Issue by luilongo** [root-project/root#9196] opened 2021-10-27 17:46 UTC
- [ X] Checked for duplicates

Dear All,
as discussed in a previous [issue](https://github.com/root-project/root/issues/7890),  we have observed an increase in the memory when method GetInterval of the HypoTestInverter is called (see for example this [slide](https://docs.google.com/presentation/d/1hpDIabM3pMOvooI2TH3hen0YpVy74YCg9XUNNw5prvk/edit?usp=sharing).  I've prepared a small example using root 6.22/00 on centos 3.10.0-1160.42.2.el7.x86_64, where I've only one bkg and one dummy signal sample, and I've performed an upper-limit scan with 10k toys (the workspace and .C file used for this test can be found [here](https://cernbox.cern.ch/index.php/s/FOxntIggyp89tt0).
As you can see from the picture below (it's a vimdiff of 3 different outputs of pmap), the allocated memory is increasing with the time (from the left to the right). I've also checked that for pmap the majority of this memory is flagged as dirty. 
![image](https://user-images.githubusercontent.com/80854397/139116392-29e8cadb-1f6d-4552-ba1b-c25d185f05d8.png)
Is there any way to limit the increase in memory? 

Best,
Luigi

**Comment by guitargeek** [comment] 2021-11-09 12:43
I have spent some time simplifying the reproducer significantly. This code snippet it enough to reproduce the memory leak:
```C++
#include "RooRealVar.h"

#include "TSystem.h"

void reproducer()
{
  ProcInfo_t pinfo;
  for(std::size_t i = 0; i < 10000; ++i) {

    RooRealVar x("x","x",0);
    RooRealVar y(x);

    if(i % 500 == 0) {
      gSystem->GetProcInfo(&pinfo);
      std::cout << i << " memory usage " << pinfo.fMemResident
                << " " << pinfo.fMemVirtual << std::endl;
    }

  }
}
```
For the memory increase to happen, it is important that both `RooRealVars` are defined in the loop.

Now that we have a simple reproduced, I will continue to investigate the problem later. This problem with the RooRealVar seems so general that we probably solve a ton of RooFit issues at once if we solve this problem here!

**Comment by guitargeek** [comment] 2021-11-12 15:00
Ok, so even after merging https://github.com/root-project/root/pull/9270 this issue needs to remain open because there are still more memory leaks in the full reproducer code provided in the first post of this PR.

**Comment by guitargeek** [comment] 2021-11-15 19:39
After my first PR, the remaining memory increase was dominated by a leak in `RooMinimizerFcn` that is now getting fixed in https://github.com/root-project/root/pull/9296.

However, after that PR the issue is still not fixed yet. There still remains a memory increase that is dominated by the memory waste of the RooFit memory pool for the RooDataSet. This next problem will be solved by https://github.com/root-project/root/pull/8324, but the change is too intrusive to make for the next ROOT release.

If I still have some time for new developments before the release, I will think about a way to switch off the memory arena at runtime.

**Closed** 2022-04-07 22:15 UTC
Labels: bug, in:RooFit/RooStats

**Comment by guitargeek** [comment] 2022-04-08 07:37
Ater merging https://github.com/root-project/root/pull/8324, I verified that the memory increase as reported in this PR is gone. Both with the code from the initial post and also with the simple reproducer that I wrote.
