### ISSUE TITLE
Possible optimizer optimization

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#9312] opened 2021-11-18 15:55 UTC
### Explain what you would like to see improved
`-O1` for cling spends considerable time in stressGraphics:

test | opt | non-opt
-----|-----|--------
stressGraphics.cxx | 57.68 | 16.13

We need to
- verify that it's the optimizer taking so long
- find out which pass is causing it
- consider disabling that pass by default, or reproducing and discussing with upstream what we can do

See also https://github.com/root-project/root/pull/9301

**Comment by eguiraud** [comment] 2021-11-23 10:47
]This rootbench benchmark](https://github.com/root-project/rootbench/blob/master/root/tree/dataframe/RDataFrameBenchmarks.cxx#L186-L205) that creates an artificially large jitted RDataFrame computation graph sees exploding runtimes with cling + O1.

Standalone RDF code that reproduces the problem:

```cpp
#include <ROOT/RDataFrame.hxx>
#include <ROOT/RLogger.hxx>

int main() {
  ROOT::RDataFrame root(1);
  std::vector<ROOT::RDF::RResultPtr<double>> dfs;
  for (auto i = 0u; i < 10000; i++) {
    const auto column = "x" + std::to_string(i);
    auto define = root.Define(column, "42.f");
    auto filter = define.Filter(column + " > 0.f");
    auto sum = filter.Sum(column);
    dfs.emplace_back(sum);
  }
  dfs[0].GetValue();
}
```

Actual generated code (the body of `void foo()` is what RDF passes to `TCling::Calc`, I added the `#include`s and the `using namespace std;` to make the thing compile standalone and the things in `namepsace __rdf` are passed to `TCling::Declare` when RDF jits): 
[jitted_code.zip](https://github.com/root-project/root/files/7587367/jitted_code.zip).

clang 13 goes from 16s to 2+ minutes when compiling that code without/with O1:
```
/tmp /usr/bin/time clang++ -c jitted_code.cpp (root-config --cflags | string split " ")
15.45user 0.42system 0:16.00elapsed 99%CPU (0avgtext+0avgdata 1104528maxresident)k
22712inputs+0outputs (161major+338726minor)pagefaults 0swaps

/tmp /usr/bin/time clang++ -O1 -c jitted_code.cpp (root-config --cflags | string split " ")
133.75user 0.37system 2:14.38elapsed 99%CPU (0avgtext+0avgdata 1089416maxresident)k
10280inputs+0outputs (115major+287793minor)pagefaults 0swaps
```

cling seems to do much worse, going from a few seconds to over 10 minutes if O1 is added.

**Comment by hahnjo** [comment] 2021-11-23 12:27
For `stressGraphics.cxx`, the explosion comes from interpreting generated C++ code. I'm attaching the largest instance, which is the last of 50 sub-tests: [sg50.zip](https://github.com/root-project/root/files/7587535/sg50.zip) (similar to Enrico, I added the `#include`s to make it compile standalone)
For this single file, Clang 12.0.1 (from C8S) takes 4s with `-O0` and 12s with `-O1`.

Looking at `Pass execution timing report` from `-ftime-report` shows, for `sg50.cpp` down to a time of 0.1s:
```
   1.5001 ( 71.7%)   0.0359 (  9.5%)   1.5360 ( 62.2%)   1.5395 ( 62.2%)  X86 DAG->DAG Instruction Selection
   0.3250 ( 15.5%)   0.3377 ( 89.2%)   0.6627 ( 26.8%)   0.6633 ( 26.8%)  X86 Assembly Printer
   0.0760 (  3.6%)   0.0040 (  1.0%)   0.0800 (  3.2%)   0.0801 (  3.2%)  Fast Register Allocator
```
for `-O0`, while for `-O1`:
```
   2.1491 ( 23.0%)   0.0050 (  1.7%)   2.1540 ( 22.4%)   2.1562 ( 22.4%)  Greedy Register Allocator
   1.8328 ( 19.6%)   0.0439 ( 14.7%)   1.8767 ( 19.5%)   1.8805 ( 19.5%)  X86 DAG->DAG Instruction Selection
   0.5354 (  5.7%)   0.0000 (  0.0%)   0.5354 (  5.6%)   0.5361 (  5.6%)  Combine redundant instructions
   0.2517 (  2.7%)   0.2238 ( 75.0%)   0.4755 (  4.9%)   0.4760 (  4.9%)  X86 Assembly Printer
   0.3088 (  3.3%)   0.0000 (  0.0%)   0.3088 (  3.2%)   0.3091 (  3.2%)  Control Flow Optimizer
   0.2958 (  3.2%)   0.0010 (  0.3%)   0.2968 (  3.1%)   0.2972 (  3.1%)  Machine Instruction Scheduler
   0.2617 (  2.8%)   0.0000 (  0.0%)   0.2617 (  2.7%)   0.2620 (  2.7%)  Merge disjoint stack slots
   0.1949 (  2.1%)   0.0070 (  2.3%)   0.2019 (  2.1%)   0.2021 (  2.1%)  Simple Register Coalescing
   0.1759 (  1.9%)   0.0000 (  0.0%)   0.1759 (  1.8%)   0.1761 (  1.8%)  Live Variable Analysis
   0.1414 (  1.5%)   0.0000 (  0.0%)   0.1414 (  1.5%)   0.1416 (  1.5%)  Combine redundant instructions #6
   0.1413 (  1.5%)   0.0000 (  0.0%)   0.1413 (  1.5%)   0.1415 (  1.5%)  Combine redundant instructions #7
   0.1411 (  1.5%)   0.0000 (  0.0%)   0.1411 (  1.5%)   0.1413 (  1.5%)  Combine redundant instructions #4
   0.1410 (  1.5%)   0.0000 (  0.0%)   0.1410 (  1.5%)   0.1412 (  1.5%)  Combine redundant instructions #3
   0.1408 (  1.5%)   0.0000 (  0.0%)   0.1408 (  1.5%)   0.1410 (  1.5%)  Combine redundant instructions #5
   0.1406 (  1.5%)   0.0000 (  0.0%)   0.1406 (  1.5%)   0.1407 (  1.5%)  Combine redundant instructions #2
   0.1359 (  1.5%)   0.0000 (  0.0%)   0.1359 (  1.4%)   0.1360 (  1.4%)  Branch Probability Basic Block Placement
   0.1342 (  1.4%)   0.0000 (  0.0%)   0.1342 (  1.4%)   0.1343 (  1.4%)  Machine Common Subexpression Elimination
   0.1065 (  1.1%)   0.0000 (  0.0%)   0.1065 (  1.1%)   0.1066 (  1.1%)  MemCpy Optimization
```
-> mostly register allocation and `instcombine`.

A similar picture for `jitted_code.cpp`:
```
   8.6377 ( 81.7%)   0.0066 (  0.7%)   8.6444 ( 75.4%)   8.6522 ( 75.4%)  Fast Register Allocator
   0.7586 (  7.2%)   0.7869 ( 87.4%)   1.5455 ( 13.5%)   1.5470 ( 13.5%)  X86 Assembly Printer
   0.5620 (  5.3%)   0.0794 (  8.8%)   0.6414 (  5.6%)   0.6424 (  5.6%)  X86 DAG->DAG Instruction Selection
   0.1600 (  1.5%)   0.0031 (  0.3%)   0.1632 (  1.4%)   0.1633 (  1.4%)  Prologue/Epilogue Insertion & Frame Finalization
   0.1125 (  1.1%)   0.0071 (  0.8%)   0.1195 (  1.0%)   0.1197 (  1.0%)  Two-Address instruction pass
```
for `-O0`, while for `-O1`:
```
  115.8049 ( 89.6%)   0.0191 (  2.1%)  115.8240 ( 89.0%)  115.9569 ( 89.0%)  Combine redundant instructions
   4.2064 (  3.3%)   0.1518 ( 16.6%)   4.3582 (  3.3%)   4.3642 (  3.3%)  X86 DAG->DAG Instruction Selection
   0.5607 (  0.4%)   0.5501 ( 60.0%)   1.1108 (  0.9%)   1.1122 (  0.9%)  X86 Assembly Printer
   0.8415 (  0.7%)   0.0053 (  0.6%)   0.8468 (  0.7%)   0.8477 (  0.7%)  Machine Instruction Scheduler
   0.7902 (  0.6%)   0.0112 (  1.2%)   0.8013 (  0.6%)   0.8022 (  0.6%)  Greedy Register Allocator
   0.6279 (  0.5%)   0.0060 (  0.7%)   0.6339 (  0.5%)   0.6345 (  0.5%)  Live Variable Analysis
   0.3958 (  0.3%)   0.0048 (  0.5%)   0.4006 (  0.3%)   0.4010 (  0.3%)  Simple Register Coalescing
   0.2857 (  0.2%)   0.0020 (  0.2%)   0.2877 (  0.2%)   0.2881 (  0.2%)  Combine redundant instructions #3
   0.2847 (  0.2%)   0.0021 (  0.2%)   0.2867 (  0.2%)   0.2871 (  0.2%)  Combine redundant instructions #2
   0.2842 (  0.2%)   0.0024 (  0.3%)   0.2866 (  0.2%)   0.2870 (  0.2%)  Combine redundant instructions #6
   0.2842 (  0.2%)   0.0015 (  0.2%)   0.2858 (  0.2%)   0.2861 (  0.2%)  Combine redundant instructions #5
   0.2837 (  0.2%)   0.0017 (  0.2%)   0.2854 (  0.2%)   0.2857 (  0.2%)  Combine redundant instructions #4
   0.2825 (  0.2%)   0.0017 (  0.2%)   0.2842 (  0.2%)   0.2846 (  0.2%)  Combine redundant instructions #7
   0.2828 (  0.2%)   0.0012 (  0.1%)   0.2841 (  0.2%)   0.2844 (  0.2%)  Machine Common Subexpression Elimination
   0.1977 (  0.2%)   0.0031 (  0.3%)   0.2008 (  0.2%)   0.2010 (  0.2%)  CodeGen Prepare
   0.1788 (  0.1%)   0.0036 (  0.4%)   0.1824 (  0.1%)   0.1826 (  0.1%)  Constant Hoisting
   0.1525 (  0.1%)   0.0040 (  0.4%)   0.1565 (  0.1%)   0.1567 (  0.1%)  Called Value Propagation
   0.1465 (  0.1%)   0.0070 (  0.8%)   0.1535 (  0.1%)   0.1538 (  0.1%)  Interprocedural Sparse Conditional Constant Propagation
   0.1317 (  0.1%)   0.0010 (  0.1%)   0.1327 (  0.1%)   0.1329 (  0.1%)  Machine Copy Propagation Pass
   0.1281 (  0.1%)   0.0019 (  0.2%)   0.1299 (  0.1%)   0.1301 (  0.1%)  Prologue/Epilogue Insertion & Frame Finalization
   0.1210 (  0.1%)   0.0016 (  0.2%)   0.1226 (  0.1%)   0.1227 (  0.1%)  Live Interval Analysis
   0.1161 (  0.1%)   0.0011 (  0.1%)   0.1172 (  0.1%)   0.1173 (  0.1%)  X86 Byte/Word Instruction Fixup
   0.1104 (  0.1%)   0.0037 (  0.4%)   0.1141 (  0.1%)   0.1143 (  0.1%)  Two-Address instruction pass
   0.1024 (  0.1%)   0.0026 (  0.3%)   0.1050 (  0.1%)   0.1052 (  0.1%)  Live Range Shrink
   0.1010 (  0.1%)   0.0007 (  0.1%)   0.1017 (  0.1%)   0.1018 (  0.1%)  Machine Copy Propagation Pass #2
```

Two more "fun" facts:
 * Clang built from LLVM `main` now takes almost 14 minutes!
 * GCC 8.5.0 (from C8S) needs around 12 minutes at `-O1` (compared to 9s at `-O0`).

**Comment by hahnjo** [comment] 2021-11-23 12:46
The commonality between the two cases seems to be that we generate a lot of code in a single function. The current hypothesis is that this makes some optimization (or their required analyses) explode because compilers perform better for a more balanced ratio of number of functions and their lengths.

We therefore want to
1. confirm that this is actually the case by creating a reproducer, ideally without including ROOT headers (but how hard can it be to generate some code...). If that also explodes, and confirms that performance is regressing with newer versions of LLVM, we can send that to `llvm-dev` and ask for help / advice.
2. For RDF graphs, we could try chunking the code into multiple functions when exceeding a certain threshold, because we do want optimizations without things exploding.
3. For the graphics code, we could just re-enable the existing [`#pragma cling optimize(0)`](https://github.com/root-project/root/blob/master/graf2d/gpad/src/TCanvas.cxx#L1891-L1894) because there we don't really care about optimizations.

**Comment by eguiraud** [comment] 2021-11-24 07:41
When we discussed I understood cling was doing much worse than clang, but that does not seem to be the case in the end..?

**Comment by hahnjo** [comment] 2021-11-24 07:43
No, that's another thing to investigate. But the first few factors can be understood via Clang, which should be easier for now. Then we can think about the rest.

**Comment by eguiraud** [comment] 2021-11-24 10:32
Uh. The `const char**` were introduced because `std::vector<std::string>` made _O0_ compile times explode, see https://github.com/root-project/root/commit/3c3fd99a671cade7ad9bfbd35cd301f4e299759b . Does it help if `string_view`s are also substituted with `const char *`?

I'm working on the chunking.

**Comment by hahnjo** [comment] 2021-11-24 10:37
> Does it help if `string_view`s are also substituted with `const char *`?

Yes, that's essentially what I did. However, it's a bit inconvenient because the `std::string_view`s travel all the way into the constructor of `RDefineBase`...

**Comment by eguiraud** [comment] 2021-11-24 10:44
we just need the `const char *` at that level in the callstack, we can build `string_view`s out of them down the stack. I'll do that asap.

**Comment by hahnjo** [comment] 2021-11-24 10:51
No, unfortunately that's not sufficient because of inlining. Which probably also means that the commit you linked above doesn't work anymore...

**Comment by hahnjo** [comment] 2021-12-02 16:03
With #9342, JIT time for 10k RDF nodes is down from 33.5s to 12.4s, compared to 8.7s with `-O0`. On Grafana, it's 17s versus 23s:

![Bildschirmfoto vom 2021-12-02 16-58-32](https://user-images.githubusercontent.com/1613332/144457487-c34e166b-179c-4a00-86f5-2c8d35a9857a.png)

`perf diff` says:
```
     0.24%     +1.26%  libCling.so               [.] llvm::AttributeList::hasAttribute
     2.27%     +1.22%  libc-2.28.so              [.] __memcmp_avx2_movbe
     1.76%     -1.10%  [unknown]                 [k] 0xffffffff9f603885
     0.03%     +0.85%  libCling.so               [.] llvm::TargetLibraryInfoImpl::getLibFunc
     2.76%     -0.84%  libCling.so               [.] (anonymous namespace)::DAGCombiner::AddToWorklist
     0.13%     +0.78%  libCling.so               [.] llvm::Value::getValueName
     1.69%     -0.63%  libCling.so               [.] clang::LookupResult::resolveKind
               +0.56%  libCling.so               [.] AddReachableCodeToWorklist
               +0.50%  libCling.so               [.] llvm::InstCombiner::run
               +0.49%  libCling.so               [.] (anonymous namespace)::DeadMachineInstructionElim::runOnMachineFunction
     1.47%     -0.49%  libCling.so               [.] llvm::SelectionDAG::Combine
     0.01%     +0.43%  libCling.so               [.] llvm::PMDataManager::findAnalysisPass
     0.02%     +0.39%  libc-2.28.so              [.] __memchr_avx2
     0.18%     +0.37%  libCling.so               [.] llvm::ConstantUniqueMap<llvm::ConstantExpr>::getOrCreate
               +0.36%  libCling.so               [.] computeKnownBits
               +0.35%  libCling.so               [.] llvm::SparseSolver<llvm::PointerIntPair<llvm::Value*, 2u, (anonymous namespace)::IPOGrouping, llvm::PointerLikeTypeTraits<llvm::Value*>, llvm::PointerIntPairInfo<llvm::Value*, 2u, llvm::PointerLikeTypeTraits<llvm::Value*> > >, (anonymous namespace)::CVPLatticeVal, llvm::LatticeKeyInfo<llvm::PointerIntPair<llvm::Value*, 2u, (anonymous namespace)::IPOGrouping, llvm::PointerLikeTypeTraits<llvm::Value*>, llvm::PointerIntPairInfo<llvm::Value*, 2u, llvm::PointerLikeTypeTraits<llvm::Value*> > > > >::visitInst
     0.03%     +0.35%  libCling.so               [.] llvm::CallBase::hasFnAttrOnCalledFunction
     1.15%     -0.34%  libCling.so               [.] llvm::FoldingSetBase::FindNodeOrInsertPos
               +0.33%  libCling.so               [.] llvm::removeUnreachableBlocks
               +0.32%  libCling.so               [.] llvm::hash_combine<llvm::MachineOperand::MachineOperandType, unsigned int, unsigned int, bool>
     0.02%     +0.32%  libCling.so               [.] llvm::Use::getImpliedUser
     0.71%     -0.31%  libCling.so               [.] clang::Decl::castFromDeclContext
     1.01%     -0.31%  libCling.so               [.] llvm::hashing::detail::hash_combine_range_impl<unsigned int const>
     0.79%     -0.31%  libCling.so               [.] llvm::SelectionDAG::AssignTopologicalOrder
               +0.29%  [JIT] tid 277295          [.] 0x00007fbc9e40e37a
     1.13%     -0.28%  libCling.so               [.] clang::Sema::isModuleVisible
               +0.27%  libCling.so               [.] (anonymous namespace)::PeepholeOptimizer::runOnMachineFunction
     0.89%     -0.27%  libCling.so               [.] llvm::ScheduleDAGSDNodes::BuildSchedUnits
     0.03%     +0.26%  libCling.so               [.] llvm::ValueHandleBase::AddToUseList
     0.74%     -0.24%  libCling.so               [.] AddNodeIDNode
     0.80%     -0.24%  libCling.so               [.] llvm::SelectionDAGISel::SelectCodeCommon
               +0.24%  libCling.so               [.] (anonymous namespace)::MachineCopyPropagation::CopyPropagateBlock
               +0.23%  libCling.so               [.] llvm::LivePhysRegs::removeDefs
               +0.22%  libCling.so               [.] llvm::ReachingDefAnalysis::processDefs
     0.79%     -0.22%  libpcre.so.1.2.10         [.] 0x0000000000001f72
     0.09%     +0.20%  libCling.so               [.] llvm::hashing::detail::hash_short
     0.58%     -0.20%  libCling.so               [.] llvm::FoldingSetNodeID::AddString
               +0.20%  libCling.so               [.] llvm::Value::stripPointerCasts
               +0.19%  libCling.so               [.] llvm::PointerMayBeCaptured
               +0.19%  libCling.so               [.] llvm::InstCombiner::visitGetElementPtrInst
               +0.18%  libCling.so               [.] getCalledFunction
               +0.18%  libCling.so               [.] (anonymous namespace)::MachineCSE::ProcessBlockCSE
     0.77%     -0.18%  libCling.so               [.] clang::UsingDirectiveDecl::getNominatedNamespace
               +0.17%  libCling.so               [.] llvm::SelectionDAGISel::ComputeLiveOutVRegInfo
               +0.17%  libCling.so               [.] llvm::InstCombiner::visitCallBase
     0.51%     -0.16%  libCling.so               [.] llvm::ScheduleDAGSDNodes::EmitSchedule
               +0.16%  libCling.so               [.] llvm::SlotIndexes::runOnMachineFunction
     0.03%     +0.16%  libCling.so               [.] llvm::Value::getName
     0.53%     -0.16%  libCling.so               [.] clang::NamedDecl::getUnderlyingDecl
     0.02%     +0.16%  libCling.so               [.] llvm::AttributeList::hasFnAttribute
               +0.16%  libCling.so               [.] llvm::AAResults::pointsToConstantMemory
     1.23%     -0.16%  libc-2.28.so              [.] malloc
```

Most of this makes sense to me:
 * optimization passes check function and parameter attributes that analyses put there
 * `instcombine` combines IR instructions, instead of SelectionDAG
 * and some other optimizations and analyses

I don't see anything obvious to go faster here. I propose we close this after disabling optimizations in the graphics code (@couet  are you taking care of this?).

**Comment by hahnjo** [comment] 2021-12-20 12:36
> I propose we close this after disabling optimizations in the graphics code

see #9467

**Closed by hahnjo** 2021-12-20 12:36 UTC
Labels: improvement, in:Cling
