### ISSUE TITLE
[ROOT-10465] rootcling ignores -W flag passed through ACLiC

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14574] opened 2024-02-04 18:16 UTC
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

From https://its.cern.ch/jira/browse/ROOT-10465

If I try to pass a -W flag to rootcling with:

```
gSystem->AddIncludePath("-Wno-narrowing");
```

and then I  compile a macro with:
```
.L . macro.C+kv
```

rootcling ignore this flag, even if it appears in the arguments.

See more details on the ROOT forum: [Changing ACLiC compilation flags](https://root-forum.cern.ch/t/changing-aclic-compilation-flags/36971/13?u=ccorti)

### Reproducer

As per the description

### ROOT version

Any

### Installation method

Any

### Operating system

Any

**Comment by hahnjo** [comment] 2024-02-13 10:17
After investigation, it turns out that the issue is slightly different than described above: `rootcling` *does* correctly honor the `-W` flag and the dictionary compiles fine. What's causing the problem is that upon loading the dictionary, some code is parsed again. This time it's under the Cling compilation flags and that's causing the error, unless changed with `EXTRA_CLING_ARGS="-Wno-narrowing"` on the command line. I propose we close this issue (and the JIRA equivalent).

**Closed by hahnjo** 2024-02-13 10:17 UTC
Labels: bug, fixathon
