### ISSUE TITLE
Strange overflow bin bar when plotting TH1D with X1 option

### ISSUE THREAD

**Issue by karuboniru** [root-project/root#16976] opened 2024-11-19 02:41 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

ROOT produces strange result when plotting after setting excessive range via SetRange/SetRangeUser, namely the "bar" over X axis can overlap between different bins
![plot](https://github.com/user-attachments/assets/ab04df44-614e-4921-bb53-793835b0082f)

### Reproducer

```cxx
#include <TCanvas.h>
#include <TH1D.h>
#include <TRandom.h>
#include <TStyle.h>
#include <array>
#include <memory>

int main() {
  gStyle->SetOptStat(0);
  auto c1 = std::make_shared<TCanvas>("c1", "c1", 800, 600);
  auto x_bins = std::to_array<double>({0, 0.3, 0.5, 0.6, 1.0});
  auto h1 =
      std::make_shared<TH1D>("h1", "h1", x_bins.size() - 1, x_bins.data());
  for (int i = 0; i < 1000; i++) {
    h1->Fill(gRandom->Gaus(0.5, 1));
  }
  h1->GetXaxis()->SetRange(-1, 6);
  h1->Draw("X1 E0");
  c1->SaveAs("plot.eps");
}
```

It seems that ths issue is related to non-uniform bin width, maybe related to the code where the bar with of the overflow bin is determined. 

### ROOT version

```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.32.06                        https://root.cern |
  | (c) 1995-2024, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Sep 23 2024, 00:00:00                 |
  | From tags/6-32-06@6-32-06                                        |
  | With clang version 18.1.8 (Fedora 18.1.8-3.fc41)                 |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------
```

This reproduces on many versions.

### Installation method

Self built

### Operating system

Linux Fedora 41

**Comment by dpiparo** [comment] 2024-11-19 07:19
@couet , was this fixed in master perhaps? I get:
```
Warning in <TAxis::TAxis::SetRange>: first < 0, 0 is used
Warning in <TAxis::TAxis::SetRange>: last > fNbins+1, fNbins+1 is used
```
![image](https://github.com/user-attachments/assets/dca407f2-dd74-42f5-9f9a-9826f57f12fb)

**Comment by karuboniru** [comment] 2024-11-19 10:22
So in master `TAxis::SetRange`/`SetRangeUser` no longer includes the overflow bin in the plot? This I think would be great as I have faced an issue where the overflow bin appears unexpectedly and thought this is a feature.

**Comment by dpiparo** [comment] 2024-11-19 20:45
I investigated more and what we are dealing with is a mismatch between the web based and traditional graphics. The former does not display the overflow/underflow bins, the latter does @linev @couet

**Comment by linev** [comment] 2024-11-20 09:27
Yes, looks like classical graphics displays overflow/underflow bins - which should never happens.
Output from @dpiparo answer produced with web canvas.

And storing in PS file always done with old graphics.

**Comment by couet** [comment] 2024-11-20 14:09
The range you specify for TAxis is invalid. In this issue [1] it was requested to print a warning in case of invalid range.
It was done via this PR [2]. It is a warning only, the code was not changed otherwise.
You can see the warning with:
```
root [0] auto h = new TH1D("h","h",10,0,1)
root [1] h->GetXaxis()->SetRange(-1,12)
Warning in <TAxis::TAxis::SetRange>: first < 0, 0 is used
Warning in <TAxis::TAxis::SetRange>: last > fNbins+1, fNbins+1 is used
root [2] .q
```
[1] https://github.com/root-project/root/issues/9917
[2] https://github.com/root-project/root/pull/14589

**Comment by couet** [comment] 2024-11-20 14:24
That said, the output of the classical graphics changes with an invalid range. That's strange. I am looking

**Comment by couet** [comment] 2024-11-20 15:05
So the old graphics is right.

**Comment by couet** [comment] 2024-11-20 15:19
> But if it allowed to draw overflow/underflow bins, one should draw them correctly.
> 
> Original error message - errors bar from these bins overlap range of first/last bin - which should not happen

I will check that

**Comment by couet** [comment] 2024-11-20 15:32
Indeed, the X error bars  of the overflow (underflow) bin is not displayed correctly in case of non equidistant bins. 
Example:
```
{
  gStyle->SetOptStat(0);
  double x_bins[5] = {0, 0.3, 0.5, 0.6, 1.0};
  auto h1 = new TH1D("h1", "h1", 4, x_bins);
  for (int i = 0; i < 1000; i++) h1->Fill(gRandom->Gaus(0.5, 1));
  h1->GetXaxis()->SetRange(1, 5);
  h1->Draw("E");
  h1->Draw("SAME");
}
```
<img width="747" alt="Screenshot 2024-11-20 at 16 22 19" src="https://github.com/user-attachments/assets/c2dc796d-7d10-4bb5-a32a-d7ec6921f035">

In case of equidistant bins it is correct:
Example:
```
{
  gStyle->SetOptStat(0);
  auto h1 = new TH1D("h1", "h1", 4, 0.,1.);
  for (int i = 0; i < 1000; i++) h1->Fill(gRandom->Gaus(0.5, 1));
  h1->GetXaxis()->SetRange(1, 5);
  h1->Draw("E");
  h1->Draw("SAME");
}
```
<img width="655" alt="Screenshot 2024-11-20 at 16 27 01" src="https://github.com/user-attachments/assets/82c06155-ac90-451c-96b2-d7eed19ac20c">

**Comment by couet** [comment] 2024-11-20 15:50
So, there are indeed two fixes to do:  
1-  In the web graphics because the over/underflow bin should be displayed in that case. 
2- In the standard graphics to fix the error bar display in case of non equidistant bins.

**Comment by karuboniru** [comment] 2024-11-21 01:54
Thank you for figuring out the problem, and the same behavior is also present when using SetRangeUser 
```c++
#include <TCanvas.h>
#include <TH1D.h>
#include <TRandom.h>
#include <TStyle.h>
#include <array>
#include <memory>

int main() {
  gStyle->SetOptStat(0);
  auto c1 = std::make_shared<TCanvas>("c1", "c1", 800, 600);
  auto x_bins = std::to_array<double>({0, 0.3, 0.5, 0.6, 1.0});
  auto h1 =
      std::make_shared<TH1D>("h1", "h1", x_bins.size() - 1, x_bins.data());
  for (int i = 0; i < 1000; i++) {
    h1->Fill(gRandom->Gaus(0.5, 1));
  }
  h1->GetXaxis()->SetRangeUser(0, 1.01);
  h1->Draw("X1 E0");
  c1->SaveAs("plot.eps");
}
```
I understand that the code path behind should be the same, but [the documentation](https://root.cern/doc/v632/classTAxis.html#ac85f8261dedc23bbe68f90afd196cdb8) did not mention what will happen if the range specified goes beyond the center of first or last bin. This behavior should be documented no matter how it is implemented to avoid surprises.

**Comment by couet** [comment] 2024-11-21 13:18
Indeed, the problem is not in graphics, but in `TAxis::GetBinWidth()`. We cann see it with the following example:
```
void overflow_bin_width(TH1* h, int bin) {
   printf("Bin Number          = %d \n",bin);
   printf("Bin Low Edge        = %g \n",h->GetXaxis()->GetBinLowEdge(bin));
   printf("Bin Up Edge         = %g \n",h->GetXaxis()->GetBinUpEdge(bin));
   printf("Bin Width           = %g \n",h->GetXaxis()->GetBinWidth(bin));
   printf("Computed Bin Width  = %g \n\n",h->GetXaxis()->GetBinUpEdge(bin)-h->GetXaxis()->GetBinLowEdge(bin));
}

void overflow_bin_width_test(){
  double x_bins[5] = {0, 0.3, 0.5, 0.6, 1.};
  auto h1 = new TH1D("h1", "h1", 4, x_bins);
  overflow_bin_width(h1, 0);
  overflow_bin_width(h1, 2);
  overflow_bin_width(h1, 4);
  overflow_bin_width(h1, 5);

}
```
Which gives:
```
root [0] 
Processing overflow_bin_width_test.C...
Bin Number          = 0 
Bin Low Edge        = -0.25 
Bin Up Edge         = 0 
Bin Width           = 0.3 
Computed Bin Width  = 0.25 

Bin Number          = 2 
Bin Low Edge        = 0.3 
Bin Up Edge         = 0.5 
Bin Width           = 0.2 
Computed Bin Width  = 0.2 

Bin Number          = 4 
Bin Low Edge        = 0.6 
Bin Up Edge         = 1 
Bin Width           = 0.4 
Computed Bin Width  = 0.4 

Bin Number          = 5 
Bin Low Edge        = 1 
Bin Up Edge         = 1.25 
Bin Width           = 0.4 
Computed Bin Width  = 0.25 

root [1] 

```
As you can see the Bin Width in not correct for over/underflow bins (5 and 0 in that case). It is different form the Computed bin width. For all other bins they are equal, as they should be.

**Comment by linev** [comment] 2024-11-21 13:28
Technically there is neither bin-width nor edges for overflow/underflow bins.
For these bins bin-width is always infinite.
Also lower edge of underflow bin and upper edge of overflow bin infinite.

Therefore I would expect following printout for underflow bin 0:
```
Bin Number          = 0 
Bin Low Edge        = -NaN 
Bin Up Edge         = 0 
Bin Width           = NaN
Computed Bin Width  = NaN
```
And if we want to paint such bins - they should be handled differently compared to normal bins.

**Comment by couet** [comment] 2024-11-21 13:31
Yes, but the 2 ways to get the bin width should be consistent.

**Comment by linev** [comment] 2024-11-21 13:32
> Yes, but the 2 ways to get the bin width should be consistent.

If they consistent and return NaN - this would not help for painting.

**Comment by couet** [comment] 2024-11-21 13:35
Exactly, I just tried to replace GetBinWidth but `h->GetXaxis()->GetBinUpEdge(bin)-h->GetXaxis()->GetBinLowEdge(bin)` in THIstPainter::PaintErrors. That fixes the problem. I will now see why GetBinWidth for non equisdant binninng is diffrent. PR coming soon.

**Closed** 2024-11-22 16:51 UTC
Labels: bug

**Comment by linev** [comment] 2025-01-23 08:34
For completeness - after PR #17386  overflow/underflow bins also shown with web graphics.
