### ISSUE TITLE
[RF] Crash when passing null pointer to RooFit::ConditionalObservables

### ISSUE THREAD

**Issue by AlkaidCheng** [root-project/root#10232] opened 2022-03-25 05:36 UTC
Since ROOT 6.26/00, passing a null pointer to RooFit::ConditionalObservables results in a crash. It does not crash for ROOT 6.22/xx and 6.24/06.

Reproducer:
```
import ROOT
ws = ROOT.RooWorkspace("ws")
# seg fault
ROOT.RooFit.ConditionalObservables(ws.set(""))
```
Tested ROOT versions that crashes: 6.26/00 (installed from conda), 6.27/01 (from swan bleeding edge)
Tested ROOT version that does not crash: 6.22/00 (LCG 98), 6.24/00 (LCG 100), 6.24/06 (LCG 101)

**Comment by guitargeek** [comment] 2022-04-13 10:16
Hi! Your code is wrong, the behavior of your code is undefined already 6.24/06. [RooWorkspace::set()](https://root.cern.ch/doc/master/classRooWorkspace.html#af505b7efdb0c2aae4a2e4234734ba51d) returns a null pointer if no set with the name exists, and then [ConditionalObservables](https://root.cern/doc/v624/group__Fitting.html#gacfb237547174cfe35e7d8f7570442f73) expects a RooArgSet by reference. So Python will dereference a null pointer in your example, which is undefined. It's surprising you didn't get a crash, but that was just chance.

In ROOT 6.26, the `ConditionalObservables` function is implemented differently, and in this new implementation you actually get a crash. This was good actually, because like this you got aware of the problem and can now fix the problem with the nullptr dereferencing in your code :)

**Comment by guitargeek** [comment] 2022-04-19 13:15
I'll close this issue, as the crash is caused by undefined behavior in the user code.

**Closed by guitargeek** 2022-04-19 13:15 UTC
Labels: bug, in:RooFit/RooStats
