### ISSUE TITLE
cling includer issue on ROOT version included from lcg toolchain

### ISSUE THREAD

**Issue by dcampora** [root-project/root#12458] opened 2023-03-08 21:48 UTC
Dear ROOT team,

I am attempting to compile LHCb's Allen with the following command on a RHEL9 machine with CVMFS:

```
mkdir build
cd build
cmake -DSTANDALONE=ON -DCMAKE_TOOLCHAIN_FILE=/cvmfs/lhcb.cern.ch/lib/lhcb/lcg-toolchains/LCG_103/x86_64_v3-el9-gcc11-opt+g.cmake -GNinja ..
ninja
```

Compilation works fine, but upon execution of the produced executable I encounter the following error:

```
$ ./Allen --sequence hlt1_pp_default
...
<<< cling interactive line includer >>>: fatal error: module file '/build/jenkins/workspace/lcg_release_pipeline/build/projects/ROOT-6.28.00/src/ROOT-6.28.00-build/lib/Vc.pcm' not found: module file not found
<<< cling interactive line includer >>>: note: imported by module 'MathCore' in '/cvmfs/lhcb.cern.ch/lib/lcg/releases/ROOT/6.28.00-98349/x86_64-centos9-gcc11-opt/lib/MathCore.pcm'
Failed to load module MathCore
Failed to load module Hist
Failed to load module ROOTBrowsable
Failed to load module Unfold
Failed to load module RHTTPSniff
...
Failed to load module SessionViewer
input_line_4:2:2: error: unknown type name 'include'
#include "TError.h"
 ^
input_line_4:2:1: error: expected unqualified-id
#include "TError.h"
^
input_line_4:4:2: error: unknown type name 'define'
#define _ClassDefInterp_(name,id,virtual_keyword, overrd) \
 ^
input_line_4:21:7: error: expected ';' after top level declarator
#undef ClassDef
      ^
      ;
input_line_5:1:2: error: unknown type name 'include'
#include "cling/Interpreter/DynamicLookupRuntimeUniverse.h"
 ^
input_line_5:1:1: error: expected unqualified-id
#include "cling/Interpreter/DynamicLookupRuntimeUniverse.h"
^
Failed to load module MathCore
Info in <TInterpreter::TCling::RegisterModule>: Module MathCore in modulemap failed to load.
```

Please note that the folder `/build/jenkins` does not exist in the machine I am building on.

**Comment by guitargeek** [comment] 2023-11-07 14:11
Hi! Sorry for the late reply. I'm closing this issue, because as you can see from these two lines, the problem is the mixing of two different ROOT builds:
```txt
<<< cling interactive line includer >>>: fatal error: module file '/build/jenkins/workspace/lcg_release_pipeline/build/projects/ROOT-6.28.00/src/ROOT-6.28.00-build/lib/Vc.pcm' not found: module file not found
<<< cling interactive line includer >>>: note: imported by module 'MathCore' in '/cvmfs/lhcb.cern.ch/lib/lcg/releases/ROOT/6.28.00-98349/x86_64-centos9-gcc11-opt/lib/MathCore.pcm'
```

You should double-check your environment. If you have any more questions, please reach out to us on the ROOT forum! The GitHub issues are more for bug reports, feature requests, and improvement requests. Thanks :pray:

**Closed by guitargeek** 2023-11-07 14:11 UTC
