### ISSUE TITLE
Broken serialization of  ROOT objects in python3 with dill  

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#6370] opened 2020-09-17 09:24 UTC
## Describe the bug

Serialization of ROOT  objects  in python using `dill` is broken for `python3`, but it works ok for `python2`.
  
( `dill` serialization is vital for the proper paralllel and distributive python calculations using `pathos` suite. The functionality of 
regular paralell python `pp`  and `multiprocessing` module  is very limited due to limitations of `pickle`` serialization, 
and it is a moment when `dill`/`pathos` enters the game, significantly extending the functionality
 

## Expected behavior

Similar behaviour for `python2`  and  `python3` is expected 
b ut it works for `python2` and fails for `python3`
 
## To Reproduce

to reproduce see this very simple gist 
    https://gist.github.com/VanyaBelyaev/278074969f2f940f180885be35f04db9 

It has been tested with different LCG releases   from LCG_94 to LCG_97a
and it always works for `pytjon2` and fails for `python3`

for `python3` one gets  an error
```
Traceback (most recent call last):
  File "./test_dill.py", line 13, in <module>
    hh = dill.loads ( dill.dumps ( h ) )
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/dill/_dill.py", line 294, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/dill/_dill.py", line 287, in dump
    pik.dump(obj)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 637, in save_reduce
    save(func)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/dill/_dill.py", line 1064, in save_builtin_method
    pickler.save_reduce(_get_attr, (module, obj.__name__), obj=obj)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/dill/_dill.py", line 1269, in save_module
    state=_main_dict)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/dill/_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/dill/_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 846, in _batch_appends
    save(tmp[0])
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 633, in save_reduce
    save(cls)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/dill/_dill.py", line 1330, in save_type
    StockPickler.save_global(pickler, obj)
  File "/cvmfs/sft.cern.ch/lcg/releases/LCG_97python3/Python/3.7.6/x86_64-centos7-gcc9-opt/lib/python3.7/pickle.py", line 960, in save_global
    (obj, module_name, name)) from None
_pickle.PicklingError: Can't pickle <class '_pythonization.compose_method.<locals>.composition_pythonizor'>: it's not found as _pythonization.compose_method.<locals>.composition_pythonizor
```

## Setup

 1. ROOT versions from LCG_94 to LCG_97a
 2. centos7, lxplus7.cern.ch 
 3. LCG-releases via cvmfs 
  

## Additional context

I've opened the issue also for `dill` project:  https://github.com/uqfoundation/dill/issues/356

**Comment by etejedor** [comment] 2020-09-22 10:32
Hi,

I believe this is a duplicate of https://sft.its.cern.ch/jira/browse/ROOT-10523.

I will close it and we continue here, is that ok?

So in the end is this due to the Python2 `save_global` vs Python3 `save_reduce` difference in dill?

**Comment by VanyaBelyaev** [comment] 2020-09-22 10:56
Hi Enrico, 
yes, it is the same issue:  combination of  `dill`+`PyROOT`  is fine for `python2`  but  it fails for `python3`...  (and separately both `dill` and `PyROOT` are fine for `python2` and `python3`.

**Comment by vepadulano** [comment] 2020-09-22 12:25
Hi @VanyaBelyaev ,
I ran your reproducer with LCG97apython3(ROOT 6.20/06) and LCG98python3(ROOT 6.22/00).
With the latter it seems that the call to `dill.dumps` is executed but I get a different error with a long stacktrace, I report the main parts:
```
...
input_line_38:16:29: error: allocating an object of abstract class type 'TInterpreter'
         *ret = new (arena) TInterpreter[nary];
                            ^
Error in <TClingCallFunc::make_ctor_wrapper>: Failed to compile
...
Error in <TClingCallFunc::ExecDefaultConstructor>: Called with no wrapper, not implemented!
Error in <TClingClassInfo::New()>: Call of default constructor failed to return an object for class: TInterpreter
Error in <TClass::New>: cannot create object of class TInterpreter
Error in <TBufferFile::ReadObject>: could not create object of class TInterpreter
TBufferFile::WriteObjectAny:0: RuntimeWarning: since TROOT has no public constructor
	which can be called without argument, objects of this class
	can not be read with the current library. You will need to
	add a default constructor before attempting to read it.


<class cppyy.gbl.TH1D at 0x560bc237aa20>


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/vpadulan/Programs/rootproject/rootinstall/v6-22-00-patches/lib/ROOT/__init__.py", line 119, in cleanup
    backend.gROOT.EndOfProcessCleanups()
ReferenceError: attempt to access a null-pointer
```

The line `<class cppyy.gbl.TH1D at 0x560bc237aa20>` is there because I added a print to your reproducer just to check that `dill.loads` is executed. Actually this is the simplest command to reproduce the same stacktrace:

```
python -c "import ROOT; import dill; print(type(dill.loads(dill.dumps(ROOT.TH1D()))))"
```

So it's possible that something in the new pyroot (default since 6.22) fixes the `dill` issue but triggers this other error.
@etejedor any thoughts?

**Comment by vepadulano** [comment] 2021-04-14 11:49
Hi @VanyaBelyaev,

I confirm the following simple commands both work with ROOT 6.22/08 and ROOT master
```
$ python2 -c "import ROOT; import dill; print(type(dill.loads(dill.dumps(ROOT.TH1D()))))"
<class cppyy.gbl.TH1D at 0x564a995e04e0>
$ python -c "import ROOT; import dill; print(type(dill.loads(dill.dumps(ROOT.TH1D()))))"
<class cppyy.gbl.TH1D at 0x559369cdb3a0>
```

They should be similar to your original reproducer, can you confirm this is fixed for you as well now?

**Comment by vepadulano** [comment] 2021-04-19 16:08
For our reference: apparently this was not working as late as 6.22/06
```
[vpadulan@lxplus706 ~]$source /cvmfs/sft.cern.ch/lcg/views/LCG_99/x86_64-centos7-gcc10-opt/setup.sh
[vpadulan@lxplus706 ~]$root --version
ROOT Version: 6.22/06
Built for linuxx8664gcc on Nov 27 2020, 15:14:08
From tags/v6-22-06@v6-22-06
[vpadulan@lxplus706 ~]$python -c "import ROOT; import dill; print(type(dill.loads(dill.dumps(ROOT.TH1D()))))"
TBufferFile::WriteObjectAny:0: RuntimeWarning: since TROOT has no public constructor
        which can be called without argument, objects of this class
        can not be read with the current library. You will need to
        add a default constructor before attempting to read it.
Error in <TClass::New>: cannot create object of class TROOT
Error in <TBufferFile::ReadObject>: could not create object of class TROOT
Error in <TSystem::TSystem>: only one instance of TSystem allowed
input_line_38:5:21: error: allocating an object of abstract class type 'TInterpreter'
         *ret = new TInterpreter;
```

**Comment by vepadulano** [comment] 2021-04-19 16:17
A bit more research: 
Apparently on lxplus also 6.24 cannot correctly use `dill`
```
[vpadulan@lxplus706 ~]$source /cvmfs/sft.cern.ch/lcg/views/dev4/latest/x86_64-centos7-gcc10-opt/setup.sh
[vpadulan@lxplus706 ~]$root --version
ROOT Version: 6.24/00
Built for linuxx8664gcc on Apr 14 2021, 14:33:50
From tags/v6-24-00@v6-24-00
[vpadulan@lxplus706 ~]$python -c "import ROOT; import dill; print(type(dill.loads(dill.dumps(ROOT.TH1D()))))"
TBufferFile::WriteObjectAny:0: RuntimeWarning: since TROOT has no public constructor
        which can be called without argument, objects of this class
        can not be read with the current library. You will need to
        add a default constructor before attempting to read it.
Error in <TClass::New>: cannot create object of class TROOT
Error in <TBufferFile::ReadObject>: could not create object of class TROOT
Error in <TSystem::TSystem>: only one instance of TSystem allowed
input_line_35:5:21: error: allocating an object of abstract class type 'TInterpreter'
         *ret = new TInterpreter;
```

But it seems that might be due to the `dill` version:
```
[vpadulan@lxplus706 ~]$python
Python 3.8.6 (default, Dec 11 2020, 21:40:36) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.__file__
'/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-centos7-gcc10-opt/lib/python3.8/site-packages/dill/__init__.py'
>>> dill.__version__
'0.3.2'
>>> quit()
```

[vpadulan@lxplus706 ~]$python
Python 3.8.6 (default, Dec 11 2020, 21:40:36) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.__file__
'/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Mon/x86_64-centos7-gcc10-opt/lib/python3.8/site-packages/dill/__init__.py'
>>> dill.__version__
'0.3.2'
>>> quit()

Because on my machine I can correctly run the reproducer with 6.22/08 and ROOT master, as I posted above. Indeed, I have `dill` 0.3.3 on my laptop. If I install `0.3.2` instead I get the same error from ROOT
```
vpadulan@fedorathinkpad-T550 [~]: python -m pip install dill==0.3.2
Defaulting to user installation because normal site-packages is not writeable
Collecting dill==0.3.2
  Downloading dill-0.3.2.zip (177 kB)
     |████████████████████████████████| 177 kB 762 kB/s 
Building wheels for collected packages: dill
  Building wheel for dill (setup.py) ... done
  Created wheel for dill: filename=dill-0.3.2-py3-none-any.whl size=78912 sha256=35e6366990c4e96b981d376a44de3e8f256a18b9b0250eacadd51602ad6740c4
  Stored in directory: /home/vpadulan/.cache/pip/wheels/93/7f/7d/78ec535a4340ef2696aad8b17fe8bb063d56301bd62881b069
Successfully built dill
Installing collected packages: dill
Successfully installed dill-0.3.2
vpadulan@fedorathinkpad-T550 [~]: python -c "import ROOT; import dill; print(type(dill.loads(dill.dumps(ROOT.TH1D()))))" 
TBufferFile::WriteObjectAny:0: RuntimeWarning: since TROOT has no public constructor
        which can be called without argument, objects of this class
        can not be read with the current library. You will need to
        add a default constructor before attempting to read it.
Error in <TClass::New>: cannot create object of class TROOT
Error in <TBufferFile::ReadObject>: could not create object of class TROOT
Error in <TSystem::TSystem>: only one instance of TSystem allowed
input_line_35:5:21: error: allocating an object of abstract class type 'TInterpreter'
         *ret = new TInterpreter;
```

So it might be that `dill` changed the way in which it retrieves information to serialize ROOT objects between the two versions, any thoughts @VanyaBelyaev ?

**Comment by vepadulano** [comment] 2021-04-19 16:50
Interestingly, going back at the first post
> It has been tested with different LCG releases from LCG_94 to LCG_97a and it always works for python2 and fails for python3

And indeed:
```
[vpadulan@lxplus706 ~]$source /cvmfs/sft.cern.ch/lcg/views/LCG_94python3/x86_64-centos7-gcc8-opt/setup.sh
[vpadulan@lxplus706 ~]$python
Python 3.6.5 (default, Sep 20 2018, 20:43:16) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> ROOT.__file__
'/cvmfs/sft.cern.ch/lcg/views/LCG_94python3/x86_64-centos7-gcc8-opt/lib/ROOT.py'
>>> import dill
d>>> dill.__version__
'0.2.8.2'
>>> quit()
[vpadulan@lxplus706 ~]$python -c "import ROOT; import dill; print(type(dill.loads(dill.dumps(ROOT.TH1D()))))"
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-56635/x86_64-centos7-gcc8-opt/lib/python3.6/pickle.py", line 918, in save_global
    obj2, parent = _getattribute(module, name)
  File "/cvmfs/sft.cern.ch/lcg/releases/Python/3.6.5-56635/x86_64-centos7-gcc8-opt/lib/python3.6/pickle.py", line 266, in _getattribute
    .format(name, obj))
AttributeError: Can't get local attribute 'compose_method.<locals>.composition_pythonizor' on <function compose_method at 0x7f58daa07268>
```

But you can see from the block above that the dill version is `0.2.8.2`. If instead the latest `dill` is installed, the issue cannot be reproduced anymore:
```
[vpadulan@lxplus706 ~]$pip install dill==0.3.3 --user
[vpadulan@lxplus706 ~]$python
Python 3.6.5 (default, Sep 20 2018, 20:43:16) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0, "/afs/cern.ch/user/v/vpadulan/.local/lib/python3.6/site-packages")
>>> import ROOT
>>> import dill
>>> dill.__version__
'0.3.3'
>>> dill.loads(dill.dumps(ROOT.TH1D()))
<ROOT.TH1D object at 0x89a1550>
>>>
```

So I'm even more convinced that this could be a `dill` issue rather than ROOT per se, what do you think?

**Comment by vepadulano** [comment] 2021-04-20 07:07
The commit that fixes the `dill` behaviour was introduced in this PR https://github.com/uqfoundation/dill/pull/382 . I tried applying that patch to an older dill version and it already solves the issue.

**Comment by vepadulano** [comment] 2021-04-26 10:30
Seeing that this was fixed in upstream dill, I will close the issue for now. @VanyaBelyaev feel free to reopen if the issue persists

**Closed by vepadulano** 2021-04-26 10:30 UTC
Labels: bug, in:PyROOT

**Comment by VanyaBelyaev** [comment] 2021-04-26 10:39
dear Vincenzo
than you very much for your studies. 
I am sorry - I was very busy with totally different stuff, but I hope to be able to test my code in May.
Should we ask to use a newer version of  dill for the next  LCG release? Whom should I ask for?

**Comment by vepadulano** [comment] 2021-04-26 17:06
Hi Vanya,
Probably the easiest thing to do is to open a ticket on the [SPI Jira](https://sft.its.cern.ch/jira/projects/SPI) to let them know they should update to latest dill to include the fix to this issue. Let me know if you need anything else :)

**Comment by VanyaBelyaev** [comment] 2021-04-27 07:36
Dear Vincenzo
done, see SPI-1879
thank you very much
