### ISSUE TITLE
cmake option -Dall=YES breaks the cmake

### ISSUE THREAD

**Issue by FonsRademakers** [root-project/root#15139] opened 2024-04-04 14:39 UTC
### Check duplicate issues.

- [X] Checked for duplicates

### Description

On macOS, running with cmake option `-Dall=YES` breaks cmake on `master`, on `v6.30.*` is works fine:

`cmake -G Ninja -Dall=YES -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3.9 ..`

```CMake Error: CMake can not determine linker language for target: RooBatchCompute_CUDA
CMake Error in roofit/batchcompute/CMakeLists.txt:
  Exporting the target "RooBatchCompute_CUDA" is not allowed since its linker
  language cannot be determined


CMake Error: CMake can not determine linker language for target: RooBatchCompute_CUDA
CMake Error in roofit/batchcompute/CMakeLists.txt:
  Exporting the target "RooBatchCompute_CUDA" is not allowed since its linker
  language cannot be determined


-- Generating done (0.8s)
CMake Generate step failed.  Build files cannot be regenerated correctly.```

### Reproducer

On `master` branch, on macOS, do:

```cmake -G Ninja -Dall=YES -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3.9 ..```

### ROOT version

master branch of today.

### Installation method

Build from source

### Operating system

macOS

### Additional context

_No response_

**Comment by dpiparo** [comment] 2024-04-04 15:11
@guitargeek is this due to the fact that we do not have this option in 6.30? And if yes, would it be enough to exclude the CUDA option from the set enabled by all on macOS?

**Comment by bellenot** [comment] 2024-04-04 15:31
FYI I can reproduce the error on Windows

**Comment by guitargeek** [comment] 2024-04-05 15:30
Closed by https://github.com/root-project/root/pull/15155.

**Closed by guitargeek** 2024-04-05 15:30 UTC
Labels: bug
